### ISSUE TITLE
Bug: Cordova Google Maps with ion-tabs, tabsHideOnSubPages

### ISSUE THREAD

**Issue by philipgriffin** [ionic-team/ionic#10533]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
Using tabsHideOnSubPages works for all sub-pages except when using the cordova map.
The tabs will show on that page but are unusable.

**Expected behavior:**
Ion-tabs should be hidden on all sub-pages.

**Steps to reproduce:**
Create an application with one sub-page.
Create a native map on the sub-page, with a height of 50%.
Set tabsHideOnSubPages to true in app.module.ts.
Navigate to subpage.

**Other information:**
I'm not sure of the hiding method used to hide the tabs but I know the map makes the web view transparent in some way. This is really killing my UX so even a hack at this stage would be good enough.

**Ionic info:** 
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.2.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks, we will look into this!

**Comment by philipgriffin** [comment]
To add more information to this I have created a new project which replicates the issue and can be cloned from here https://github.com/philipgriffin/ionic2MapsBug

The [README.md](https://github.com/philipgriffin/ionic2MapsBug/blob/master/README.md) of the project contains some screenshots outlining showing the issue in action.

**Comment by philipgriffin** [comment]
On the off chance anyone else is having this issue I managed to temporarily solve it with a hack.

Adding the below lines to the typescript file with the map

```
  ionViewDidLoad() {
    document.getElementsByTagName('html')[0].className += 'ion-tab-fix';
  }
  ionViewWillLeave() {
    document.getElementsByTagName('html')[0].className = '';
  }
```

Then adding this in the scss outside the page selector
```
.ion-tab-fix {

.scroll-content {
  margin-bottom: 0 !important;
}

.tabbar.show-tabbar {
  display: none !important;
}
} 
```

I did try adding the styles to just that page via the page selector but that resulted in the tabs being disabled everywhere so for now this is all I have working.

**Comment by philipgriffin** [comment]
On further inspection my CSS wasn't actually completely removing the ion-tabs so I have resorted to using this instead. It works but its clearly not ideal. The 'fix' is just for android but can easily be implemented on other platforms.

```
.ion-tab-fix {
  ion-tabs.tabs.tabs-md.tabs-md-white {
    height: 109.7% !important;
  }
}
```

**Comment by scarings** [comment]
hey @philipgriffin , did you fix that ? i have a same issue on ionic v3

**Comment by philipgriffin** [comment]
@scarings 

open `src/pages/your-page-with-map.scss`  and add the following outside the page selector:
```
  .ion-tabs-fix {
	   ion-tabs {
		height: calc(100% + 56px) !important;
	  }
  }
```
You can change the `56px` to whatever height your tabs are, default is `56px`.

Then go to  `src/pages/your-page-with-map.ts` and add the following:
```
	ionViewDidLoad() {
		document.getElementsByTagName('html')[0].className += 'ion-tabs-fix';
	}
	ionViewWillLeave() {
		document.getElementsByTagName('html')[0].className = '';
	}
```
Then test it on a real device, an important note is that if you have the application running with `livereload `make sure to quit the application and fully close it and re-open it or the change does not show.

If you can't get it working after that and can link or share your project with me I can have a look.

Normally you should be able to add just this under the page selector in the `map-page.scss` but it does not work.
```
ion-tabs {
	height: calc(100% + 56px) !important;
  }
```

**Comment by christianwico** [comment]
None of the above solutions are working. Is anyone even working on it for the past few weeks?

Having the exact same issue as well.

**Comment by philipgriffin** [comment]
@christianwico if you have a github repo or replication of the issue somewhere I'd be willing to try have a look for you.

**Comment by christianwico** [comment]
@philipgriffin I forgot to reply and call my issue off. But I *(perhaps temporarily)* resolved my issue by applying the **Google Maps** plugin to a *modal* instead of a *page*. Since modals **overlap everything** *(except the statusbar)*, it has given a possible solution should management decide to just go with a modal rather than a page.

*(Also, it's **kinda private** so I can't do such a thing as make the repo shareable.)*

**Comment by philipgriffin** [comment]
@christianwico  Ah I see. Here is another work around if you don't want to use the modal.

Import App
```
  import { App } from 'ionic-angular';
  constructor(public appCtrl: App) {}
```

and push your map page using this code..
`this.appCtrl.getRootNav().push(SecondPage);`

**Comment by scarings** [comment]
solution from me 
`ionViewWillEnter() {
    this.tabBarElement.style.display = 'none';
  }
  ionViewWillLeave() {
    this.tabBarElement.style.display = 'flex';
  }`

**Comment by haifzhan** [comment]
@philipgriffin It helps, thanks!

**Comment by haifzhan** [comment]
@jgw96 Any updates on this issue?

**Comment by wf9a5m75** [comment]
As far as I know, tabs control of `ionic3` and `ionic4` are no problem.
I have never used ionic2.

You guys need to understand how ionic native google maps displays the map view.
The map view is **NOT a HTML element**. It is a native view.
It means the map view is completely different object.
In order to display under HTML elements, `cordova-plugin-googlemaps` changes background color to `transparent` of parent elements of `map div(<div id="map_canvas">)`.

That's why map view is always behind browser view.
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

-----

Some JS frameworks hide elements just only `z-index` and `background color`.
But the `cordova-plugin-googlemaps` sets to `transparent`.
That's why you can see the other pages, but you can not touch it.
You need to manage those elements by yourself, such as `move it to outside screen` or `control visibility`.

-----

[AGM google maps](https://angular-maps.com/) is just a wrapper plugin of `Google Maps JavaScript API v3`.
It's still HTML element. That's why this problem does not occur.

[ionic-native/google-maps](https://github.com/ionic-team/ionic-native-google-maps) is a wrapper plugin of [Google Maps SDK for Android](https://developers.google.com/maps/documentation/android-sdk/intro), [Google Maps SDK for iOS](https://developers.google.com/maps/documentation/ios-sdk/intro), and [Google Maps JavaScript API v3](https://developers.google.com/maps/documentation/javascript/tutorial).
It's powerful than just a wrapper of Google Maps JS v3 API, but you need to manage this problem by yourself.

Choosing which one is depends on your purpose and priority.
