### ISSUE TITLE
Styling $segment-button-ios-height and $segment-button-ios-line-height has no effects

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#10645]
**Ionic version:**  (check one with "x")
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
Setting a value to $segment-button-ios-height and $segment-button-ios-line-height in variable.scss seems to have no effects.

Furthermore, according documentation, their size should be 3.2rem and 3rem where in fact they seems to be rendered with 2.6rem

**Expected behavior:**
Modifying $segment-button-ios-height and $segment-button-ios-line-height should have an effect.

Note: Modifying $segment-button-md-height and $segment-button-md-line-height works fine.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by brandyscarney** [comment]
Thanks for the issue! Sorry for the late reply on this. I believe you are using a segment in a toolbar, based on your statement that the value is `2.6rem`. Segments in a toolbar have a different `height`/`line-height` value than if you were to use them just in content.

There are different Sass variables for styling segment buttons when inside of toolbars. I tested the following and they are working properly:

```
$segment-button-ios-toolbar-button-height: 3.7rem;
$segment-button-ios-toolbar-line-height: 3.9rem;
```

These are documented under the Sass variables here: http://ionicframework.com/docs/api/components/segment/Segment/#sass-variables

These variables might not have existed when the issue was created, but since it has been resolved with the latest versions I am going to close this. If you think we could improve the documentation, please create an issue on our `ionic-site` repository: https://github.com/ionic-team/ionic-site/issues

Thanks! 🙂

**Comment by peterpeterparker** [comment]
@brandyscarney thx for taking the time to check this issue and for the feedback

**Comment by TomasKatz** [comment]
WHY THE FUCK AM I GETTING THESE MAILS ARE YOU FUICKING RETARDED?????

**Comment by jgw96** [comment]
Hey @TomasKatz , while I agree that the email notifications can get a little frustrating sometimes, we do ask that you follow our [code of conduct](https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md) at all times. Also, since this issue has been resolved I am going to lock this issue for now.
