### ISSUE TITLE
ion-col's wrap incorrectly

### ISSUE THREAD

**Issue by zakton5** [ionic-team/ionic#11006]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
<ion-row>
    <ion-col col-4>
        Col 1
    </ion-col>
    <ion-col col-7>
        Col 2
    </ion-col>
    <ion-col col-1>
        Col 3
    </ion-col>
</ion-row>
```

The HTML above will result in the 3rd column wrapping to a second line. I can't tell if this is a bug with flexbox itself or with the new ionic grid system, but I think its probably flexbox. Of course, adding the `nowrap` attribute to the `ion-row` fixes it, but I don't think that is how it is designed to work. For example,

```
<ion-row>
    <ion-col col-4>
        Col 1
    </ion-col>
    <ion-col col-4>
        Col 2
    </ion-col>
    <ion-col col-4>
        Col 3
    </ion-col>
    <ion-col col-4>
        Col 4
    </ion-col>
    <ion-col col-4>
        Col 5
    </ion-col>
    <ion-col col-4>
        Col 6
    </ion-col>
</ion-row>
```

should result in the 4th-6th columns wrapping to the 2nd line (which is what I want), but in reality, it looks like this

```
Col1   Col2
Col3   Col4
Col5   Col6
```

**Expected behavior:**
Proper wrapping of ion-cols when ion-row is set to `flex-wrap: wrap`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3 Build version 8E162

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you applying `margin` to the columns? They should look like this:

<img width="591" alt="screen shot 2017-04-03 at 11 17 04 am" src="https://cloud.githubusercontent.com/assets/6577830/24616452/23a3001a-185f-11e7-94ea-42f8f0f2970e.png">

but if you are adding margin they will wrap:

<img width="590" alt="screen shot 2017-04-03 at 11 17 13 am" src="https://cloud.githubusercontent.com/assets/6577830/24616453/23a3b9f6-185f-11e7-8f27-40d4102ea358.png">

I'd recommend against adding any `margin` property to the `.col` itself since this interferes with the width, and instead adding it to a child element of the column. Let me know if this is what you're seeing!

**Comment by zakton5** [comment]
No I checked the inspector and could not find any margin. There is however padding, as expected. Also, I forgot to mention that **I am only seeing this on iOS**.

**Comment by LloydVincent** [comment]
I was having this issue and it turns out the problem was a :before element added from a twitter bootstrap css file I had in the project. The offending code is:
`  
.clearfix:before, .clearfix:after, .container:before, .container:after, .container-fluid:before, .container-fluid:after, .row:before, .row:after {
  content: " ";
  display: table;
}
`
Apparently this :before element was taking up 1px of width on iOS, causing the grid to break on the top line.

Solved it with this:
`
ion-grid .row:before {
  width: 0;
}
`

**Comment by zakton5** [comment]
@LloydVincent That is probably my issue as well! Thanks for the suggestion. I'll look into it and respond later.
