### ISSUE TITLE
@IonicPage Deeplinker is double loading pages

### ISSUE THREAD

**Issue by GavinHellyer** [ionic-team/ionic#11122]
**Ionic version:**
[ x ] **3.x**

**I'm submitting a ...**
[ x ] bug report

**Current behavior:**
Refreshing the App in your browser with a hash bang url is setting the rootPage in app.components and then setting the page from the hash bang.

**Expected behavior:**
Deeplinker should not set the page if the same page is currently set.

**Steps to reproduce:**
I have updated my application to v3.0.1 and updated all Pages to Modules using @IonicPage(). When app.components.ts loads it does a storage check to see if there is already a user logged in, if there is it sets rootPage = 'HomePage', otherwise it will set it to 'LoginPage'. If I load the app at base route: http://localhost:8100/ it loads the login page and the url then changes to http://localhost:8100/#login. If I then refresh the page the application sets the rootPage to 'LoginPage' and then the DeepLinker navigates to 'LoginPage', causing the page to load twice.

There should be a way of detecting if the DeepLinker is going to cause a navigation change or have the DeepLinker not navigate to the page it is already on.

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.3.0
Xcode version: Not installed
```

**Comment by MvRemmerden** [comment]
Still happening in v3.5.0

**Comment by 5im0n** [comment]
You should use the navigation guard to prevent auth pages to be loaded.

```
  public ionViewCanEnter(): boolean {
    return this.userService.isAuthenticate;
  }
```

**Comment by salanford** [comment]
I've been battling this issue in vain trying to come up with a workaround with no success so far. Any recommended workarounds for this issue? I too have an authentication check in my app component page that either sets the page root to a home page or a login page depending on if the user is authenticated or not. I don't see how a navigation guard is of any use here since any "IsAuthenticated" function is going to always return true on page refresh as long as the token exists. I obviously can't require the user to re-authenticate every time they refresh the page.  

One approach I've been trying is to somehow compare the current page/route and skip the setRoot for the page if the page being loaded via the route is the same. However I haven't figured out a way to do this yet and I'm not sure it's the correct approach at any rate.

**Comment by danielehrhardt** [comment]
Same Issue here

**Comment by konrin** [comment]
@brandyscarney @kensodemann is there a move on this issue?

**Comment by danielehrhardt** [comment]
Yes same question. This issue is sometimes really annoying

**Comment by cmer4** [comment]
Yeah agreed and especially when your app has things like FCM notifications and logout (which is pretty common, such a refresh can mess a few things around. Like in my case i have widget page as "main page" which user gets to after login, if now they press "refresh" in their browser (and we should treat browser controls as source of truth ofc) - widget page gets loaded first and then gets loaded second time.

The current work around I have (not ideal) is to prevent loading that page second time completely:

```
if (this.nav.getActive() instanceof ViewController === false || this.nav.getActive().name !== 'WidgetPage') 
     {
        this.nav.setRoot('WidgetPage');
      }
```
