### ISSUE TITLE
ion-spinner is totally blurred in a popover

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#11265]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using ion spinner inside a popover shows a blurred version of the spinner. It looks like a spinning blurred cube:

![image](https://cloud.githubusercontent.com/assets/6171883/25171239/cc94240e-24f5-11e7-8d86-38555359604f.png)

**Expected behavior:**
The spinner shouldn't be blurred

**Steps to reproduce:**
1. Create a popover
2. Put `<ion-spinner>` inside it's component.

**Related code:**
```
<ion-spinner></ion-spinner>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic 3.0.1
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. We will look into this.

**Comment by bergergit** [comment]
Hi. Any solutions to this issue? I still see the problem even in latest Ionic version

**Comment by vpandiyan** [comment]
Still this issue persist. Is there any solution or fix available?

**Comment by briznad** [comment]
I've discovered, via Chrome's DevTools, that if you modify certain CSS rules which cause a redraw of the page, that can cause the grey box within the popover to turn into the expected spinner. I can reliably reproduce this when turning on/off `display: flex` on the `.popover-content` element. However, setting `display: block` in CSS doesn't fix it. This confirms for me that the issue is related to a limitation within Android WebView to reliably render SVGs when they're nested within multiple layers of elements that have "advanced" display settings - i.e. flexbox, absolute position, 3D transforms, etc. This is my guess.

**workaround**
For now I can workaround this issue by using the following self-animating svg in place of `<ion-spinner>` within the popover:
```html
<svg viewBox="0 0 64 64" width="28" height="28">
	<circle transform="translate(32 32) rotate(118.022)" r="26" fill="white" stroke="black" stroke-width="4" stroke-dasharray="128" stroke-dashoffset="82">
		<animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0" to="360" dur="0.75s" repeatCount="indefinite" additive="sum"></animateTransform>
	</circle>
</svg>
```
The animation isn't as smooth as the CSS version, but it'll do for now.
