### ISSUE TITLE
the device back button won't work if navigating to another page from popover elements

### ISSUE THREAD

**Issue by Abderrahmane-H** [ionic-team/ionic#11357]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
navigating to a page by clicking on a popover element makes the device back button useless.
the device back button won't get me back to the previous page but the navbar back button will do.

**Expected behavior:**
the device back button must get me back to the previous page

**Steps to reproduce:**

the back button device does not work only if the popover is not dismissed before navigating to new page.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v6.10.2
Xcode version: Not installed
```

**Comment by armeniopinto** [comment]
I am having the same problem.

I fixed it be re-using the `NavController` instance of the page that created the `Popover`, instead of the one supplied in the `Popover` constructor. For example:

    private navCtrl: NavController;
    
    constructor(private navParam: NavParams) {
        this.navCtrl = navParam.data.navCtrl;
    }

... and when you create the `Popover` do it like this:

`this.popoverCtrl.create(MenuPage, {navCtrl: this.navCtrl});`

**Comment by Abderrahmane-H** [comment]
it works. but it is just a workaround we need a fix for this.does the way you solved the problem have no effects on the navigation ?

**Comment by armeniopinto** [comment]
No effects at all. My case was actually a bit worse, as it wasn't even displaying the automatic back button in the `ion-navbar`. I think the problem here is that, for some reason, the new page doesn't get a history when navigation comes from the popover. Without history Ionic doesn't enable the `back` behaviour.

**Comment by Abderrahmane-H** [comment]
Thanks I am going to use the solution you gave me until there is a fix for this, and because I can use it with the NavPush and NavParams. :+1: 

I used to fix it by dismissing the popover before navigating:
`this.popoverCtrl.dismiss().then(()=>{
    //navigate to other page
})`
