### ISSUE TITLE
bug: Ionic 3 and ion-nav + lazy loading 

### ISSUE THREAD

**Issue by javico2609** [ionic-team/ionic#11602]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If I use 2 ion-nav in the app one for the sidemenu and another for the content each time the browser is updated because change the code in the sidemenu is shown instead of the menu items the RootPage is displayed

**Expected behavior:**
work fine.

**Steps to reproduce:**

**Related code:**

```
<div [class]="theme$ | async">
  <ion-split-pane when="md">

    <ion-nav [root]="rootPage" main #content swipeBackEnabled="false"></ion-nav>

    <ion-menu [content]="content">
      <ion-nav [root]="sideRoot" swipeBackEnabled="false"></ion-nav>
    </ion-menu>

  </ion-split-pane>
</div>
```
![image](https://cloud.githubusercontent.com/assets/12940555/25926275/b48e422e-35c4-11e7-9227-7f43778e07f2.png)

![image](https://cloud.githubusercontent.com/assets/12940555/25926300/d5cca9a8-35c4-11e7-94a6-9895956b7ea1.png)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

global packages:

    @ionic/cli-utils : 1.0.0-rc.2
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0-rc.2

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.2
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.2
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.7.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Would you mind posting a repo we could use to reproduce this issue?

**Comment by mburger81** [comment]
I have similar problem! We have a two level navigation. 
If we navigate to /main/configure, this means first ion-nav is loading man and second ion-nav is loading configure page. The problem is, if we navigate only to main, we will in the constructor load the default Page which is Dashboard. 
So this would be /main/dashboard

The problem is if we load directly /main/configure the construcor first will load Dashboard and then the framework as wanted loads ConfigurePage. 

So for me is not clear if this is a lazy loading and IonicPage bug or there is something we don't know. There is no now to check in construcor which is the requested page or url. Or if it exists, itbis not documented!

**Comment by javico2609** [comment]
maybe is not lazy loading, but i have the same code on different projects an work fine even using different ionic version.

**Comment by javico2609** [comment]
REPO
https://github.com/javico2609/angular-mvd-meetup

**Comment by mburger81** [comment]
@javico2609 Do you have still the problem??? Or does your repo work?

**Comment by javico2609** [comment]
@mburger81  yes i have still the problem, you can use the repo to reproduce this issue, kind regards

**Comment by kitkimwong** [comment]
http://roblouie.com/article/456/ionic-3s-lazy-loading-is-bad/

**Comment by q769073309** [comment]
+1
