### ISSUE TITLE
Ionic 2 / Ionic 3 Apps Painly Slow on windows 10 UWP

### ISSUE THREAD

**Issue by tryadelion** [ionic-team/ionic#11783]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ X] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Some ionic components run very sluggish and slowly on windows 10 UWP, while others work fancily.
For example, the AlertDialogs run very slow, sometimes even lagging for more than 4s, as some page transitions, while scrolling & BottomSheet Dialogs ( can't remember exact name) run perfectly fine. I think it might have to do with the animations, but visual studio doesn't provide any good ( that i know) profiling tool to test it.

The swipe on the List items for example only works with a mouse plugged in. Quite weird.

**Comment by mpaland** [comment]
Are you using Crosswalk or is it native?
Have you tried the actual conf-app on your hardware as a reference?

**Comment by tryadelion** [comment]
I am using the default ionic installation, isn't Crosswalk a android webview?

**Comment by jgw96** [comment]
Hello everyone, thanks for opening an issue with us, we will look into this.

**Comment by tryadelion** [comment]
I have reproduced the slowly-ness on:
(desktop)
 a windows 10 PC 16gb ram, a good graphic card and a intel i7
 a virtual machine Windows 10 with 8gb ram and a virtualized quad core.
(tablet)
HP 2gb ram average market tablet, has a core i3 processor, market price ~300$USD
Microsoft Surface 3 8gb ram core i5

On the surface it worked slightly better than on any other, it might come with some browser optimizations, but the settings bar button load time or list item clicks was over 1.5s on both my app and the conference app on most devices, with some punctual performance exceptions.

**Comment by mpaland** [comment]
@tryadelion Crosswalk is/was available for Windows, too. But not necessary anymore.
Which ionic version did you use in your tests? `ionic info` please.

**Comment by tryadelion** [comment]
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : windows 5.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.6.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by mpaland** [comment]
Okay, I can confirm this. Tested the latest conf-app **without** crosswalk plugin on my (speedy) notebook with:
```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : windows 5.0.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```
The conf app in prod mode is very laggy. Clicking on any menu/toggle/list item needs round about a second for any feedback/reaction.
I've seen this much faster in early ionic versions before.

...and there are big visual problems with the grid view in the speakers list and in hovering over the menu items, but that's another issue.

**Comment by tryadelion** [comment]
i must also add that i find myself unable to build it in --prod --release due to some build error i can't trace to any file, but i have to test more before submitting an issue, all my experiences are on development mode and --aot.

**Comment by digaus** [comment]
This has likely something to do with the Edge Engine... there are severel reports and it can be reproduced in the Edge Browser aswell. See #10009, #8710 and many more. More (list) elements result in longer click registration. I think it has something to do with how Edge handles the DOM-Elements... I also opened a ticket for the Edge Browser: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11555978/

**Comment by tryadelion** [comment]
Is there any workaround in the meanwhile that could mitigate the speeds? for example an ionic setting that disabled rendering touch and transition animations, those seem to be the worst.

**Comment by tryadelion** [comment]
Is there any update @manucorporat  @digaus  ?

**Comment by mpaland** [comment]
@tryadelion I think, if there were any fixes/updates on this topic, @manucorporat would have already announced them here.
As stated in #10009, problem seems to be the Edge rendering engine, but plain ng2 apps seem to be running fast on Edge. That being said, it's likely a topic which needs deeper inspection/debugging on Windows (or which should be even done by MS) and the ionic team is not so well equipped with Windows 10 machines.

**Comment by tryadelion** [comment]
i understand completely, @mpaland  , but i have a client that really wants his app released so i need to document the reason of the delays and keep him informed of the progress.

**Comment by ADCJustinH** [comment]
@tryadelion I've been working on windows on Ionic for almost a year now. The truth is ionic "supports" windows only as far as cordova does. It is not tested, considered, reviewed or anything as far as I've been able to tell. It's a small team, they're not bad guys, they just only have so many resources and have decided not to allocate much to windows support since there are few users there (on mobile anyway)

Now, I have an app in the windows store built with Ionic so I'm not saying you can't do it. I'm just saying you are more or less on your own and you should set your and your clients expectations accordingly.

**Comment by tryadelion** [comment]
@ADCJustinH  well i don't expect a miracle, but maybe some workaround help, like an option to disable *every single* ionic component animation so the rendering becomes faster, in the meanwhile.

**Comment by mpaland** [comment]
@tryadelion Have you tried to use the Windows Crosswalk plugin? Maybe this enhances performance.

**Comment by tryadelion** [comment]
@mpaland  do you have a link? i can only find the android one.

**Comment by ADCJustinH** [comment]
@mpaland @tryadelion Crosswalk can be used for windows desktop apps but not for UWP as far as I can tell (https://crosswalk-project.org/documentation/windows/deploy_windows_store.html) :/

**Comment by mpaland** [comment]
@ADCJustinH You are right, crosswalk is for Windows desktop only, not for UWP. Didn't know that exactly. Sorry for misleading.

**Comment by mtycholaz** [comment]
I just noticed this on the Edge Blog.

**Comment by graphefruit** [comment]
After this discussion is realy ongoing here I just want to share my thoughts/experience:

I had several issues with the UWP on ionic2 (v2) aswell, I decided to drop the "support" (I didn't even release it).

After launching Android and iOS I got bumbed by many people why there is no Windows-App outside, and they couldn't realy understand why I didn't publish anything.

Even so the app would work, I cant live with it, when a user needs to wait 2-3 seconds after clicking, and having lags while scrolling.

On my other app I needed to support windows-phone (earlier with windows 8.1) and now just UWP left.
This app is written in AngularJS 1.6. built on top with Angular-Material.

After I had many performance issues there myself I digged deep into this issues and fount out that minimizing CSS-Code already helps a lot.
Back then I reduced the build CSS-File from angular-material from 55k lines to 5k lines.

But as far as I experienced we can't dig to deep into the generated css. 
I've already opend an issue back then:  https://github.com/ionic-team/ionic/issues/10351

Even so Windows-Phone is short-handed, specialy in Germany and in bigger companies many have Windows-Phones which needs to be supported.

My2C

**Comment by tryadelion** [comment]
And many companies use surface tablets for professional services,  our clients would love to not have to bring in their ipad/tablet at work instead of the provided surface pro.

**Comment by graphefruit** [comment]
@tryadelion For the surface pro tablets, you could atleast try the Crosswalk version (I have no experience here, just using Crosswalk for Android)

"Other topic":
After I don't know your app and what it does: 
Maybe you could release a webbased version which could be opend with chrome on the surface tablets atleast.
It is not the best indeed, but atleast you could provide a solution

**Comment by tryadelion** [comment]
@graphefruit  Ionic-2 doesn't support cordova plugins on browser, and the app relies on many cordova plugins.
For the crosswalk-for-windows-desktop thing, i have yet to find an install guide for ionic 3/angular 4, it's not even on the official website, or atleast nowhere easily visible.

**Comment by mobidev111** [comment]
Crosswalk is deprecated and does not get maintained any more ([deprecation notice](https://crosswalk-project.org/blog/crosswalk-final-release.html)). Thus it doesn't make sense to base a solution on this.

To achieve a sustainable solution, Ionic needs to work flawlessly on plain MS Edge / Windows 10 incl. UWP apps. 

We need to identify the root cause of the problems, so that the ionic guys / Microsoft / others have a chance to provide bug fixes and that we can verify progress:
* If the cause are Edge rendering performance problems -> file issues with Microsoft
* If the cause are Edge quirks -> build workarounds into ionic components

--> let's compile a detailed list of issues - ideally reproducible with source code (e.g. based on the sources of the conference app).

@tryadelion @graphefruit @ADCJustinH @digaus @mpaland please share your detailed problem observations / debugging / profiling results:
* which ionic components are slow? which one are wrong?
* which parts become slow after which number of items?

**Comment by tryadelion** [comment]
which ionic components are slow? which one are wrong?
 - SpinnerDialog doesn't display ( being fixed in ionic-native)
- Buttons unresponsive ( 1-3s click lag)
- Dialog load times excessive ( 2 - 6s lag)
- swipeable items on lists don't work. there is no swipe.
- Page load times quite high (  1 - 6s lag)

The number of items doesn't seem to be the root of the issue, lists with ion-items scroll easily and laglessly with over 60 items.

Cards seem to induce lag, maybe the box shadow?

I've seen the ripple animation on click look very laggy on every element, maybe this is one of the causes.

**Comment by graphefruit** [comment]
@mobidev111 I don't wanna trigger a new topic about crosswalk but it still has is eligibility in many use cases and will be still used some time more.
Even though the marketshare of Android 4.1 to 4.3 is still 15%.
Also the performance of Edge is not the best at all (aside the issue with angular/ionic)

Because I've not installed the project on my Windows-Phone I'm not able to share details about the issue promptly.

Greetings

**Comment by mobidev111** [comment]
@graphefruit crosswalk is not relevant for this particular issue (ionic v2+ support on Windows 10). The major maintainers abandoned it, thus it doesn't help for the longer-term perspective. And it doesn't help at all for plain Edge website viewing of ionic v2+ apps.

**Comment by mobidev111** [comment]
As of now, ionic v2+ seems to be de-facto completely broken on Windows 10.

Does Microsoft still actively support Ionic in visual studio? The last ionic mentions date back to early 2016 ([msdn blog 1](https://blogs.msdn.microsoft.com/visualstudio/2016/03/30/build-ionic-apps-in-minutes-with-vs-code/), [msdn blog 2](https://blogs.msdn.microsoft.com/visualstudio/2016/08/03/create-high-quality-mobile-apps-with-ionic-visual-studio/)).

Pinging the microsoft guys: @ryanjsalva @axemclion @jmatthiesen 
* can you help to improve ionic support on windows?
* Are there any planned actions to improve ionic v2+ support? Any timelines? 
* Who at Microsoft is driving this? So that we can get in touch..

**Comment by mobidev111** [comment]
@mlynch @mhartington @jgw96
are there any planned improvements? is there any timeframe? 

 * please lay out some roadmap
 * whom can we notify at Microsoft? is there any contact/team you are working with?

**Comment by mhartington** [comment]
@mobidev111 having used ionic and windows uwp the other day, it is much improved. I'm going to lock this issue as the conversations here are not being constructive.
