### ISSUE TITLE
Ionic 3.0.0 side menu issue in RTL

### ISSUE THREAD

**Issue by jafaripur** [ionic-team/ionic#11805]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After upgrade to version 3.0.0, Sidebar Menu have error in RTL mode with side="left" option.

Before this version this is work correctly. I think the padding, margin which added in last versuib generate this issue.

```
rtl: add rtl margin, padding, position and border-radius (#11342) (a30379b)
```

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by AmitMY** [comment]
That is correct.
Due to some limitations in that PR, I had to place LTR first and RTL second, and so I overridden LTR by doing `right: auto` - for this case.
To fix this, there is a version with a seperation of LTR and RTL - https://github.com/driftyco/ionic/pull/11635
Along with a full fix for the menu side animation and gesture - https://github.com/driftyco/ionic/pull/11336

We try not to, but allow to break RTL functionality for now, with the purpose of having full functionality in the correct way soon.

Here is a quick fix for you for now - for menu on the right side - you will be able to fix it for left as well, no problem.
```
[dir="rtl"] ion-menu[side=right] > .menu-inner {
    right: auto;
    left: 0;
}
```
