### ISSUE TITLE
BUG: activator: 'ripple' doesn't work with mode: 'ios'

### ISSUE THREAD

**Issue by yozman** [ionic-team/ionic#11812]
I want to use ripple activator effect with ios.

I set the config to
```
  IonicModule.forRoot(AppComponent, {
      activator: 'ripple',
      hoverCSS: false,
      iconMode: 'ios',
      mode: 'ios',
      pageTransition: 'ios',
      swipeBackEnabled: false,
      tabsHideOnSubPages: true
    }),
```

but not work,

could you please tell me
what should I do?

**Comment by danielsogl** [comment]
Please post your ionic info output as described in the issue template.

Thank you

**Comment by jgw96** [comment]
Hello! We currently do not support ripple in iOS mode as that does not follow the design language for iOS. Because of this, I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#231
