### ISSUE TITLE
app is keep running

### ISSUE THREAD

**Issue by anivaisu** [ionic-team/ionic#11887]
Hi ,

I am using ionic 2 with localnotifications.

My app is received notification on when app is background or foreground.

When i forced app to exist.does not reeive notifications.

I need app is keep running like whatsup..

How can i do this.

Kindly advice me,

Thanks

**Comment by danielsogl** [comment]
Hey @anivaisu,
If you want to run your app in the background, you can use the background mode ionic native plugin here: https://ionicframework.com/docs/native/background-mode/

**Comment by anivaisu** [comment]
Thanks for ur reply.I also used this.

Here is my code.
 cordova.plugins.autoStart.enable();

It's also work on app is resumed.i ask when app is exit receive notifications

**Comment by Khalid-Nowaf** [comment]
Hi, @anivaisu, I think what you are looking for is `phonegap-plugin-push`, this will handle remote notifications from GCM for Android and APNS for IOS. the track is, the notification will be shown to the user in the notification center if the user clicks or tap on the notification, the notification will launch the app, then the notification handler will pick it up. so local notification only works when the app is running. whatsup use remote notification, and that's why you receives notification even if the app is not running. I encourage you to read the documentation https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#overview

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
