### ISSUE TITLE
bug(ngc): Referencing a page breaks with --prod

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#11920]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have code which works perfectly but not in `--prod`. When a user navigates to a page, I highlight which page they are currently on the the menu. 

This is what is meant to happen:
![ngc issue](https://cloud.githubusercontent.com/assets/2852839/26765119/705ba406-4975-11e7-9013-cf7a46b4c22c.gif)

This is what happens when running with a `--prod` build on a device:
![ngc issue 2](https://cloud.githubusercontent.com/assets/2852839/26765138/e81b1c6a-4975-11e7-94c3-34ea1e35852f.gif)

**Expected behavior:**
I am not expecting such different behaviour due to a `--prod` build. 

**Related code:**
Repo here: 
[ngcissue.zip](https://github.com/ionic-team/ionic/files/1050699/ngcissue.zip)

The `app.component.ts` class looks as follows:
```
pages: Array<{ title: string, component: any, isActive: boolean }>;

  constructor(public platform: Platform, public statusBar: StatusBar, public splashScreen: SplashScreen) {
    this.initializeApp();

    // used for an example of ngFor and navigation
    this.pages = [
      { title: 'Home', component: HomePage, isActive: false },
      { title: 'List', component: ListPage, isActive: false },
      { title: 'Test', component: TestPage, isActive: false }
    ];

  }

openPage(page) {
    // Reset the content nav to have just this page
    // we wouldn't want the back button to show in this scenario
    this.nav.setRoot(page.component);

    // set which page is active
    for (let p of this.pages) {
      p.isActive = false;

      if (p == page) {
        p.isActive = true;
      }
    }
  }

  ngAfterViewInit() {
    this.nav.viewWillEnter.subscribe(x => {

      for (let p of this.pages) {
        if (x.component.name === p.component.name) {
          p.isActive = true;
        }
        else {
          p.isActive = false;
        }
      }
    });
  }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.10
```

**Comment by AmitMY** [comment]
AoT build uglifies the code, and makes the `name` value on `Component` to be equal to "t" (in my testing at least), because first it uglifies the class's name, to be `t`, then when setting `name` it just copies that "t".

(your init for loop does: `if("t" === "t")` and sets isActive on everything)

I am not sure this should be considered a bug, and especially not a bug with ionic, probably with angular.

**Comment by jgw96** [comment]
Hey @dylanvdmerwe, you can check out the [conference app](https://github.com/ionic-team/ionic-conference-app/blob/master/src/app/app.component.ts#L164) for an example of how to achieve this functionality. @AmitMY is correct that your current logic will not work in prod mode because of how uglify works, but if you use the way we do it in the conference app it will work in prod mode.
