### ISSUE TITLE
3.4.0 - SCSS Mixin Conflicts (e.g. transform)

### ISSUE THREAD

**Issue by EbilPanda** [ionic-team/ionic#12062]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Error on serve/build/... after updating to 3.4.0:

```
sass: node_modules/ionic-angular/themes/ionic.mixins.scss, line: 506
            argument `$string` of `str-index($string, $substring)` must be a string Backtrace:
            node_modules/ionic-angular/themes/ionic.mixins.scss:506, in function `str-index`
            node_modules/ionic-angular/themes/ionic.mixins.scss:506, in mixin `transform`
            src/pages/testpage/testpage.scss:57
```

**Expected behavior:**

No error (was working with 3.3.0)

**Steps to reproduce:**

1. have own transform-scss-mixin
2. use the mixin
3. update to 3.4.0

**Related code:**
app.mixins.scss
```
@mixin transform($args...) {
    -webkit-transform: $args;
    -moz-transform: $args;
    -ms-transform: $args;
    -o-transform: $args;
    transform: $args;
}
```

page.scss:
```
@include transform(translateX(-50%));
```

**Other information:**

I think the issue raises because ionic implemented an own kind of transform-mixin -> maybe they should be encapsulated from user-code so that they don't conflict with each other or they should be named in a ion-way e.g. `ion-transform`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.0.3
```

**Comment by AmitMY** [comment]
The mixins should not be encapsulated from the user, as you should use them in your apps. (for multi directional support)
The naming of the mixins is the same naming as the css property they are "replacing".

For example, for your case, `@include transform(translateX(-50%));` generates both an LTR and an RTL version, and the RTL version is `translateX(50%)` - technically not `translateX`, but `translate3d`, but I will add `trasnlateX`.

About the naming conflicts - I don't think it is such a big problem, and that we should change the core's naming, because it is more intuitive this way. @brandyscarney, what you think?

*Note, regarding your mixin that adds prefixes - I believe the build process prefixes most things. @manucorporat is that correct?

**Comment by jgw96** [comment]
@AmitMY , was this fixed by the changes in 3.4.1 - 3.4.2?

**Comment by AmitMY** [comment]
@jgw96 Nope, it is not a bug... Brandy should be the one deciding on this issue, I think that keeping the current naming is good.

**Comment by brandyscarney** [comment]
Just to add a note on this issue - this will not be an issue in v4 since Ionic's Sass is not built with the project's Sass anymore.
