### ISSUE TITLE
what happen with ionic start projectname template

### ISSUE THREAD

**Issue by prasitnarkdee** [ionic-team/ionic#12124]
I just start a new project, look like the template is gone.  no /www/index.html

**Comment by AmitMY** [comment]
- This is more related to ionic-cli
- Please fill the issue template otherwise it is harder to help you.

I can understand this in two ways.
- If you don't have the `www` folder, it's ok. just run `ionic serve` once
- If you are trying to start a project type template, run `ionic start projectname`, and it will give you the template options, like menu, tabs, etc..

**Comment by prasitnarkdee** [comment]
about 2 hours ago I run
$ ionic start demo tabs
then I can build and test it on an emulator as well
after that around 30 minutes i try to start
$ ionic start myapp tabs
then i run it error like [screen shot](https://drive.google.com/a/netway.co.th/file/d/0B2Ux96IwybaCZEkweXU4d3N6aDQ/view?usp=sharing)

**Comment by AmitMY** [comment]
Your screenshot is requiring permissions. Please paste it in a comment

**Comment by prasitnarkdee** [comment]
oh sorry, it ok now.
it must run 
$ ionic serve 
it will create index.html in www

thank or help, I just surprise why first app can run.
