### ISSUE TITLE
ion-Input clearIcon only aprearing when used in conjunction with ion-item

### ISSUE THREAD

**Issue by Remco75** [ionic-team/ionic#12200]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using <ion-input clearInput> WITHOUT a wrapping <ion-item> the clear-input button does not appear when typing.

**Expected behavior:**
Using the ion-input on it's own will work. Sometimes you might want the function of the ion-input without the styling of the ion-item

**Steps to reproduce:**
http://plnkr.co/edit/sobZUdUpMH3aPYIauqub?p=preview

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time it is a requirement for `ion-input` to be a child of `ion-item` as `ion-input` inherits alot of styles (including for the clear button) from `ion-item`. Because of this, I am going to consider this a feature request and move this over to our internal feature request tracking repo. When we have evaluated and started working on this feature, I will move this back to the main repo here.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-feature-requests#264

**Comment by Remco75** [comment]
thnx for opening the feature request. Is there any way to get feedback on the progress of these matters? (this is no biggy ,was just wondering :-))
