### ISSUE TITLE
ion-tabs: Variable tabIcon

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic#12228]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[x] feature request (if intentional behaviour)
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Icon not changing.

**Expected behavior:**
The icon should be changed if the variable assigned to tabIcon changes.

**Steps to reproduce:**
http://plnkr.co/edit/iHUDXfoJBCqXa7ZI0UzS?p=preview
When clicking on the bulb-icon in the tabbar, the icon should be changed from `ios-bulb-outline` to `ios-bulb`. In the developer tools you can see `ng-reflect-name="ios-bulb"` is changed on the ion-icon, but the class stays the same.

Also the `enabled`-attribute is not dynamically assignable, but I think that should be an own issue?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. This is actually working as [this plunker](http://plnkr.co/edit/a1bz5QtSlJsRzcPf1kOd?p=preview) shows. The actual issue is that the `ios-bulb` icon and the `ios-bulb-outline` icon seem to be the same. Because of this, I am going to move this issue to the ionicons repo.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionicons#494
