### ISSUE TITLE
Zoom not working in ionic 3

### ISSUE THREAD

**Issue by thanhdn9120** [ionic-team/ionic#12232]
Hi everybody,
I'm using ionic 3, I want to slides images can zoom, but It's not working
Below is my code
```
<ion-slides zoom="true" initialSlide="0" class="center" pager="true" paginationType="bullets">
      <ion-slide *ngFor="let img of listImgs">
              <img src="{{img}}"/>
      </ion-slide>
</ion-slides>
```
I also try add class "swiper-zoom-container", but it only zoom center and will reset orginal when my finger release out mobile screen
```
<ion-slides zoom="true" initialSlide="0" class="center" pager="true" paginationType="bullets">
      <ion-slide *ngFor="let img of listImgs">
              <div class="swiper-zoom-container">
                  <img src="{{img}}"/>
              </div>
      </ion-slide>
</ion-slides>
```
Anybody can help me. I think it very simple but It's amazing that this function is not working.
Thanks,
Thanh Nguyen

**Comment by AmitMY** [comment]
- Please fill the issue template

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by pipoa** [comment]
@jgw96 , @mhartington  
I trace this issue from 2015 to 2018. Yes, 3 years, how many 3years we can have? It's a very easy and simple bug, what Ionic team did is just merge all user's issues to #5039 ([https://github.com/ionic-team/ionic/issues/5039]) . And finally point to an invalid url link, and CLOSED!! What? Really? YES, what ionic team did is to just CLOSE issues one by one but NOT SOLVE issues.

"Ionic Team's attitude is just close issues, not solve issues?"
If you don't believe , you can look around Ionic github issues , many issues,  they close issues just because no new comments added, "NOT" they solve the bug(s). People are waiting for solutions, they didn't write duplicated comments once and again. But, because the didn't produced trash comments, Ionic team close issues.
Further more, they use Ionic ROBOT to AUTOMATICALLY close issues with no new comments. Be Notice, to CLOSE,  not to SOLVE.

I dont know Ionic team has intension to develop Ionic or not. But from their attitude, I regret to select IONIC. If I have a new chance, I won't select IONIC again. 

sorry for the long post.

**Comment by mhartington** [comment]
@pipoa Please try to be respectful when posting issues. Support for this has been in the framework for some time.


 ```html
 <ion-slides zoom="true">
   <ion-slide>
     <div class="swiper-zoom-container">
       <img src="assets/img/dog.jpg">
     </div>
     <ion-label>Woof</ion-label>
   </ion-slide>
   <ion-slide>
     <div class="swiper-zoom-container">
       <img src="assets/img/cat.jpg">
     </div>
     <ion-label>Meow</ion-label>
   </ion-slide>
   <ion-slide>
     <div class="swiper-zoom-container">
       <img src="assets/img/fish.jpg">
     </div>
     <ion-label>Just keep swimming</ion-label>
   </ion-slide>
 </ion-slides>
 ```


As per the rest of your comments, as we've stated in our [blog post](https://blog.ionicframework.com/whats-the-issue-with-issues/), we have a bot to help us manage new issues and issues where there has been no comment from the reporter. This is to help manage the large amount of issues that get reported.
