### ISSUE TITLE
When using the ionic cordova build browser - prod, some android phones run white, and the ionic cordova build browser's mobile browser is not a white screen？？

### ISSUE THREAD

**Issue by xiaoman627** [ionic-team/ionic#12250]
The way to pack it is the ionic cordova build browser -- prod -- release, which USES ionic2, and android 7.0 shows a white screen,There's nothing wrong with that

**Comment by danielsogl** [comment]
@xiaoman627 You know how to open an Issue on GitHub correctly?

**Comment by xiaoman627** [comment]
@danielsogl It does not report anything wrong

**Comment by AmitMY** [comment]
- Can you please fill in the issue template in the first comment?
- What version of ionic, what version of android?

**Comment by xiaoman627** [comment]
@AmitMY It doesn't make any mistakes, it just shows a white screen。
Use ionic2, android7.0

**Comment by AmitMY** [comment]
I understand. However, to know your exact setup, and to make this issue more accessible, please fill in the issue template above.

**Comment by janpio** [comment]
This sound more like a question to be answered on https://forum.ionicframework.com/ than via an issue here. Please open a topic there, post the URL here and close this issue.

**Comment by jgw96** [comment]
Hello all! The issue here is happening because of the cordova browser platform. You can read [here](https://github.com/ionic-team/ionic/issues/11557#issuecomment-302123320) the details about why we do not recommend using the browser platform. If you want to run your app on an android device you should run `ionic cordova run android --prod`. Thanks for using Ionic!
