### ISSUE TITLE
[version3.5.0] dismiss function or remove function and navCtrl.push() use at a same time will accurs the backBtn not worked.

### ISSUE THREAD

**Issue by giscafer** [ionic-team/ionic#12326]
**Ionic version:**  (check one with "x")

 **3.5.0**

**I'm submitting a ...**  (check one with "x")
[ ] bug report

**Current behavior:**

naviagte to a new page，close current modal page，back button is not work.

**Expected behavior:**
back button is work fine;

**Steps to reproduce:**

**global config back btn**
```
     IonicModule.forRoot(MainApp, {
            tabbarPlacement: "bottom",
            backButtonText: '', // config back btn
            tabsHideOnSubPages: true,
            tabsHighlight: true
        }),
```

**Related code:**

**create a modal page**
```
 let myModal = this.modalCtrl.create('CertificationModalPage', {}, {
            cssClass: 'custom-modal'
});
 myModal.present();
```

** in the modal page to navigating to a new page  `UserInfoAuthenticationPage` **
```
  openUserAuthentication(): void {
    this.navCtrl.push(UserInfoAuthenticationPage);
    this.viewCtrl.dismiss();// if use the dismiss() function,back btn in page `UserInfoAuthenticationPage` is not work.
  }

```

![qq 20170712135444](https://user-images.githubusercontent.com/8676711/28103695-b13ca1bc-6709-11e7-917f-ae8888ffffee.png)

**Other information:**

```
local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0


```

**Comment by peterkelly** [comment]
Both `navCtrl.push()` and `viewCtrl.dismiss()` are asynchronous methods - both return a Promise, and you must wait for each respective promise to complete before proceeding. The best way to do this is to use `async`/`await`:

or, even better:

```
async openUserAuthentication(): Promise<void> {
    await this.navCtrl.push(UserInfoAuthenticationPage);
    await this.viewCtrl.dismiss();
}
```

Because `openUserAuthentication()` returns a Promise here, callers can also use the same technique to wait for its completion before doing something else if necessary.

**Comment by giscafer** [comment]
@peterkelly my code work fine at the old version 3.3.0，thks, i try it later

**Comment by peterkelly** [comment]
@giscafer There were some changes to navigation controllers in 3.5.0 (see https://github.com/ionic-team/ionic/releases) which may have resulted in your code breaking. I'm aware of at least one such bug, https://github.com/ionic-team/ionic/issues/12238, which has recently been fixed. Try with the latest nightly build (npm install ionic-angular@nightly) and see if the problem remains.

At any rate, I recommend using `await` as I've described above, as it's possible your code was only working by accident. Otherwise you risk the same class of bugs that can occur in traditional multi-threaded programming environments when synchronization primitives are used incorrectly.

**Comment by giscafer** [comment]
@peterkelly it both works fine  use the `ionic-angular@nightly` version，it's a bug for ionic-angular@3.5.0

```
async openUserAuthentication(): Promise<void> {
    await this.navCtrl.push(UserInfoAuthenticationPage);
    await this.viewCtrl.dismiss();
}
```

```
openUserAuthentication(): Promise<void> {
    this.navCtrl.push(UserInfoAuthenticationPage);
    this.viewCtrl.dismiss();
}
```
