### ISSUE TITLE
ionic using popTo specifc page

### ISSUE THREAD

**Issue by anivaisu** [ionic-team/ionic#12332]
I am using ionic2.

I need popTo specific page.

I tried to this

` this.navCtrl.popToRoot('CartPage');`
But i am getting this err

`Cannot create property 'direction' on string 'CartPage'`

How can i fix this issue.

kindly advice me,

Thanks

**Comment by dr1v3** [comment]
You should store somewhere your target page instance on create or another event via 
`  ionViewDidEnter() {
    targetPageInstance = this.viewCtrl.index;
  }`
and pop to it later with 
`this.navCtrl.popTo(targetPageInstance);`
You should use page instance, not page controller class because you can have several open page of this type in your navigation stack.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
