### ISSUE TITLE
bug: Ionic 3.x Toggle Component not rendering on few androids

### ISSUE THREAD

**Issue by anupmca** [ionic-team/ionic#12390]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>3.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Toggle component is not rendering properly on few latest Android phones like **Le X507** and  **Redmi 3S-Xiaomi** and few other for **Ionic 3.x**.
_With Redmi 3 Note, Moto G, Lenovo A6000. This issue not observed._
Button displayed with no background or too large button displayed.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Most likely this is happening because those devices do not use the stock chrome webview that comes with most android devices running Android 5.0 and up. Unfortunately some device manufacturers will use custom webviews instead of the stock chrome webview, and usually, these custom webviews have spotty api support and can be buggy. To get around this issue and make sure that your app is always running on a good chrome webview i recommend checking out [crosswalk](https://crosswalk-project.org/). Thanks!
