### ISSUE TITLE
bug(ion-input): autocapitalize=words capitalizes two characters

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#12426]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
![jul-20-2017 21-03-14](https://user-images.githubusercontent.com/2852839/28434246-f3e82b90-6d8e-11e7-93a0-522c7bc7fc70.gif)

Setting an `ion-input` to have the `autocapitalize=words` property should capitalize the first letter of every word. It currently capitalizes the first two chars, or every second char. 

**Expected behavior:**
Follow the `autocapitalize` rules as per: https://developers.google.com/web/updates/2015/04/autocapitalize

**Steps to reproduce:**
Run on iOS device (with wkwebview plugin). Not sure about Android.

**Related code:**

```
  <ion-list>
    <ion-item>
      <ion-icon name='md-person' item-left></ion-icon>
      <ion-label stacked>What is the Client's Name?</ion-label>
      <ion-input autocapitalize=words type="text" placeholder="Enter client's name"></ion-input>
    </ion-item>
  </ion-list>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 5.3.0
```

**Comment by davec21** [comment]
Looking at the comments of the posted google link... looks like this is due to browser issue not ionic. Someone else mentioned the same behavior as you as well as put a link to a polyfill they made.

**Comment by dylanvdmerwe** [comment]
Should ionic not include this polyfill by default then? Can you reference the other issue and the polyfill?

**Comment by davec21** [comment]
It could for sure. Link to the comment:

[https://plus.google.com/+AngelGrablev52/posts/emfbBSNMfGm]

**Comment by jgw96** [comment]
Hello all! @brandyscarney found out this morning that this is actually a bug in webkit itself. It was first reported in 2015, but here is a link to the latest bug report https://bugs.webkit.org/show_bug.cgi?id=157410 . I am not sure how we should progress on this at the moment since it is a bug in webkit itself, but just updating this issue.

**Comment by jgw96** [comment]
Hello all, after some internal discussion/testing we are going to close this as a `wontfix` for now. We tested both native inputs and `ion-input` and the same behavior happens in both because of the above bug. 
![image uploaded from ios](https://user-images.githubusercontent.com/8823093/29082947-bce4de20-7c2c-11e7-9819-4746b3f7aa37.jpg)

Because this is an issue in webkit itself, there is unfortunately not much we can do about it. I would recommend just following along on that webkit issue i linked to above to know when the fix hits webkit. Thanks for using Ionic everyone!

**Comment by jgw96** [comment]
Also, there are some 3rd party libs such as this one https://github.com/agrublev/autocapitalize that you can use to fix this behavior, but in my opinion its not worth the extra bundle size to get this behavior, but if you really need this functionality there are libs out there for it.
