### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by kukipei** [ionic-team/ionic#12463]
After updating my application to use angular 4.3.1 I have following warnings in my console after npm install:

`npm WARN ionic-angular@3.5.3 requires a peer of @angular/common@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/compiler@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/compiler-cli@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/forms@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/http@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/platform-browser@4.1.3 but none was installed.
npm WARN ionic-angular@3.5.3 requires a peer of @angular/platform-browser-dynamic@4.1.3 but none was installed.` 

Are you planning to update angular-ionic to use angular 4.3.1?

**Comment by danielsogl** [comment]
If they merge this PR: https://github.com/ionic-team/ionic/pull/12000 then yes!

**Comment by jgw96** [comment]
Hello all! We are slightly behind on updating to Angular 4.3.1 as it does not play well with some of our manual optimizations of compiled Angular code that we do in our build tools. We think that these optimizations are key as they help with bundle size and are working on updating them to work with the modified generated code that Angular 4.3 compiles. Thanks for using Ionic!

**Comment by rahul270393** [comment]
UNMET PEER DEPENDENCY @angular/core@4.4.6
 UNMET PEER DEPENDENCY @ionic-native/core@4.3.2
why i'm getting this problem please can someone help me

**Comment by srinivas444** [comment]
@rahul270393 its because of not installing the dependencies properly or they may be locally installed, but the path defined to npm is different. Then it will throw error in installing which dependencies are missing.
you can resolve by installing the UNMET dependencies globally.

example : npm install -g @angular/common@4.4.6

install each one by one.
its worked for me.

**Comment by srinivas444** [comment]
@rahul270393 its because of not installing the dependencies properly or they may be locally installed, but the path defined to npm is different. Then it will throw error in installing which dependencies are missing.
you can resolve by installing the UNMET dependencies globally.

example : npm install -g @angular/common@4.4.6

install each one by one.
its worked for me.
