### ISSUE TITLE
ionic serve command did not working

### ISSUE THREAD

**Issue by chomnit** [ionic-team/ionic#12510]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I don't see anything happen after i run command ionic serve

**Expected behavior:**
It should run my app on the browser

<img width="955" alt="screen shot 2017-07-30 at 12 47 06 pm" src="https://user-images.githubusercontent.com/6535394/28750964-698aaeb6-7525-11e7-891e-6eda9dc9c751.png">

**Comment by AmitMY** [comment]
Thanks for opening an issue.
Can you please move this to the app-scripts repo? `serve` is built in there.

**Comment by chomnit** [comment]
Hi @AmitMY, sorry I am pretty new to ionic. Could you please provide me in a brief answer? thank you so much.

**Comment by AmitMY** [comment]
[ionic](https://github.com/ionic-team/ionic) (npm: ionic-angular) is the repository for the framework itself - the angular modules and components.
[ionic-app-scripts](https://github.com/ionic-team/ionic-app-scripts) is the repository for the build processes, including `serve`
[ionic-cli](https://github.com/ionic-team/ionic-cli) (npm: ionic) is the cli, that manages ionic services, access to cordova, and access to `ionic-app-scripts`

Your issue is with `ionic-serve`, hence your issue should be moved to `ionic-app-scripts`.
I don't have moving privileges, so I can't do it automatically.

**Comment by chomnit** [comment]
@AmitMY , i go it.

**Comment by chomnit** [comment]
I will close this ticket and create new one here: https://github.com/ionic-team/ionic-app-scripts/issues/1157
