### ISSUE TITLE
ionic serve not working - Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

### ISSUE THREAD

**Issue by adilob** [ionic-team/ionic#12664]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I try to execute: ionic serve
I'm getting the error below:
Error: Cannot find module 'angular/tsc-wrapped/src/tsc'
**Expected behavior:**

Expect to run my ionic project

**Steps to reproduce:**

**Related code:**

```

```

**Other information:**

I need some help on this please.
My project was running yesterday and today started to give me this error.
As far as I understood, the new Ionic's version (3.8) merges some "cli" frameworks on it.
My guess is that the @angular/tsc-wrapped package is not merged or something related to it is broken.
Anyway, before open the issue I've tried some things, like:
- Downgrade npm to these versions: 5.2.0, 5.1.0, 4.6.1
- Remove the node_modules folder and package-lock.json and re-installing it
- Update all cli frameworks

But I'm still facing the error.
I'd really appreciate some help on this.

Thanks!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.8.0
    ionic (Ionic CLI) : 3.8.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v7.9.0
    npm               : 5.3.0 
    OS                : Linux 4.4
```

**Comment by adilob** [comment]
I tried to downgrade node to version 7.10.0 and it worked fine now.
Anyway, I think when I update the node I'll face the problem again.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I just tried this with a couple of different projects using ionic 3.8.1 and did not have the issue. Can you try using `3.8.1` and see if you still have the issue? If so, can you also provide an application via Git that demonstrates the issue?

Thank you for using Ionic

**Comment by Alvaroctal** [comment]
Hi, my project seems pretty broken since ionic left v3.6

`ionic serve --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 
        '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project', 
        local: true, binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', 
        libPath: 
        '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/ionic/dist/index.js' 
        }
[DEBUG] Daemon found (pid: 628)
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 
       --livereload-port 35729 - Ctrl+C to cancel
[16:41:59]  watch started ... 
[16:41:59]  build dev started ... 
[16:41:59]  clean started ... 
[16:41:59]  clean finished in 1 ms 
[16:41:59]  copy started ... 
[16:41:59]  transpile started ... 
[16:42:05]  transpile finished in 5.30 s 
[16:42:05]  preprocess started ... 
[16:42:05]  deeplinks started ... 
[16:42:05]  deeplinks finished in 71 ms 
[16:42:05]  preprocess finished in 72 ms 
[16:42:05]  webpack started ... 
[16:42:05]  copy finished in 5.65 s`

And then the prompt is returned with exit code 130.

ionic: 3.9.1
typescript: 2.3.4 (upper versions doesn't support rxjs at any versión (even 5.4.3 which is supposed to fix it))
OS: Mac OS 10.12.6
Node: 6.11.2 / 3.10.10

Extra: moving to typescript 2.4.* it starts watching, opens the browser and seems to work fine (but as I said, this version of typescript doesn't work with rxjs).

thanks in advance.

**Comment by kensodemann** [comment]
There have been known NPM related issues that have caused this. Since this is not an Ionic Framework related issue, I am going to close this. If you are still having this issue, I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
