### ISSUE TITLE
Template cache in ionic framework

### ISSUE THREAD

**Issue by swen-xiong** [ionic-team/ionic#12679]
**Ionic version:**  (check one with "x")
[ x ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

i used ionic framework to build a mobile version of my website (not a compiled add, but a webapp). The problem is that the framework loads (and maybe caches) all html templates in the first request. I'd like to disable it. I used
```
$ionicConfigProvider.views.maxCache(0);
```
and, for each state in stateProvider:
```
url: "/xxx",
cache: false,
```
but it resolves nothing. When i reset cache in the browser, the first request load all templates. How is it possible? thank you

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, since this is an Ionic V1 issue I am going to move this issue to https://github.com/ionic-team/ionic-v1. Please monitor and provide further updates to the issue over there.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-v1#297
