### ISSUE TITLE
URL navigation redirects to root page when using lazy loaded tabs template

### ISSUE THREAD

**Issue by MvRemmerden** [ionic-team/ionic#12680]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Whenever I try to navigate via URL, I get redirected to the root page.

**Expected behavior:**
Navigating via URL leads me to the site I actually requested.

**Steps to reproduce:**
I downloaded the lazyLoadTabs template by Mike, updated it to the most recent package.json and built it. You can find my repo here: https://github.com/MvRemmerden/ionic-tabs-url-bug

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.1.4
    npm  : 5.0.3 
    OS   : macOS Sierra

**Comment by mhartington** [comment]
This appears to be an issue with how nav parses the url to figure out what component to load. We'll need to revisit this. For now, to work around it, I modified the segment name for the tabs class

```diff
diff --git a/src/pages/tabs/tabs.ts b/src/pages/tabs/tabs.ts
index 6284915..f2545b0 100755
--- a/src/pages/tabs/tabs.ts
+++ b/src/pages/tabs/tabs.ts
@@ -1,6 +1,8 @@
 import { Component } from '@angular/core';
 import { IonicPage } from 'ionic-angular';
-@IonicPage()
+@IonicPage({
+  segment: `tabs-page`
+})
 @Component({
   templateUrl: 'tabs.html'
 })

```

**Comment by MvRemmerden** [comment]
Thanks for the quick fix, but it only works for the pages in the app that are there as tabs. If you visit a page that has been pushed on top on the view and reload the page, you get the following error:

Error: Uncaught (in promise): TypeError: Cannot read property 'match' of undefined

**Comment by kensodemann** [comment]
@MvRemmerden - I have duplicated the issue you are having with the child pages. We will have a look at that. It might be a few weeks as we're all hands on deck with a large refactor for Ionic 4 right now and not really fixing bugs presently. Bug fixing will resume shortly.

**Comment by kensodemann** [comment]
@MvRemmerden - I have found a workaround for the issue. If you set the `segment` in the parent to something other than what the `segment` would default to, it works.

So for your case, I modified the `home.ts` file as such:

```ts
import { Component } from '@angular/core';
import { NavController, IonicPage } from 'ionic-angular';

@IonicPage({segment: 'mi-casa'})  // this is the workaround...
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {

  }

  pushPage(){
    this.navCtrl.push('Detail')
  }

}
```

Now the only issue I have with it is that I cannot get the `defaultHistory` option to work (which is why my sample doesn't have it implemented), so when you refresh while on the child there is no back arrow.

**Comment by MvRemmerden** [comment]
Do I understand that correctly that the tabs.ts and every single .ts file needs to have an individual 'segment' set and then it works (except for the 'defaultHistory'?

**Comment by kensodemann** [comment]
Close. Not necessarily every single page component. Just `tabs.ts` and any page that will have a child page. So for the case of your sample app, just `tabs.ts` and `home.ts`

**Comment by lucasbasquerotto** [comment]
@kensodemann Is there a way to change the name that is given to the child tab in the url. From what I see, it uses the literal text, removing some symbols and changing the words to lowercase. If I have more than 1 language the url could be different (but I would want it to be the same). Also the url may be ugly in some cases (because of some symbols).

I have a tabs page that has a segment `project-view-tabs/:projectId`, and the first tab has the text as `Details` in one language and `Detalhes` in another. I would like that the url would **always** be `/project-view-tabs/123/details` if the project id is `123`. Or, if this is not possible, using the tab index:  `/project-view-tabs/123/0` (or `/project-view-tabs/123/1`). This way it would be **the same url** independently of the language.

Is there a way to achieve this? (Or are there any plans to support it?)

**Comment by Robinyo** [comment]
@lucasbasquerotto
 
See: https://forum.ionicframework.com/t/ionic-pwa-loading-the-wrong-first-page/130748/13?u=robinyo

**Comment by timsar2** [comment]
i found this issue will be appear with the second issue.
1- we have to save pages twice after each edit.
2- navigation to other page will be back to root page.

**Comment by uongvan09** [comment]
i have same issue @timsar2
