### ISSUE TITLE
Use of non-relative module imports fails at runtime

### ISSUE THREAD

**Issue by piotaixr** [ionic-team/ionic#12693]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
I have the current directory structure: 
- src
   - app
      - app.module.ts
   - common
      - auth
         - index.ts
         - AuthModule.ts

I added in `tsconfig`, under `compilerOptions`, `"baseurl": "src","`

In `app.module.ts` i have: 
```typescript
import { AuthModule } from 'common/auth'

[...]

@NgModule({
imports: [ AuthModule, [...] ], 
[...]
})
export class AppModule { }
```

When testing my app with `ionic serve`, the compilation is succesful but i have an error page saying:
```
Runtime Error
Cannot find module "common/auth"
Stack
Error: Cannot find module "common/auth"
    at Object.<anonymous> (http://localhost:8100/build/main.js:86024:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:50:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:86523:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:50:30)
    at http://localhost:8100/build/main.js:148:18
    at http://localhost:8100/build/main.js:151:10
```

When looking in the generated javascript, i found in `main.js`: 
```js
[...]
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7_ionic_angular__ = __webpack_require__(133);
throw new Error("Cannot find module \"common/auth\"");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_9__common_api__ = __webpack_require__(272);
[...]
```
so it seems that the problem is not in the compilation but in webpack (i would say its configuration as i have exactly the same code in an angular app and its working wonderfully)
**Expected behavior:**
Two possibilities:
- The compilation should fail and a warning should be displayed in the CLI output
- The dependency should be resolved correctly and the app should work normally

**Ionic info:**

```
cli packages: 

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 1.3.12
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.3.0
    npm  : 5.3.0 
    OS   : Linux 4.12
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

You can accomplish this via using a custom `webpack.config.js`. In order to do this:

1. mkdir config
2. cp node_modules/@ionic/app-scripts/config/webpack.config.js config/
3. modifiy tsconfig.json to have set the `baseUrl` (which you have already done)
4. modify the webpack.config.js as outlined in [this article](https://psamsotha.github.io/angular/2017/03/18/angular-webpack-absolute-paths.html). Basically, this just means adding `'../'` to `resolve.modules`
5. add the following lines to the `package.json` so the custom `webpack.config.js` is used instead of the default one.

```json
    "config": {
        "ionic_webpack": "./config/webpack.config.js"
    },
```

All of that said, I probably would just use relative paths. It is more in line with the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html). Specifically this bit:

```
A relative import is resolved relative to the importing file and cannot resolve to an ambient module declaration. You should use relative imports for your own modules that are guaranteed to maintain their relative location at runtime.

A non-relative import can be resolved relative to baseUrl, or through path mapping, which we’ll cover below. They can also resolve to ambient module declarations. Use non-relative paths when importing any of your external dependencies.
```

Thank you for using Ionic
