### ISSUE TITLE
I need help urgently. How do I streamline vender.bundle.js?

### ISSUE THREAD

**Issue by Eusen** [ionic-team/ionic#12727]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Since ionic serve is too slow to debug, it takes about 60 seconds for each compilation, so my project is migrated to angular/cli and debugged and packaged. But the packaged vender.bundle.js is 3 times the size of ionic packaged out of vender.js, and the loading speed is extremely slow! Now that the project is on the line, are there any good ways to streamline vendor.bundle.js's code?

**Comment by AmitMY** [comment]
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

- It seems like your question is about angular cli and not ionic's, so it will probably be best if you opened a support request with angular

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I agree with @AmitMY that since you are talking about Angular CLI you may get more traction by also asking in an Angular forum.

Thanks for using Ionic!
