### ISSUE TITLE
 Error: Your yargs-parser platform does not have Api.js

### ISSUE THREAD

**Issue by weitaoyang** [ionic-team/ionic#12752]
I get a error

E:\work\HAagrioa>ionic cordova platform add android
[INFO] Enabling Cordova integration.
> ionic config set integrations.cordova {} --json --force
[OK] integrations.cordova set to {} in .\ionic.config.json!
> cordova platform add android --save
× Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-android@~6.2.2

        Adding yargs-parser project...
        Error: Your yargs-parser platform does not have Api.js

cli packages: (C:\Users\Administrator\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.0
    npm               : 3.10.10
    OS                : Windows 7

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with Cordova. You may want to try raising this issue up to them to see if they have a fix for it. What happens if you run `cordova platform add android --save` from the command prompt while in the root of your project?

You can also try asking this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Others may have also run into this issue and solved it.

Thank you for using Ionic
