### ISSUE TITLE
Virtual Scroll Throws Error on Route Change if scrolling

### ISSUE THREAD

**Issue by tskweres** [ionic-team/ionic#12750]
Ionic V3

Testing on IOS device ( iPhone 7 )

I'm using a sidemenu app with virtual scroll on one of the pages.

If the user happens to scroll very fast, then opens the side menu, the virtual scroll list is still scrolling on the page.

If the user changes routes by clicking a link in the sidemenu, the virtual scroll throws an error:

`self.onScroll is not a function. ( in 'self.onScroll(ev'), 'self.onScroll' is null`

Any idea on how to tell virtual scroll to pause or to stop its scroll? I tried adding overflow hidden to ion-content and the ion-list, but to no avail

Tested on iPhone 7

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by tskweres** [comment]
My apologies - created a test app and can't reproduce it. Went back to my app, can't reproduce it. Changing routes while scrolling the virtual scroll seems to work fine.

**Comment by kensodemann** [comment]
Excellent!! Glad to hear it.

One more thing I should mention is that you may want to switch to using [WKWebView](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) instead of UIWebView. This is also consistent with [Apple's advice](https://developer.apple.com/documentation/webkit/wkwebview).

**Comment by jaybloke** [comment]
I'm also getting the same error when using VirtualScroll:

`self.onScroll is not a function. ( in 'self.onScroll(ev'), 'self.onScroll' is null`

The problem only occurs when the list is still scrolling when tapping the back button. So far, I have only been able to replicate the problem when using the iOS emulator.


![output](https://user-images.githubusercontent.com/564037/34474068-f5265fc4-efb4-11e7-8ede-69db2e97873b.gif)

I haven't switched to using WKWebView simply because WKWebView does not support custom schemes used by the native photo library plugin i am using in the app ( photo library uses cdvphotolibrary:// prefixes for images), so the issue could be related to UIWebView - it's hard to say.

Mark up:

```
<ion-header>
  <ion-navbar>
    <ion-title>{{ count }} Comments</ion-title>
  </ion-navbar>
</ion-header>
<ion-content no-padding no-bounce class="outer-content">
  <div text-center [class.hide]="!isLoading">
    <ion-spinner></ion-spinner>
  </div>
  <ion-list [class.hide]="isLoading" [virtualScroll]="reviews" no-lines approxItemHeight="116px">
    <div *virtualItem="let review" style="width: 100%; padding: 2px 0">
      <ion-card>
        <ion-item *ngIf="review.person">
          <rating [(ngModel)]="review.average" readOnly="true" float-right></rating>
          <text-avatar *ngIf="!review.person.avatar" [text]="review.person.salutation" item-left></text-avatar>
          <ion-avatar item-start *ngIf="review.person.avatar">
            <img [src]="review.person.avatar">
          </ion-avatar>
          <h2>{{ review.person.salutation }}</h2>
          <p>{{ review.created_at | amTimeAgo }}</p>
        </ion-item>
        <ion-item *ngIf="!review.person">
          <rating [(ngModel)]="review.average" readOnly="true" float-right></rating>
          <text-avatar text="FC" item-left></text-avatar>
          <h2>Former Customer</h2>
          <p>{{ review.created_at | amTimeAgo }}</p>
        </ion-item>
        <ion-card-content [innerHTML]="review.comment | MarkdownToHtml"></ion-card-content>
      </ion-card>
    </div>
  </ion-list>
</ion-content>
```

ionic info

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-sim : 6.1.2 
    Node    : v8.9.1
    npm     : 5.5.1 
    OS      : macOS High Sierra
    Xcode   : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

```

Would appreciate any pointers on how to fix the problem.
