### ISSUE TITLE
Browser Back Button: Tabs hidden

### ISSUE THREAD

**Issue by AlessandroSchneiderSignUP** [ionic-team/ionic#12759]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have implemented DeepLinker and navigation backwards through the browser works as expected. Whenever I click back on the browser the navigation with the tabs hides. If I reload the page, the navigation remains.

**Expected behavior:**

The tabs should stay.

**Steps to reproduce:**
see above

**Related code:**
My code is quite customized, so not sure what to post. What I realized is that when I click the tab button there is no output in the console from ionViewDidLoad. But when I hit the back button it loads ionViewDidLoad and prints the console. Maybe that's a clue?

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.6.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X Yosemite
Node Version: v7.9.0
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by AlessandroSchneiderSignUP** [comment]
I think it's loading http://localhost:8100/#/myjobs instead of http://localhost:8100/#/jobs/myjobs. So it's just loading the component belonging to the segment.

How can I fix that?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Since you say your code is quite customized I suggest starting with something like `ionic start debug-tabs tabs`, then make the minimal modifications necessary to show the behavior you are seeing.

I tried the above real quick, but did not have an your issue.

Thanks for using Ionic!

**Comment by AlessandroSchneiderSignUP** [comment]
Hello @kensodemann 
Thanks for your reply. I took the ionic start debug-tabs tabs app and did the following modifications according to https://ionicframework.com/docs/2.0.0/api/navigation/DeepLinker/ and  https://www.joshmorony.com/link-to-pages-via-urls-with-deep-linking-in-ionic/

1.) I added the DeepLinkConfig in app.module.ts
 ```
{links:[
      { component: AboutPage, name: 'AboutPage', segment: 'about' },
      { component: ContactPage, name: 'ContactPage', segment: 'kontakt' },
    ]
    }
```
2.) installed deep-link via npm
3.) import { IonicPage } from 'ionic-angular'; and @IonicPage() to each page


If you start the app >> click About tab >> Contact tab >> Back Button
then the Tabs are hidden.

**Comment by kensodemann** [comment]
@AlessandroSchneiderSignUP - thank you for your reply. Can you take what you describe above and create a sample application that demonstrates your issue and then share that via GitHub or [plunker](http://plnkr.co/edit/cpeRJs?p=preview)?

**Comment by AlessandroSchneiderSignUP** [comment]
@kensodemann  Thanks again
Here you go: https://github.com/AlessandroSchneiderSignUP/debug-tabs

**Comment by kensodemann** [comment]
Thank you for supplying that repo.

The issue comes down to parts of the app using deep linking and parts not. Deep linking works best if the whole app is set up to use it.

I updated your `app.module.ts` such that the deep link config looks like this:

```ts
    IonicModule.forRoot(MyApp, {}, {
      links: [
        { component: AboutPage, name: 'AboutPage', segment: 'about' },
        { component: ContactPage, name: 'ContactPage', segment: 'kontakt' },
        { component: HomePage, name: 'HomePage', segment: 'home' },
        { component: TabsPage, name: 'TabsPage', segment: 'tabs-page' }
      ]
    })
```

The back button then works as expected and the tabs stay in place.

I am going to close this issue. Please let me know if this fix works for you. If not, we can re-open the issue.

Thank you for using Ionic.
