### ISSUE TITLE
ion-datetime does not work when displayFormat="M" and initial value is null

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#12763]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ion-datetime does not work when displayFormat="M" and initial value is null. When the user selects a different value the model is not changed
See https://plnkr.co/edit/R8h9cw?p=preview

Note that everything works if you set:
1) displayFormat to smth else, for example "YYYY"
OR
2) set initial value to a valid datetime ISO string

**Expected behavior:**

ion-datetime should change its value as expected when the user chooses new value in the picker

**Steps to reproduce:**

See https://plnkr.co/edit/R8h9cw?p=preview

**Related code:**
See See https://plnkr.co/edit/R8h9cw?p=preview

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This works the same way if you use days instead of months. I believe it works properly with years but not with months or days because at least with years you have the bare minimum of information required to create an actual Date.

I will mark this as something to look at after the initial Ionic v4 release. To help us better understand your requirements, can you reply with a use case for this? Everything I can think of would probably be better handled, for example, by just having a select list where the user picks a month, but you could easily be attempting to accomplish something I am not thinking of, so a use case would be very helpful.

Thank you for using Ionic

**Comment by ryaa** [comment]
The use case is to have a credit card expiration controls - one for month and the other for year.
The month control should allow selecting a value between 1 to 12. Right now it does not work as I described initially unless I provide an initial value

**Comment by kensodemann** [comment]
OK, thank you.

A couple of workarounds in the meantime.

I don't know what the UI of your app looks like, but as a user of applications I would rather just enter the expiration date as a single thing as such:

```html
    <ion-item>
      <ion-label>Date:</ion-label>
      <ion-datetime displayFormat="M/YYYY" pickerFormat="M YYYY"></ion-datetime>
    </ion-item>
```

If this has to be two separate controls for some reason you could also use a couple of selects and build the date from there.

Just some thoughts.

**Comment by ryaa** [comment]
I also thought about single control for the entire expiration date however these to be separate. So this could be either two ion-select or smth else... or i will need to initialize the existing control with some default value. Thank you for the suggestions!

**Comment by kensodemann** [comment]
After internal discussions, the issue comes down to the fact that you cannot create a Date without the year. You can start with just the year and default the month to Jan 1st, or take a year and month and default to the first day of the month, etc.

So the only valid generic way to do this would be to have the user supply an initial seed date, which you already have to do.
