### ISSUE TITLE
Documentation about css and layouts

### ISSUE THREAD

**Issue by mokrea** [ionic-team/ionic#12797]
Hi Ionic Team!

First of all, congrats!! I've been using Ionic from the first release. Ionic 3 is a really good platform for apps and was a big improviment. But I am still having problem to implement the design( (and based on the ionic forum like this link https://forum.ionicframework.com/t/custom-modal-alert-with-html-form/47980)). It's a pain work create and change things like borders, round-borders, backgrounds, and etc. It's a pain cuz I'm not a css pro, I admit.

For those are css specialists (or from web dev), probably it's sounds wierd, but I spent 2 weeks to make the code and after one week I'm still doing the css trying create a customized box (like popover with round borders, background color, specific color for the header) for input data by the users. Yes, I'm not good on css.

I think there are devs with same problem. 

Could ionic improve the documentation about theming to give us more to deal with that, please? (maybe create topics, like the components, about buttons, headers, content.. and show to us with examples how to change the css for headers, buttons and explain the relation between headers and navbar, how to center things like inputs and etc)

**Comment by gabriellecozart** [comment]
I am another dev with the same problem. The documentation for functionality is great, but I can never find how to do what I want with the css through ionic's official documentation. I always have to search through sites like stack overflow.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I will urge that you ask these questions on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). The community can help you a lot with various CSS issues.

I am assuming you have already looked here: http://ionicframework.com/docs/theming/ (and at the child pages under there).

For more general CSS questions, I suggest consulting a site such as https://css-tricks.com

Another tool I often use is the Chrome inspection window, which allows you to see the current styles and why each style is applied, etc. I then use that to tweak the CSS until things look right, and then apply the minimal tweaks at the correct scope, preferring to set SASS variables if they exist to control things. Hopefully that made sense...

Since our documentation could always use improvement, and I think you have some good suggestions here on how to do that, I am going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#307
