### ISSUE TITLE
ionic install issue (  > npm install -g ionic@3.6 )

### ISSUE THREAD

**Issue by nirav4273** [ionic-team/ionic#12801]
npm ERR! sha1-eCA6TRwyiuHYbcpkYONptX9AVa4= integrity checksum failed when using sha1: wanted sha1-eCA6TRwyiuHYbcpkYONptX9AVa4= but got sha1-2OkxlXAs+UChEUaP3YoK LcfudIA 

tried  : npm cache -f clean / npm cache verify -g

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am closing this because it is not an issue with the Ionic Framework. You don't state which OS or npm version you are using, but if you are using Windows this could be a node/npm issue. See [this issue](https://github.com/ionic-team/ionic-cli/issues/2572) in the `ionic-team/ionic-cli` repo. Hopefully that helps you out.

FWIW, I was able to install the 3.6.0 ionic CLI on my machine without error, so I doubt there is an issue with the npm packages themselves:

```
~/Projects/Ionic/stencil (feat/testUtilities): npm -g remove ionic
removed 341 packages in 1.796s
~/Projects/Ionic/stencil (feat/testUtilities): npm -g install ionic@3.6
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic
+ ionic@3.6.0
added 135 packages in 9.029s
```

Question: why are you installing version 3.6.0 of the CLI? That is rather out of date. The latest version is 3.9.2. I suggest just doing `npm -g install ionic@latest` (once you get the npm version stuff sorted out if that is indeed the issue)

The latest version of `ionic-angular` (the ionic framework) is at 3.6.0, but that would not be installed globaly. That would be installed on a project by project basis.

Thank you for using Ionic
