### ISSUE TITLE
vendor.js is too big to use on mobile

### ISSUE THREAD

**Issue by yozman** [ionic-team/ionic#12851]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

hey guys,
thanks for build amazing framework ionic,
but the vendor.js is too big to use on mobile device,
it's more than 400kb without gzip

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is a large part of the reason that with `Ionic v4` we are moving to using web components, as well as built in lazy loading and code splitting. This will help to make that bundle smaller.

Note that it will still initially be on the larger size because of the use of Angular. However, that is also becoming more optimized over time, and eventually, you should be able to use Ionic with lighter weight frameworks such as VueJS or Preact.

Thank you for using Ionic

**Comment by yozman** [comment]
@keithdmoore 
amazing,
wish ur guys goal,
by the way i think angular is good enough

**Comment by yozman** [comment]
@keithdmoore 
I read about `Stencil` sourcecode.
do u mean ionic v4 will base on it.
and v3 can't compatible with v4?
like angular.js & angular 2?

**Comment by kensodemann** [comment]
@yozman - yes, Ionic v4 will use Stencil. In fact, that is why Stencil is being created.

As for compatibility, expect some breaking changes. Ionic v4 will not just be a drop in replacement of v3. There will be some breaking changes where the code will need to change in order to use it, but I would not expect _anything_ like the change from AngularJS to Angular.

**Comment by layinka** [comment]
@keithdmoore 
Will Ionic v4 use angular 5 too?
Should we expect a change to the routing system, maybe an adaptation of angular's routing system.
The current ionic routing system works well for mobile but has some snags for PWAs.

it will be good if we could get a tentative timeline for its release too
