### ISSUE TITLE
Prevent the keyboard from resizing the screen ionic 3

### ISSUE THREAD

**Issue by wuilmerj24** [ionic-team/ionic#12855]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ X] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have an input text when I click the keyboard comes out and the entire screen is resized. How can I prevent the screen from being changed?

**Expected behavior:**

Do not change the screen size

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by heidji** [comment]
so everybody who is interested in that topic will have to submit a support ticket separately?

**Comment by kensodemann** [comment]
@heidji - I would highly prefer that rather than do that, that any person interested in this topic go to the [support forum](https://forum.ionicframework.com) and search for the topic first and read what is there.

It is exactly for these sorts of questions that the community support forum exists. Same for the Slack channel, or StackOverflow. The knowledge of us all is much greater than the knowledge or any one of us, and those are the perfect forums for that.

This issues list, OTOH, is used in order to track bugs in the framework and so the framework developers can track what still needs to be worked on.
