### ISSUE TITLE
Push Plugin Warning during --prod

### ISSUE THREAD

**Issue by Barathwaja** [ionic-team/ionic#12919]
Getting WARNING like this during --prod but works correctly during --debug mode..

**Native: tried calling Push.hasPermission, but the Push plugin is not installed.
Install the Push plugin: 'ionic cordova plugin add phonegap-plugin-push'
Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.**

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If it turns out that this is a bug with the plugin itself, please open an issue at https://github.com/ionic-team/ionic-native, and please fully fill out the issue template that the Ionic Native repo has in place for issues. It will help get your issue resolved more quickly.

Thanks for using Ionic!
