### ISSUE TITLE
ionic --prod command doesn't work in ionic 3.x above with angular 4.2 above

### ISSUE THREAD

**Issue by Gamerakki** [ionic-team/ionic#12914]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When ever i try to run the app with --prod flag. It give me an error saying the deeplinks didnt return proper value and it get terminate

**Expected behavior:**
should run the app in production mode

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Angular version is pinned to version `4.1.3` in the latest starter because of build time optimizations that are done. Updating the Angular version breaks those optimizations (as you are seeing).

At this time, @danbucholtz is working on upgrading the version of Angular used for the next 3.x release of `ionic-angular`. Until that is out you should use Angular `4.1.3` in your project.

Thank you for using Ionic
