### ISSUE TITLE
ion-row dynamic attribute [class] drops the `row` class from the final HTML

### ISSUE THREAD

**Issue by amreladawy** [ionic-team/ionic#12924]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I am not sure if this an issue or not, but here I document the details in case someone needed it.

**Current behavior:**

`ion-row` is finally rendered as `<ion-row class="row" ></div>` . When using dynamic attribute value for `class` attribute, the final value of the `class` attribute loses the class `row` which makes the `ion-row` to act differently.

There is a workaround, which is to add the `row` class to the value of the dynamic attribute as following

```
<ion-row [class]="'row' + myClass" ></ion-row>
```

**Expected behavior:**

I think `ion-row` should ensure that class `row` is added to the final class value of the element.

**Steps to reproduce:**
 Here is a plunker case, and the relative code is below

http://plnkr.co/edit/3zeZyoMugPdICbu2TOYc?p=preview
**Related code:** 
```
<ion-row [class]="myClass" ></ion-row>
```

**Other information:**

**Ionic info:** :

``` 

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

System:

    Node : v6.11.2
    npm  : 5.4.2
    OS   : Windows 10
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The bug is in this line here: `<ion-row [class]="myClass" ></ion-row>`

At this point, Angular is doing exactly what you told it to do, which is replace any classes on this element with whatever is specified by `myClass`. So Angular is doing exactly what you told it to do.

If you need to dynamically add classes to the element, use Angular's [NgClass](https://angular.io/api/common/NgClass) directive.

Thank you for using Ionic
