### ISSUE TITLE
ionic upload not working 

### ISSUE THREAD

**Issue by Hybapps** [ionic-team/ionic#12980]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[* ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ *] bug report
[ ] feature request

**Current behavior:**
till two days ago every thing is working well
today I updates to ionic v 3.10.2

after that any project I try to serve or upload crashed in the Lint finished line and never move forwards
even when I reinstall version 3.9.2
The problem didn’t solved at all
even with the apps. which I have already uploaded before
today I upgrade to 3.12.0  and problem still exist  
I send the issue to the website support they answer that I have found an Issue in the Ionic framework and that I need to post it here so I did

**Expected behavior:**

```


![error](https://user-images.githubusercontent.com/18331545/30806934-0ba64f4e-a1f8-11e7-8a74-ab83afb43cef.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This sounds like it could be an ionic-app-scripts issue so I will move this issue over there. Please follow this issue over there. You are likely going to have to supply some sort of supporting information such as error log files that point to how website support determined this was an Ionic issue of some sort in order for us to help solve your problem. Otherwise, it is going to be very difficult to know what is going on.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1240
