### ISSUE TITLE
the navctrl canot  be use in httpclient interceptor

### ISSUE THREAD

**Issue by tangxuelei** [ionic-team/ionic#13026]
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

Current behavior:
I write a  httpclient interceptor to add some special request headers and filter some json response
such as  unify disponse some warn msg or 500 404code
and i need   navctrl.push the loginpage  when some json code,it errs navctrl canot be provdide 
I also try use to modalctrl to the loginpage ,but when i login suc ,it seems no way i know how to reload the page 

Expected behavior:
I need knwo if do this logininterceptor  code in httpclient interceptor  is best practice

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by kensodemann** [comment]
In my opinion, you should not inject the `NavContrlller` into any `HttpInterceptor`. This creates too tight of a coupling between your interceptor and the Ionic Framework. Ideally, you should be able to take the exact same interceptor and pick it up and use it in an Ionic Framework app, a straight up Angular app, or an app using Angular with some other Ionic-like framework without modification. If you inject `NavController` you cannot do that.

I suggest doing something like this:

1. create a shared service that will emit an "unauthorized" event (and perhaps also a "bad-response" or whatever event for the 500 errors)
2. add methods that trigger said event(s)
3. inject that service into the interceptor which will call the methods to trigger the events when appropriate
4. also inject that service into an appropriate component or page (probably the `AppComponent`) which will then listen for the event(s) and take the appropriate action

In this way, you then have a common interceptor and emitter service that can be used in any Angular based application, Ionic or not, rather than something that is specific to a given application written in a given framework.
