### ISSUE TITLE
Lose focus on the field when close keyboard

### ISSUE THREAD

**Issue by JamilHijjawi** [ionic-team/ionic#13039]
Is it possible to add attribute on ion-input and ion-searchbar components to prevent blur when close keyboard using back button on Android [I don't think this case is valid for iOS]

Ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.2
    ios-sim    : 5.0.11
    Node       : v8.5.0
    npm        : 5.4.2
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by JamilHijjawi** [comment]
Thank you for the fast resonse, But I think this request could be a new feature

**Comment by kensodemann** [comment]
OK, sorry, it sounded more like a question than a feature request.

In that case, please open a new issue with the issue template filled out. Be sure to check the box that this is a feature request, and fill out the sections stating the current behavior (or lack of functionality in this case), and in the "Expected Behavior" section explain how you would like this to work, being fairly specific about how you would like to see it work and exactly what use cases this feature would solve.

The "steps to reproduce", "related code" etc. is all more applicable to bugs than feature requests.

I will then move it to the "feature requests" repo where we catalog and prioritize them.
