### ISSUE TITLE
win10 execute ioinc command issue

### ISSUE THREAD

**Issue by kuangqifu** [ionic-team/ionic#13082]
My os is win10,I install Ionic with command "npm install -g ionic cordova",everything looks OK,but when I run "ionic start" command,normally,it should ask and wait me to enter my project name,but it just ask me but not wait me to wait,command quickly end.
"ionic start" command execute like this:
```
C:\WINDOWS\system32>ionic start
? What would you like to name your project:
C:\WINDOWS\system32>
```

execute "ionic start ionictest",it's the same([see here](https://stackoverflow.com/questions/46638242/win10-dos-execute-ioinc-command-issue)).I tried to update,and restart computer,but the same.

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Also, since this is not an Ionic Framework issue, but looks like it is an Ionic CLI issue, I ask that you open the issue in the (Ionic CLI repo)[https://github.com/ionic-team/ionic-cli]

Thanks for using Ionic!
