### ISSUE TITLE
Ionic android build prod failed in android

### ISSUE THREAD

**Issue by sarathscs** [ionic-team/ionic#13090]
i am using ionic 2 for hybrid application development. Once i build the android application using following command.

ionic build android --prod

I am getting the following error in my console. Whats the exact issue any one please suggest.

ionic-app-script task: "build"
[00:15:38]  Error: ./node_modules/ionic-native/dist/es5/plugins/plugin.js Module build failed: TypeError: Cannot read
            property 'type' of undefined at Object.getEffectiveTypeAnnotationNode
Following is my ionic information:

 Cordova CLI: 6.5.0
Ionic Framework Version: 3.6.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed

 i am really stuck with this issue. Please help!!!

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. Since this is not an Ionic Framework issue, I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Also, have a look at this SO question. It may be helpful: https://stackoverflow.com/questions/45301203/no-resource-found-that-matches-the-given-name-attr-androidkeyboardnavigationc

Thanks for using Ionic!
