### ISSUE TITLE
Screen orientation bug in IOS

### ISSUE THREAD

**Issue by oguzuncu** [ionic-team/ionic#13124]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The bug is that the current orientation of a ios device displays landscape when it is in portrait mode and visa versa.

**Expected behavior:**

The expected behavior is that it displays landscape when it is actually in landscape mode and the same for portrait mode.

**Steps to reproduce:**

Just try the ionic native control on an IOS device
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

My apps work just fine, so either I am not doing something you are doing or I am not understanding exactly what you are saying.

Thanks for using Ionic!

**Comment by oguzuncu** [comment]
[dha-app2 kopie.zip](https://github.com/ionic-team/ionic/files/1379991/dha-app2.kopie.zip)

**Comment by kensodemann** [comment]
It looks like there isn't a problem with the actual orientation of the controls, but of the orientation reported by the Cordova ScreenOrientation plugin. In cases like that, you should register the (potential) issue with the plugin itself as this is not an issue with the Ionic Framework.

However, I think I see the issue...

Here is what you have (after stripping some stuff that was bugging me by turning my flashlight on and vibrating my phone):

```ts
    this.screenOrientation.onChange().subscribe(() => {
      this.currentOrientation = this.screenOrientation.type;
    });
```

The problem here is that the orientation has indeed changed, but `this.screenOrientation.type` does not yet reflect that. Push it off into the next cycle and your code will work as you expect:

```ts
    this.screenOrientation.onChange().subscribe(() => {
      setTimeout(() => this.currentOrientation = this.screenOrientation.type);
    });
```
