### ISSUE TITLE
how to handle the initial flow when boot load a IonicPage 

### ISSUE THREAD

**Issue by jimliuxyz** [ionic-team/ionic#13151]
If app started from http://localhost:8100, we can hold the rootPage until the custom initialization done, to make sure the first view present stable.

But if started from http://localhost:8100/#/home, the system automatically nav to home IonicPage, how can I make it nav after custom initialization done?

**Comment by JasonAsmk** [comment]
I guess you are using the angular router since you mention urls. Consider taking the SPA approach and use the Ionic `Navcontroller` it will be easier. 
As for your issue, it might be that your plugins and DOM aren't ready in which case you have to make sure you are doing stuff after the `this.platform.ready()` promise. If you are already running your code after the platform ready promise, then if you want to use DOM elements somehow you have to make sure you wait after the DOM is loaded before using them. In that case your code should run in an ngAfterViewInit (angular hook) or even better ionViewDidEnter(ionic hook). Hope that covers it somehow.

**Comment by jimliuxyz** [comment]
thanks for sharing experience!

the platform.ready() is async, once the app ran into it, the first view of IonicPage shown already, it nav automatically with '.../#/home'. I have some custom initialization after ready(), but the loading of IonicPage will not waiting it done.

I found a way to do it, but this may not proper and need to implement in each IonicPage, I still expect a better solution.

```js
  ionViewCanEnter(): Promise<any>{
    return new Promise((res, rej) => {
      this.myservice.ready().then(_ => {
        res(true)
      });
    })
  }
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
