### ISSUE TITLE
ionic3 update problem

### ISSUE THREAD

**Issue by YuyangHYY** [ionic-team/ionic#13153]
I am using ionic3.6.0 version, I want to update to latest version, so is it necessary to update to 3.6.1 first then go update to 3.7.0?

**Comment by Gamerakki** [comment]
hi, 
no it not necessary. U can run this command npm install -g ionic@3.7.0. Since u want to update to latest version which is 3.13.0 u can just run the same command but without '@' attribute

**Comment by gregor-srdic** [comment]
ionic@3.7.1 is the latest though

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

General advice: no you do not need to go step by step through the versions. You should read the [changelog](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md) and do whatever is mentioned there. You should always do this for any library that you upgrade, not just the Ionic Framework. Since `3.6.0` to `3.7.1` will also involve an update to a few other libraries such as the Angular libraries, you should read the changelogs for them as well.

If the changes required are large, you may want to go step by step. That is up to you. In the case of `3.6.0` to `3.7.1` that is probably not a big deal.

Thanks for using Ionic!
