### ISSUE TITLE
Click is not working in innerHTML

### ISSUE THREAD

**Issue by nisos-siddharth** [ionic-team/ionic#13175]
I am developing the hybrid mobile app in ionic2. In that, I want to bind HTML content which is coming from a backend API.
Following is my code:
`htmlCode ='<p>Please visit your <a ion-text color=\"orange\" class=\"faqLink\" tappable (click)=\"openPage('EligibilityBenefits')\">ELIGIBILITY & BENEFITS SUMMARY</a> to find the summary of benefits information.</p>'`
`<div ion-text color="dgrey" class="answer" [innerHTML]="htmlCode"></div>`

In this, the click event is not working. Even when I used safe HTML then also it is not working.

```<div ion-text color="dgrey" class="answer" [innerHTML]="htmlCode | safe: 'html'"></div>```

What do I need to do so that the click works?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If this turns out to be an issue with the Ionic Framework, please open an issue here with the template fully filled out and with a sample application that duplicates your issue.

Thanks for using Ionic!
