### ISSUE TITLE
when calling an inner page its controller starts before app.components.ts ends

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#13180]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**

When I start the app by calling an inner page (url: root/inner-page)  its controller starts before app.components.ts ends, 
In the app component I do some basic things like fetching the configuration from the server by an api call, these infos are not available in the controller page at runtime and, of course, it generates an error.

**Expected behavior:**
app.components.ts should always starts  before other pages

Is this a well known behaviour or  it is  a bug?

```
cli packages: (/home/bogomips/mitify/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : browser 5.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.5.0
    npm  : 5.5.1 
    OS   : Linux 4.13

Misc:

    backend : legacy

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by bogomips** [comment]
I wrote a new app, but maybe it's too simple and I don't need to share it.
I am realizing that the behaviour is normal since the function returns a promise.

export class MyApp {
  rootPage:any = HomePage;
  constructor(platform: Platform,public apis:ApisProvider) {
    platform.ready().then(async () => {              
      await this.apis.call({method:'get',url:'photos'});
      //here I could save the photo in the storage      
      console.log('%c I got the phothos from the net now :( ', 'background: #444; color: #bada55');            
    });  
  }

so, when I start my app from an inner page its controller starts before my apis calls returns.
if the inner page's controller wants to use that data (I use it in order to get configs from server) it throws an error.

Is there a way to await untill app.components ends its operations before calling other pages or  my design is totally wrong?

Thanks

**Comment by kensodemann** [comment]
I am going to close this then as it is not really a bug in the Ionic Framework.

There are probably several ways to structure your code for this, but what I normally do is:

1. Create a service that fetches the configuration
2. The `get()` (or whatever you call it) returns either an Observable or a Promise (whichever you like)
3. If you would like the data cached, either the Observable is replayed or the Promise is kept and returned instead of fetching the data again.

For other ideas, I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
