### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Object.getOwnPropertyDescriptor(t,e)') in Safari at launch

### ISSUE THREAD

**Issue by didier-v** [ionic-team/ionic#13215]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Safari displays a runtime error when starting the app:
```
TypeError: undefined is not an object (evaluating 'Object.getOwnPropertyDescriptor(t,e)')
```
**Steps to reproduce:**
- start a project (ionic start newproject)
- choose a template:  I tested with 'blank' and 'tabs'
- serve it: (ionic serve)
- use Safari to open the app.

**Other information:**
**Ionic info:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node  : v6.11.4
    npm   : 3.10.10
    OS    : macOS Sierra
    Xcode : Xcode 9.0.1 Build version 9A1004

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have tried your steps to duplicate, but I do not get the issue. 

I have sometimes seen browser extensions cause issues like this where it _looks_ like something I am developing has an issue but it is actually a problem with the extension. If you are using any Safari extensions, please disable them all and try again. If that fixes the issue, then the issue is with one of your extensions. You can then try enabling them one by one until you find the errant one.

If disabling all extensions has no effect or if you aren't using any browser extensions, would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by didier-v** [comment]
The issue was caused by extensions. Thank you.
