### ISSUE TITLE
Livereload missing server commands

### ISSUE THREAD

**Issue by omargon** [ionic-team/ionic#13307]
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
We just upgraded our Ionic CLI from 1.7.16 to the latest 3.16.0 and we noticed that we are missing the usual ionic server command options when running `ionic cordova emulate {device} -l`

**Expected behavior:**

We use to run `ionic emulate {device} -l` and get the following server options:
```
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Ionic info:**
```
cli packages: (/Users/{user}/.nvm/versions/node/v6.11.4/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    Cordova Platforms : android 6.3.0 ios 4.5.2
    Ionic Framework   : ionic1 1.3.1

System:

    ios-deploy : 1.9.1
    ios-sim    : 6.1.2
    Node       : v6.11.4
    npm        : 3.10.10
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this is not about Ionic Framework but about the Ionic CLI, and since this is not an issue but a support question I am going to close this issue.

I suggest starting with the CHANGELOGs:
https://github.com/ionic-team/ionic-cli/blob/2.x/CHANGELOG.md
https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md

Those should document all of the relevant changes that have been made over the various versions from your starting point until current.

If you still have questions after that, I urge that you ask those questions on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
