### ISSUE TITLE
Stable versions for ionic, npm, node and cordova

### ISSUE THREAD

**Issue by macklus** [ionic-team/ionic#13304]
Hi:

is there any way were i can know the stable and full function version of ionic and its dependencies ? every time system updates, it breaks something

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X] feature request

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.0
    npm               : 5.5.1 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /opt/android

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

Feel free to keep responding though. Just closing this because we use this issues list as a list of items for developers to work on.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
> every time system updates, it breaks something

Can you clarify what you mean by this? What on the system is being updated?
