### ISSUE TITLE
After clicking browser refresh button wrong page is loaded.

### ISSUE THREAD

**Issue by vhb56** [ionic-team/ionic#13317]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
Developing a site with Ionic.
I have 2 pages, in every page were set  1 string + 5 variables in segment(@IonicPage) in order to set URL Path.
These variables are the same, except last 2.
So first 4 are the same, because same parent, last 2 variables are different.

It's difficult to explain, i've put an example below.

When i am navigating to one of those pages everything is ok.
But if i will refresh the page, i won't see it again, instead i will see another page.
Seems that it's because they have same number of variables set in segment??
Because if i add 1 dummy word, like '/something' - it won't happen.

So, 2 pages, 6 vars set in IonicPage segment(1 string + 5 vars). 
first 4 vars with same name, every var is very verbose. 

Something like this:

1st Page:

@IonicPage({
  segment: 'animals/:animalType/:animalSubtype/:animalSubSubType/:animalName/:animalSomething/'
})
vs

2nd Page:
@IonicPage({
  segment: 'animals/:animalType/:animalSubtype/:animalSubSubType/:animalAreal/:animalTalent/'
})

first word 'animals' is the string not var.
After navigating to 1st page if i will click browser refresh button i will load 2nd page instead.

if i do this with 2nd page or the 1st one:
@IonicPage({
  segment: 'animals/:animalType/:animalSubtype/:animalSubSubType/:animalAreal/:animalTalent/BLABLA'
})

it starts to work correctly. so its definitely something with vars number? or i don't understand something.

Everything is updated.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
   @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v6.11.0
    npm  : 5.5.1
    OS   : Windows 10

```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Here is what I believe your issue to be:

Here are your two paths:
`animals/:animalType/:animalSubtype/:animalSubSubType/:animalName/:animalSomething/`
`animals/:animalType/:animalSubtype/:animalSubSubType/:animalAreal/:animalTalent/`

So removing human-meaningful variable names basically you have:
path 1: `animals/:v1/:v2/:v3/:v4/:v5`
path 2: `animals/:v1/:v2/:v3/:v6/:v7`

So, if give a path like `animal/foo/bar/baz/pooh/eathoney` is 'pooh' a `v4` or a `v6`? Is 'eathoney' a `v5` or a `v7`? The navigations subsystem has no way of knowing. They are just strings. Technically, that URL matches both "path 1" and "path 2", so it gives you back whichever one it finds first and stops looking.

When you add 'BLABLA' to the end of the path, it works because now the paths have different signatures.

Suggestion: design your paths such that they are distinct outside of the variable sections.

IOW, if you strip all of the variables from your two paths above, you are left with `animals` and `animals`. Do something to make those distinct paths in whatever way makes sense for your app.

Thank you for using Ionic
