### ISSUE TITLE
Using components instead of controllers

### ISSUE THREAD

**Issue by MartinMuzatko** [ionic-team/ionic#13327]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[ ] bug report
[x] feature request

Hello!

I wonder why ionic prefers to use controllers instead of a component approach for various modules like `ActionSheet`, `Popover`, etc.
I would prefer to have my actionsheet with their actionsheet items in the template. Like so:

```html
<ion-actionsheet>
    <ion-actionsheet-item (handler)="openInfo" icon="cogs">Text</ion-actionsheet-item>
</ion-actionsheet>
```

I don't get, why popover, actionsheet etc have to be created so programatically, when you could configure them easily using templates and passing events using `input` and  `output` decorator and control using `viewchild`.

This looks like asking for a lot, but this would making components more customizable again. Ionic has a horrible culture of adding little snippets of CSS for all the things they can't achieve with component settings. Like placing the actionsheet icons somewhere else. This would be eliminated, by making components configurable and reactive again, without using controllers.

**Comment by manucorporat** [comment]
Ionic is designed to create apps, it is a end-to-end solution. It is not bootstrap, it handles many things under the hood. You are sub-estimating the complexity of it:

- You need to handle browser navigation (go back button) with popover, action sheet etc.
- All this components are not part of you page, but people expect to appear at a global context (on top a the sidemenu). Even if you switch between tabs, the actionsheet should keep visible.
- You need to coordinate how action sheet, alert, popover, sidemenu, everything plays together.

Your use case might be simple, but it is not the case sometimes.I am not saying your idea is bad, but it is not complete, your approach might fixes one use case and breaks the rest.

Fortunately, this will get better with Ionic V4 which is based in WebComponents, ie the DOM is the API. The controllers will stay, for sure, because they are needed to handle the complexity of it. But I think it is going to be easier than ever to 100% customise the markup.

**Comment by manucorporat** [comment]
and Alerts, Actionsheet, Popover are never defined in the "markup" of native iOS or Android apps, but they are created programmatically.

Again, I agree it should be easier to customize, Ionic V4 will fix that.
