### ISSUE TITLE
npm run ionic:serve reload not showing updates to .ts files

### ISSUE THREAD

**Issue by ashgibson** [ionic-team/ionic#13441]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Running npm run ionic:serve the app loads as expected but any changes to ts classes cannot be seen unless serve is stopped and started again. Any updates to html files are seen immediately without a restart.

I am not receiving any error messages in the console and the app will compile for ios successfully and I have deployed to real devices without issue.

**Expected behavior:**
Updates to ts files (services and component classes) should be seen without having to restart ionic:serve

**Other information:**
I am not sure where to start debugging this issue.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.9.1
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /usr/local/Caskroom/android-sdk/3859397

Misc:

    backend : legacy

**Comment by ashgibson** [comment]
This appears to be chrome only issue where chrome is completely ignoring the cache headers set by the dev server. This works without issue on Firefox. Is there any additional headers that can be set so that Chrome doesn't do any caching during development? I have already ticked 'do not cache' in chrome dev tools with no improvement.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by ashgibson** [comment]
Hi @kensodemann,

This is a bug with the framework/cli and the latest chrome browser.

**Comment by kensodemann** [comment]
The framework has nothing to do with this issue other than you happen to be using it. A framework bug would be something like a model not displaying properly or some other logical bug in the library itself.

The CLI or app tools _might_ have something to do with this but those are different repos:

- https://github.com/ionic-team/ionic-app-scripts
- https://github.com/ionic-team/ionic-cli

However, I just tested this using the following version of Chrome and it worked just fine, refreshing with changes to HTML files and TS files, and with the changes being reflected by the program:

```
Google Chrome is up to date
Version 62.0.3202.94 (Official Build) (64-bit)
```

Thus, I am going to say that it is more likely that this has something to do with your particular configuration rather than a bug in the CLI or app-scripts.

My Ionic Info:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.0
    npm  : 5.5.1 
    OS   : macOS High Sierra

Misc:

    backend : pro
```
