### ISSUE TITLE
Switching root navs with side menu bug?

### ISSUE THREAD

**Issue by BugsBunnyBR** [ionic-team/ionic#13496]
Hi, I think I found a bug, or I may be doing something wrong. Mind to take a look?
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

[X] bug report
[ ] feature request

**Current behavior:**
If the app has the following situation:

1) `app.html` has a `nav` and `app.ts` sets `rootPage` as one page with side menu (HomePage);
2) HomePage has a popover menu that changes the root nav to another page with side menu ( or even the same HomePage class);
3) After using the Popover menu the new page is shown, but the side menu or the `menuToggle` are not shown.

**Expected behavior:**
In the step 3) it should show the new root page with the side menu and `menuToggle`.

My app user may have two profiles, admin and user. Both of them with side menu and the use the popover to change the context.

A sample application via GitHub
https://github.com/BugsBunnyBR/ionic-nav-bug/tree/master

```
 ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : browser
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/juliocotta/Library/Android/sdk

Misc:

    backend : pro


```

**Comment by longgt** [comment]
1. Menu toggle button was not shown
Please check the menuContent attribute on ion-menu is assigned with a valid element. (Ex: ion-content of menu) 
2. Before using navigation controller to setRoot, disable menu on this page by MenuController.

**Comment by BugsBunnyBR** [comment]
@longgt What do you mean by that?
My sample shows the problem. I tested it in two different machines.
When I run the project, my side menu is shown, just when I switch the root using the popover it bugs the new side menu.

**Comment by longgt** [comment]
@BugsBunnyBR It's hard to know what's happened but you can try something like that.
Add lifecycle hook ionViewWillLeave to HomePage, disable menu by MenuController here.
Add lifecycle hook ionViewWillEnter to HomePage, re-enable menu by MenuController here.

I've viewed your code and it seems to be different with your description.
1. ListPage has a popover, not HomePage.
2. In HomePage, use nav.push to navigate to ListPage
3. In ListPage, after clicked any item, use nav.push to navigate to ListPage again with selected item
4. In ListPage, click button to show popover, return back to HomePage by getRootnav().setRoot

In my experience with menu, it's safe to disable menu before leaving and re-enable before entering. Doing something like that my team escaped from many bugs of menu when nav between page.

**Comment by BugsBunnyBR** [comment]
@longgt , ok. I will try that, but even if it solves my problem. 
Still, this does not seem to be the expected behavior to ionic, right?

**Comment by BugsBunnyBR** [comment]
@longgt , I tested your solution and it works. Thanks.

**Comment by longgt** [comment]
@BugsBunnyBR After spent a little time to investigate this problem, I think some logic of Ionic Menu is improperly.
When nav from one page (called page A) to another page (called page B), the currently logic is the following here:

1. Call MenuController._register to register menu of page B (add to end of array)
Menu of page A is still enabled.
Menu of page B is disabled.
2. Dipose page A, call MenuController._unregister to remove menu of page A from array.
Menu of page B is still disabled.
The problem is here, when trying to call MenuController._unregister to unregister an enabling menu, it should find and enable the menu of page which will be visible. (In this case, this is the menu of page B)

Another problem is MenuController._register will always add menu to last index of array. But logic to find menu of MenuController is trying to find menu from start to end. If two menu has some position (left/right) or same id, it will find and return menu on page which is below of navigation stack (NG).

I've tried to modify logic of MenuController as the  following (As I don't want to modify a lot of source code)

1. MenuController._register
Old: this._menus.push(menu); //Add to end
New: this._menus.unshift(menu); //Add to start

Reason: keep menu of the page which is on the top of navigation stack as start of array in MenuController.

2. MenuController._unregister
After removed menu from array, check the menu at start of internal array of MenuController, if it's disabled, try to enabled it. 

Reason: keep menu of the page which is on the top of navigation stack is enabled and visible.

I didn't tested another case but everything worked as expected with my project.
Hope this help.

**Comment by longgt** [comment]
@kensodemann Would you mind reviewing my solution and add this issue to plan of fix after released of v4?

**Comment by kensodemann** [comment]
@longgt - navigation is getting some pretty heavy modifications in v4, but we can mark this as something to circle back around to after v4 is released.

**Comment by tleguijt** [comment]
+1 I'm running into the same issue.
Seems like the new page (set by `setRoot`) is places outside the ion-nav element and will be on top of all other elements (including the menu you'll try to open afterwards)
