### ISSUE TITLE
Unused scss variable

### ISSUE THREAD

**Issue by paulussup** [ionic-team/ionic#13491]
https://github.com/ionic-team/ionic/blob/2273fb5d47eb64375f1608370d32b330cdc30bd9/src/components/modal/modal.md.scss#L7

**Comment by kensodemann** [comment]
Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please.

Be sure to include something in the expected behavior section. For example are you trying to do something that you cannot currently do and that is how you discovered this? It would be helpful to have some context here. Otherwise someone could easily just fix this by removing the unused variable.

Thanks for using Ionic!
