### ISSUE TITLE
ion-content fullscreen doesn't work if conditional

### ISSUE THREAD

**Issue by hmsoftware** [ionic-team/ionic#13517]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
as if fullscreen attribute was not set if it is done conditionally

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

either of these works fine:
```
<ion-content fullscreen></ion-content>
<ion-content fullscreen="true"></ion-content>
```
this following does not trigger the effects of fullscreen
```
<ion-content [attr.fullscreen]="true ? true : null"></ion-content>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
   @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3 ios 4.5.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.9.1
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I have a sample app where it is working. Code snippets:

**home.ts**
```ts
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  focus: boolean;
  full = false;
```

**home.html
```html
<ion-content padding [fullscreen]="full">
    <h2>SignUp</h2>
    
    <ion-list>
      <ion-item>
        <ion-label >Email</ion-label>
        <ion-input type="text" clearInput required></ion-input>
      </ion-item>
```

Changing `full = false;` to `full = true;` in the code causes the `fullscreen` behavior when the screen is rendered.

The one caveat here is that it will not respond to changes after the page is rendered. So, for example, if I have a checkbox on the screen and toggle it the behavior will not be affected because the page has already rendered.

What is your use case for doing this dynamically?

Thank you for using Ionic

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
