### ISSUE TITLE
Styling on Mac OS is not working

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/ionic#13512]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
css transform and box-shadow does not render correctly on Mac OS.
popover is not consistent

The errors make black screen effect in several occasion. 

**Expected behavior:**
It should work.

**Steps to reproduce:**
I have installed a vmware, and an iphone emulator with XCode.
Latest version of Mac OS (high sierra), latest version of ios.

The platform identified as "core" under linux and under mac os also.

Mac OS based Safari wasn't working, even if i made the styling "ios" at default.
Mac OS based IPhone emulator was working. (maybe some window open/close was stuck some  times, very likely because of lagging)

Mac OS based Chrome wasn't working with ios style, but working with md style.
Same label in the popover hasn't been rendered correctly. (rendered, but it was white)

Linux based Chrome was working in md and in ios case also. (with small changes, what i reported earlier - orientation change related bugs)

The following styles might help you to make it work. (It's far from perfect, but at least all the item is visible, and can be changed) - it was working under mac os based safari.

/**********************************
* ios background fix
*/
/*.popover-ios {
    opacity : 0.6 !important;
}

.popover-ios ion-backdrop {
    opacity : 1 !important;
}

.loading-ios {
    opacity : 0.5 !important;
}
*/

//strange
/*.toggle-ios .toggle-inner {
    box-shadow: none !important;
}

.toggle-ios .toggle-icon::before {
    background: none !important;
}*/

//can work
/*.picker-ios .picker-opt {
    background: lightgrey !important;
}

.bar-buttons-ios {
    transform: none !important;
}

.toolbar-background-ios {
    transform: none !important;
}

.swiper-pagination {
    background: #fff !important;
}

ion-slide {
    background: #fff !important;
}

ion-content .scroll-content {
    background: #fff !important;
}*/

I think the popover concept is wrong. (It should be a popup with the size of the window, not the size of the whole screen - in linux and in mac os it seems working in the opposite way)

If you need to make a modal window, just create a new layer, as mixing opacity with the popover is very-very painful.

If you haven't any mac, you can look at my repository under fms-design/config/mac,
and you can get the Mac running on PC.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Also with instructions on how to get the blank screen effect you are talking about.

As for the styling, I believe that the default styling for all browsers on all non-mobile platforms is MD, but it should use whatever you override to, so I will test that in Safari and let you know what happens. If I understood what you wrote, that was the only browser that had an issue and that it was working properly in Chrome.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
I had some time to go back and look at this as I said I would. You seem to have serval issues enumerated above, so I will address each item as best I can:

> The platform identified as "core" under linux and under mac os also.

That is correct. If you are running in a browser it should always identify as `core` as per the documentation: http://ionicframework.com/docs/api/platform/Platform/ (note that there are no specific mods for Linux or MacOS or Windows, only for mobile OSes, desktop devices identify as `core`)

> Mac OS based Safari wasn't working, even if i made the styling "ios" at default.

Not sure what you mean here. It should show using MD styles since it is `core`. On my system it does, no matter the browser or if I am using my Mac, my Linux machine, or my Windows machine. Always MD by default in the browser.

If I set the mode as such in my `app.module.ts`, then it shows using the iOS styles as expected:

```ts
    IonicModule.forRoot(MyApp, {
      swipeBackEnabled: true,
      preloadModules: false,
      mode: 'ios'
    })
```

If you are seeing something different, you will need to provide a sample application.

> Mac OS based Chrome wasn't working with ios style, but working with md style.

Chrome on my Mac worked for me both with the default (MD) and with the "ios" style override, so I will need a sample app duplicating this if the "ios" override is not working for you.

Perhaps a clarification of what is not working for you would be helpful.

> Same label in the popover hasn't been rendered correctly. (rendered, but it was white)

I have never seen this occur. Can you provide a sample?

> I think the popover concept is wrong. (It should be a popup with the size of the window, not the size of the whole screen - in linux and in mac os it seems working in the opposite way)

I have only seen small popovers. The only thing I have seen take up the whole screen is a modal on small screen such as a phone. I will need a sample here as well.

> If you need to make a modal window, just create a new layer, as mixing opacity with the popover is very-very painful.

Modals are also working just fine for me, so if you are having a specific issue with them a sample application and some more clarification may be needed.

We would be happy to help you with any of these issues, but just need some more information to go on in order to be effective in that.

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!

**Comment by raxim1** [comment]
The safari problem occurs on VmWare player, and figured out it's not happening on real device.

To be honest, i'm half way to rewrite ionic, because i had many other problems, like orientation change on popup, virtual scroll empty pages, when you scroll back, and many others which was totally unstable.

https://github.com/fssrepository/facs
