### ISSUE TITLE
Is not plugin or ionic  version did not follow up ios 11.1+?

### ISSUE THREAD

**Issue by dnoyeb** [ionic-team/ionic#13524]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

the statusBar of my app works not as my expectations in ios 11.1+,the header has extra 20px height and statusBar.overlaysWebView(true) doesn't work in ios 11.1+(iphone6s plus)  but  it all works well in ios 10.3.2.
**Expected behavior:** 

Is not plugin or ionic  version did not follow up ios 11.1+?

**Comment by Sampath-Lokuge** [comment]
Have you followed this: http://blog.ionicframework.com/ios-11-checklist/

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, the `ionic info` output is missing in your issue. Please include that information. So far as we know, iOS 11 support has been fully functional since `3.8.0` and had been receiving incremental improvements over several versions before that.

Thanks for using Ionic!

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!
