### ISSUE TITLE
ionic1 the modal show more times lead application 'fake dead'

### ISSUE THREAD

**Issue by wzhsh90** [ionic-team/ionic#13534]
code segment:

 var modalTemp = $ionicModal.fromTemplateUrl(path, obj).then(function (modal) {
                    modal.show();
                });
$timeout(function(){
modalTemp.show();
},1000)

when modal close ,the class 'mode-open' will still exists on body tag. this will lead application  'fake dead'.

I trace the code find the reason:

ionic.bundle.js line :55737    stack.add(self);
each time modal.show() invoke ,the modal will be add once . so when modal hide the condition '!modalStack.length will be false'
code:segment
 if (!modalStack.length) {
          $ionicBody.removeClass(self.viewType + '-open');
   }
suggest:

  add: function(modal) {
      modalStack.push(modal);
    }  instead of
  add: function(modal) {
    var index = modalStack.indexOf(modal);
      if (index==-1) {
       modalStack.push(modal);
      }
    }

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Since this is an Ionic v1 issue, please log the issue here: https://github.com/ionic-team/ionic-v1

This issue list is only for Ionic v2+

Also, please fully fill out the issue template when doing so. Including a sample application via GitHub is always a real plus.

Thank you for using Ionic
