### ISSUE TITLE
Angular Animations not working in Ionic View

### ISSUE THREAD

**Issue by wilippolis** [ionic-team/ionic#13538]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[T] **3.x**
[] **4.x**

**I'm submitting a ...**  (check one with "x")
[T] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I've successfully implemented Angular animations as components in my Ionic 3 and they work perfectly in when running locally with Ionic Serve but when I try to emulate the app with Ionic View they don't work. Just wondering if anyone has had this issue or if it that is supposed to happen.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. This appears to be a question about Ionic View, which is part of the Ionic Pro set of offerings.

For Ionic Pro issues, please use the [Ionic Pro Support Portal](http://support.ionicjs.com)

> Just wondering if anyone has had this issue or if it that is supposed to happen.

FWIW, I just tried one of my apps on Ionic View, paying attention to animations. All of the standard page transition animations work just fine. But... that is probably not really the same thing as your animations. You may need to supply a sample application when logging your issue.

Question: What happens if you load it on a device w/o using Ionic View? (IOW, use Xcode or `ionic cordova android run` depending on platform to load to your development device)?

Thanks for using Ionic!
