### ISSUE TITLE
Live reload resets app to original state on ionic serve, emulate, or run

### ISSUE THREAD

**Issue by fablrdigital** [ionic-team/ionic#13559]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When running ```ionic serve --cs``` or ```ionic cordova run android --livereload``` and a change is made the app is reset to the initial page.

**Expected behavior:**
Ionic v1 applies update without resetting the app. This should also happen on these versions, as this has a __huge__ impact on development time.

**Steps to reproduce:**
Just follow instructions under "current behavior"

**Ionic info:**

```
cli packages: (/Users/philipbennison/code/stroll/stroll-mobile/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v7.8.0
    npm        : 5.5.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

It depends on your navigation strategy. With Ionic v3 there are basically three:

- default - creates a nav stack manipulated via push/pop, but does not change the URL
- deep-linking - still have a nav stack with push and pop but URLs are generated based on the deep-link configuration
- lazy-load - similar to deep link, but each `@IonicPage()` is in its own module and (most importantly) gets its own bundle, so everything is not in a single bundle like with the other two strategies. Really this is a form of deep-link, so it has URLs as well.

So, with deep-linking and lazy-load, whatever URL you are on reloads and you thus stay on the same page.

With default, you are always at the "root" URL, so the app essentially starts at root with a reload.

Ionic v1 used the UI-State router making it most analogous to the current deep-linking strategy, so it would also just reload whatever the current URL was.

If you need to have the "stay on the same page" reloading, I suggest modifying your application to use either deep-linking or lazy-loading if possible.

I will close this issue for now. If you are using deep-linking or lazy loading and still having this issue, please provide a sample application via GitHub demonstrating the issue so we can use for debugging and testing. In that case, though, note that this will likely not be addressed until after v4 has shipped due to heaving modifications that are occurring in the nav area.

Hopefully that all made sense. Let me know if you have any questions.

Thank you for using Ionic

**Comment by fzamperin** [comment]
@kensodemann I'm using Ionic v3 in a while and my application always reload completely with livereload when I save some file (excluding scss files), even though I use the lazy-loading strategy with @IonicPage() using a module for each page and then importing this page module inside app.module.ts, is there anything extra to do?

**Comment by kensodemann** [comment]
@fzamperin - do you have a sample application you can share? Also, can you clarify exactly what you mean and what you are looking for? Your app should reload completely, but it should do so using whichever URL you are on, which means you should be on the page for that URL. Any specific info you could provide would be helpful.

**Comment by NicksonYap** [comment]
@kensodemann do you have an email where I can send you the code?
I'm having the same issue as @fzamperin 
It's making development almost impossible.
It happens the same when using `ionic serve`

It's using Angular 6 & Ionic 3

**Comment by kensodemann** [comment]
@NicksonYap - it would be best if you either provide your code on GitHub (or some other cloud based public repo site) or create a sample application that demonstrates the same behavior and share that via a GitHub repo.

**Comment by NicksonYap** [comment]
@kensodemann 
Here's the Starter I used, that has the issue
[ionic.zip](https://github.com/ionic-team/ionic/files/2318912/ionic.zip)

**Comment by kensodemann** [comment]
@NicksonYap - this is working the way I would expect things to work with an Ionic v3 app. Can you explain what behavior you are looking for?

**Comment by NicksonYap** [comment]
@kensodemann

Yes, that's the issue where it always resets to home.

Actually in app.component.ts, `rootPage` was set to HomePage

so if the whole app is hard reloaded, it would surely go to HomePage.

Everytime livereload is triggered, the webview flashes white for an instant, plus console logs will always print "Angular is running in the development mode. Call enableProdMode()..."

It shows that livereload refreshs the whole page, instead of reloading the page/component itself.


I was expecting the page/component to reload only when editing the component's script and html
Is this normal? 


Well at least when editing scss, the page stays there
