### ISSUE TITLE
https://github.com/don/cordova-filechooser/issues/40

### ISSUE THREAD

**Issue by shriswissfed** [ionic-team/ionic#13574]
And there is no proper plugin or work around documentation for FILE CHOOSER for IOS platform,so it has made lots of confusion as to why we chose hybrid.

**Comment by shriswissfed** [comment]
The file chooser for android thread is not active and still lots of issues are opened,aren't the ionic team supposed to manage and monitor all these?

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this is an Ionic Native question, I am going to close this issue and urge you to open an issue in the Ionic Native repo: https://github.com/ionic-team/ionic-native

Please fully fill out the template when doing so. Otherwise, the maintainers will have a difficult time trying to understand what you are trying to report, making it more difficult to resolve your issue.

A couple of things I noticed:

1. https://github.com/don/cordova-filechooser has not been maintained in quite some time, perhaps the project itself is dead? Hard to say as there is no notice posted that I saw.
1. Ionic Native is using a fork of that project which does appear to be getting some maintenance: https://github.com/ihadeed/cordova-filechooser. Perhaps you should log the issue linked in your subject there. It appears to be getting fixes

Thanks for using Ionic!
