### ISSUE TITLE
ion-input and conditional autofocus attribute not allowed

### ISSUE THREAD

**Issue by Emptyfruit** [ionic-team/ionic#13579]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request

**Current behavior:**

If i use `<ion-input [autofocus]="isNew" [(ngModel)]="item.name" ></ion-input>` i get the error message from angular: "Can't bind to autofocus since it isn't a know property of ion-input".

**Expected behavior:**

Since autofocus works with `<ion-input>` in general, i expect to be able to use it conditionally. 

**Steps to reproduce:**

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/Emptyfruit/dev/organizer/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.1.2 browser 4.1.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v7.9.0
    npm               : 4.2.0 
    OS                : OS X El Capitan
    Xcode             : Xcode 8.0 Build version 8A218a 
```

**Comment by mhartington** [comment]
So this is just a confusion between native attributes and Component properties. Using `[autofocus]` would mean that the component (ion-input) has an `@Input` called `autofocus`, which ion-input does not. 

The reason `<ion-input autofocus` works though is because it's a built in attr of HTML. So if you would want to make that conditional, you'd use `<ion-input [attr.autofocus]="shouldFocus"`


https://stackblitz.com/edit/ionic-nnbde8?file=pages/home/home.html
