### ISSUE TITLE
Using image file picker causes page header and footer to be repositioned

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic#13600]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using `<input type="file" accept="image/*"/>` on iOS11 (emulator or real device) the native file/image browser UI is shown when the element is clicked. Upon picking an image, any page headers and footers (nav bar/toolbar) are repositioned so the header is beneath the status bar and the footer is partially off screen. 

**Expected behavior:**
Existing screen components remain positioned normally.

**Steps to reproduce:**
1. Add `<input type="file" accept="image/*"/>` to a page (a modal in this case)
2. Click the input button
3. Select a source and an image from that source
4. The ionic UI is screwed up

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 5.0.0 ios 4.5.4 windows 5.0.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /Users/josh/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? 

Could not duplicate. Copied your supplied code into an app and tested on: iPhone 7 running iOS 11 as well as a couple of emulators also running iOS11.

Tried with both a sidemenu and a tabs based project.

Looking at your `ionic info`, the only issue I see is that your `app-scripts` version is quite old. According to the ionic-angular change log, the app-scripts version should have been updated to `3.0.0` when taking `ionic-angular` to `3.7.0` so it should probably at least be at that version (actually at least `3.0.1` looking at the app-scripts change log since `3.0.0` had a CSS bug. Might be worth reviewing the versions of things to make sure they all match properly.

Thanks for using Ionic!

**Comment by snortblt** [comment]
Never mind. Operator error. I missed the requirement for `<meta name="viewport" content="viewport-fit=cover ...>` in the process of upgrading to WkWebView

**Comment by kensodemann** [comment]
OK. Glad to hear you figure it out.

**Comment by snortblt** [comment]
Incidentally, after having upgraded many times and missed things here and there over the past several months, it would be great to have an upgrade wizard that would at least attempt to do some of these things at some point. A few other dev environments have a similar feature.
