### ISSUE TITLE
ion-col column delimiters are not working with badge

### ISSUE THREAD

**Issue by atlantim** [ionic-team/ionic#13666]
![colhata](https://user-images.githubusercontent.com/19273777/34069821-fea3c774-e269-11e7-98f4-3f3754f7f35f.JPG)
Hi friends,

**I get the error on the link given in the link below. why is that?**

[https://resmim.net/f/iZUpza.jpg](url)

`<ion-list>
      <ion-item *ngFor="let _orderDetail of orderDetailArray">
        <ion-row>
          <ion-col col-sm-7>
            {{ _orderDetail.product.name }} &nbsp;Adet :{{ _orderDetail.quantity }}
            <ion-col *ngIf="_orderDetail.properties.length>0">
              <ion-badge *ngFor="let _property of _orderDetail.properties"
                         color="secondary"> {{ _property.name }}</ion-badge>
            </ion-col>
            <ion-badge *ngIf="_orderDetail.type" color="primary">{{ _orderDetail.type.name }}</ion-badge>
          </ion-col>
          <ion-col col-sm-3>
            <button ion-button icon-only round outline color="danger"
                    (click)="_orderDetail.quantity>1 ? _orderDetail.quantity=_orderDetail.quantity-1 : _orderDetail.quantity">
              <ion-icon name="md-remove-circle"></ion-icon>
            </button>
            <button ion-button icon-only round outline color="info"
                    (click)="_orderDetail.quantity=_orderDetail.quantity+1">
              <ion-icon name="md-add-circle"></ion-icon>
            </button>
          </ion-col>
          <ion-col col-sm-2 text-right style="font-size: 20px; font-weight: bolder;">
            ₺{{ _orderDetail.product.salePrice * _orderDetail.quantity }}
          </ion-col>
        </ion-row>
      </ion-item>
    </ion-list>`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you believe this is due to an error in our standard CSS or some other part of the Ionic Framework, please open an issue with the template fully filled out and with a sample application shared via GitHub that can be used to duplicate the issue you are having.

Thanks for using Ionic!
