### ISSUE TITLE
Sass Error @import ionicicons !!!!

### ISSUE THREAD

**Issue by MELAS007** [ionic-team/ionic#13715]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
 sass: ...ASR/mobile apps/CLUBS/HSC/mobile5/node_modules/ionic-angular/fonts/ionicons.scss, line: 9
            File to import not found or unreadable: ionicons-icons. Parent style sheet: D:/EDUMASR/mobile
            apps/CLUBS/HSC/mobile5/node_modules/ionic-angular/fonts/ionicons.scss

       L9:  @import "ionicons-icons";
      L10:  @import "ionicons-variables";

Error: Failed to render sass to css
    at BuildError.Error (native)
    at new BuildError (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at Object.callback (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\sass.js:210:24)
    at options.error (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\node-sass\lib\index.js:294:32)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Please include the following information:

- the output from `ionic info`
- a github repo with a sample project that can be used to duplicate the issue
- steps to duplicate perhaps (for example, did you use a specific starter? did it happen right out of the box or did you change something and then got this issue?

I have several projects going for various purposes and none of them are exhibiting this issue, so I am going to need more information in order to attempt to duplicate this.

One item I see is that you are using Windows and have a space in your working directory. I have seen this combination cause issues with some of the tools before. You could try cloning your app in a path where there are no spaces and see if that alleviates your issue (just a stab in the dark at this point, but something to try).

Thank you for using Ionic

**Comment by kensodemann** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. If you are still having the issue, please be sure to include the information requested above.

Thanks for using Ionic!
