### ISSUE TITLE
Tabs get unresponsive after this.nav.push(TabsPage) from  .handleNotificationOpened()

### ISSUE THREAD

**Issue by informatikTirol** [ionic-team/ionic#13726]
**Ionic version:**  (check one with "x")
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

**Current behavior:**

After receiving a push notification I want to push a TabsPage. 
![2017-12-29_07-59-11](https://user-images.githubusercontent.com/16346085/34431294-3557d720-ec6e-11e7-8783-a27d08836ead.jpg)

```
this._notification.handleNotificationOpened().subscribe(data => {
            this.nav.push(TabsPage);
   });

```

The tabs get unresponsive and laggy. .When i click the second tab, the page will be entered, but the icon of the tab will not be updated... 

**Expected behavior:**
The same
```
 this.nav.push(TabsPage);

```
from click from a button does behave correct. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.1.2 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.9.5
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by informatikTirol** [comment]
Hello, here is a zip: https://www.dropbox.com/s/8wzj1v5frc9vcpj/IonicBug13726.zip?dl=0
And here is a video: https://www.dropbox.com/s/7peqvvt0zi0rfek/IonicBug_13726.m4v?dl=0
Thanks for looking into it!

**Comment by kensodemann** [comment]
I tried running your code, but did not see any lag. Also, I do not see in your sample app where you are doing a `this.nav.push()` call, which is what you say is resulting in the lag.

Finally, I had to remove the `styleUrl` in `news-thread.component.ts` just to get the sample to run without a 404, so I am not sure you gave me a good sample of your issue there, but I cannot duplicate the issue using it.

**Comment by informatikTirol** [comment]
the `this.nav.push(TabsPage) `is in app.component.ts, function : this._notification.handleNotificationOpened()

> this._notification.handleNotificationOpened().subscribe(data => {
> 
>           //Tabs get unresponsive after this.nav.push(TabsPage) from .handleNotificationOpened() #13726
>           this.nav.push(TabsPage);
>         });
The function is issued from onesignal push notification service...

There is no  `news-thread.component.ts`
im my App, see Image 
https://www.dropbox.com/s/tbqpz81is66b62z/FileStructureExampleApp.jpg?dl=0
or ZIP
https://www.dropbox.com/s/8wzj1v5frc9vcpj/IonicBug13726.zip?dl=0

Thx!

**Comment by kensodemann** [comment]
I am not sure exactly what you are trying to do, but every time the subscribed event fires, you push another TabsPage onto the nav stack, which results in another whole instance of basically your whole app in the DOM.

To see this easily, add some code for the Test button as such:

```ts
  testPage() {
    this.nav.push(TabsPage);
  }
```

Then press it about 10 times and then go inspect the DOM and you will set 11 sets of ion-tabs (to original one that was set as the rootPage, and then 10 more, one for each button press.

That is not good, and I highly doubt that is what you are _actually_ attempting to do, but it is what you _are_ doing.

Since this is not an Ionic Framework issue but rather an issue with what you are doing in your code, I am going to close this.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).
