### ISSUE TITLE
ion-input accepting single dot but does not reflect in [(ngModel)] variable.

### ISSUE THREAD

**Issue by rahul-mutyalkar** [ionic-team/ionic#13727]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
this is my input field.
<ion-input type="number" placeholder="Enter your mobile no." [(ngModel)]="mobileNumber" (keyup)="checkNumber()"></ion-input>
/*my mobile validation code */ 
checkNumber() {
    this.loginStatus = false;
    console.log("this.mobileNumber : ", this.mobileNumber);
    var regexp = /^\d{10}$/;
    var mobile: any = this.mobileNumber.toString();
    if (regexp.test(mobile) == true) {
      this.loginStatus = true;
    }
  }
this is what i entered in mobile number field "9673412006."
in checkNumber i get mobile number as "9673412006" without '.'.

please help me

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is consistent with the way a regular non-Ionic input work. For example, if you `ionic start test-inputs blank`, and then change `home.html` as such:

```html
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-list>
    <ion-item>
      <ion-input type="number" [(ngModel)]="number1"></ion-input>
    </ion-item>
    <ion-item>
      <input type="number" [(ngModel)]="number2"/>
    </ion-item>
    <ion-item>
      <div>{{number1}}</div>
      <div>{{number2}}</div>
    </ion-item>
  </ion-list>
</ion-content>
```

Then type `41.` in the `ion-input` and `42.` in the standard `input`, you will see "41" and "42" (both without the entered '.') in the output.

The one inconsistency is that if you enter `41.0` in the `ion-input` it will display as "41.0" whereas if you enter `42.0` in the standard `input` it will still display as "42". That is because the value in an `ion-input` always comes back as text and not as a number. This inconsistency will likely be fixed in the next major release of Ionic.

Thank you for using Ionic
