### ISSUE TITLE
Centralize pages segments declaration with Lazy Loading feature

### ISSUE THREAD

**Issue by Sneko** [ionic-team/ionic#13734]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request

**Current behavior:**

Hi!

I adopted lazy loading but I don’t want to specify segments in each page file through @IonicPage() decorator over component. I would prefer to centralize them in a single file like in app.module.ts as before with:

```
{
	links: [ { component: 'HomePage', name: 'Home', segment: 'home' } ]
}
```

But by doing that I have this error: “Uncaught (in promise): Error: No component factory found for HomePage. Did you add it to @NgModule.entryComponents?”

Do you know if it’s possible? May I did something wrong?

Thanks

**Expected behavior:**

I would like it works :)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? 

You may just have to specify the segment in each page at this time, but I would like to see what you are trying within the context of the code before I say for sure.

Thanks for using Ionic!

**Comment by Sneko** [comment]
@kensodemann Hi :)

Please find here a sample from super starter : 
https://github.com/Sneko/ionic-lazy-loading

For your information and to be the more precise, I do not want to manage my segments separately, I mean why my segments declaration should be splitted? It depends on "application dressing" like when we use a single style.css for global guidelines of design.

I understand that each component are in their own file but routing should be centralized somewhere. That's why I tried to declare them with old Ionic way through:

`    IonicModule.forRoot(MyApp, {}, {
      links: [
        { component: 'TutorialPage', name: 'Tutorial', segment: 'second-custom-tutorial-segment' }
      ]
    }),`

But it's not working since I'm trying to use my pages with Lazy Loading. The error "**Error: No component factory found for TutorialPage. Did you add it to @NgModule.entryComponents?**" has sense because I don't import TutorialPage in app modules.

So my question is, how I can use lazy loading while declaring segments in a single place?

Thank you for your help :)

I hope my english is comprehensible :$

**Comment by kensodemann** [comment]
@Sneko - I see what you are trying to do, but I do not believe that is going to work with Ionic v3.

The next major release of Ionic and Ionic for Angular will include quite a few changes to how navigation works. Most notably, it will use the Angular router, which means that a lot of this will change at that time and you will be able to set up the routing the same way you would on a regular Angular project without Ionic (the same will be true once we support React, Vue, etc, just with the other framework's routers).

I am going to close this since we do not plan on having another v3 release at this time.

If this is still an issue after the next major release, please open a feature request issue at that time.

Thank-you again!
