### ISSUE TITLE
Ionic real or simulator breakpoint debugging

### ISSUE THREAD

**Issue by duckls** [ionic-team/ionic#13751]
Ios front-end development, looking for a lot of information but could not find true machine or simulator breakpoint debugging methods or tools, inquire of the official, real machine or simulator debugging cordova application tutorial or tools。
thank you

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

I always use this: https://ionicframework.com/docs/developer-resources/developer-tips/#debugging-ios-safari

I am not sure what you mean by "true machine or simulator breakpoint debugging" since you are really debugging a web app, so the browser tools generally work the best and allow for breakpointing, etc., but hopefully that helps.

Thanks for using Ionic!
