### ISSUE TITLE
Copy of divisions getting created, when opentok subscribe or publisher connected

### ISSUE THREAD

**Issue by rsgone** [ionic-team/ionic#13757]
Hi,

The ionic app version is 2.
Reference app link: https://github.com/opentok/opentok-ionic-samples/tree/master/Basic-Video-Chat

I am trying to use above example in one of my apps. When I tried to execute this example I am getting 2 layers for each division, out of those 2 layers of the same DIV, the bottom layer is in our control. which is a blank black box. And on top layer video is streaming, which we can not control(resize, scroll, apply CSS etc..)

And when I try to scroll HTML page or apply any CSS, JS operations to the div which I created. It is affecting to bottom layer DIVs. 

![image002](https://user-images.githubusercontent.com/12427522/34534775-7be06bc8-f0e5-11e7-8a70-27ac3764fd66.png)

![skype_picture 2](https://user-images.githubusercontent.com/12427522/34534986-69319cc6-f0e6-11e7-92d5-65502364c6a9.jpeg)

After some googling, I realized that, OT.updateViews() or TB.updateViews() function will solve this issue, but no luck. :(

Here is my code:

    startCall() {
    this.session = OT.initSession(this.apiKey, this.sessionId);
    this.session.on({
      streamCreated: (event) => {
        var pubOptions = { publishAudio: true, publishVideo: true };
        this.session.subscribe(event.stream, 'subscriber', pubOptions);
        OT.updateViews();
      },
      streamDestroyed: (event) => {
        console.log(`Stream ${event.stream.name} ended because ${event.reason}`);
        OT.updateViews();
      }
    });

    this.session.connect(this.token, () => {
      this.publisher = OT.initPublisher('publisher');
      this.session.publish(this.publisher);
      OT.updateViews();
    });
  }

Thanks for the help in advance.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This could also be an issue with the plugin you are using.

If this does turn out to be an issue with the Ionic Framework, please open a new issue with the issue template fully filled out including a GitHub repo for a sample application that can be used to demonstrate and debug the issue. (**note** due to timing, you may want to wait an retest after the next major release of Ionic before putting in that sort of effort since it is unlikely that there will be another v3 release)

Thanks for using Ionic!
