### ISSUE TITLE
Feature Request - React VR, WebGL

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic#13865]
Hello Ionic Team,

Here are few more things you can do when you use React.js & Redux as front end.

**React VR:** 

https://facebook.github.io/react-vr/

**WebGL on React:** 

https://react.rocks/tag/WebGL

zhxnlai.github.io/react-webgl-globe-basic-example/

http://vision-explorer.reactive.ai/#/galaxy?_k=9jv3sd

**React vs Angular 2 speed:**
https://auth0.com/blog/more-benchmarks-virtual-dom-vs-angular-12-vs-mithril-js-vs-the-rest/

**Comment by jamesharvey2** [comment]
and here's another interesting article: 

https://medium.com/reverdev/why-we-moved-from-angular-2-to-vue-js-and-why-we-didnt-choose-react-ef807d9f4163

I feel the same way. TypeScript slows down production process. 
JavaScript is better... and all cordova plugins, javascript libraries were built before typescript comes out. They didn't have typescript in mind. 
I don't know why Ionic is using typescript. 

Typescript is more concise, less redundant than javascript but having to look for typings and converting existing codes into typescript is a lot of work and I don't find this process to be really helpful. 

React or Vue seems to offer better solutions with much faster speed than Angular 5, ideally React brings more tools to the table than vue.

**Comment by kensodemann** [comment]
Here is our roadmap for the near future: https://blog.ionicframework.com/ionic-2017-18-roadmap/

Basically, the next version of Ionic will consist initially of these parts:

- @ionic/core - most of Ionic
- @ionic/angular - the bits requires to play nice with Angular

There will likely be an `@ionic/react` etc as we determine special code is required in order to properly interface with a specific framework. AAMOF, if you look in the `core` branch (which will eventually become `master` when we do the release) you will see the start of that package is already there, so it is being planned. Whether or not it will be complete for the initial release is something that only time will tell, but it is there.

As far as a programming language is concerned, you should be able to use whatever you want so long as the framework you are using (Angular, React, Vue, jQuery-UI, etc) plays nicely with it.

I am going to close this issue as it is something that would be better discussed after the initial release is complete.
