### ISSUE TITLE
jellybean or kitkat devices have white screen issue on startup app(reference device Samsung  GT-I9060 for testing)

### ISSUE THREAD

**Issue by manojbhardwaj** [ionic-team/ionic#13866]
I am using the fresh ionic blank project and it's provide me white screen after splash screen and nothing happens after that
when i try to check logs  ionic cordova run android -lc
Getting this error
The connection to server was unsuccessful (http://192.168.0.8:8100)

I try with ionic cordova run android --prod all kind of slug but not effect  and i am using blank new project
variables.scss
$colors: (
  primary:    #488aff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222
);
config.xml

   preference name="FadeSplashScreenDuration" value="300"
    preference name="SplashShowOnlyFirstTime" value="false" 
    preference name="SplashScreen" value="screen" 
    preference name="SplashScreenDelay" value="3000"
 
***** I don't want to use crosswalk into my app***** so please don't suggest me for that

 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
 global packages:
    cordova (Cordova CLI) : 7.0.1
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 25.2.5
    Node              : v6.11.0
    npm               : 3.10.10
    OS                : Windows 8.1
Environment Variables:
    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk
Misc:
    backend : legacy

**Comment by Artfloriani** [comment]
Could you try to inspect with Chrome to see what is going on?

Run without the `--prod` flag:

`ionic cordova run android`

On Google Chrome open the Inspect Devices tool:

`chrome://inspect`

Click to inspect your device and check the console log for errors.

**Comment by manojbhardwaj** [comment]
just showing splash screen and nothing happen even not showing index.html on chrome://inspect time just showing device name

**Comment by ghenry22** [comment]
the problem is that it's trying to connect to the live reload server on http://192.168.0.8:8100, as in the error message.  This server is run on the PC/Mac where you issue the run command.  It may well be a firewall or something on your machine blocking the connection.

on your computer after running try opening that address in a web browser, does it display anything?  you should see your app.  If it works try it on the web browser on your mobile device and see if it loads.  if it doesn't make sure your phone is connected to the same wifi network as your computer and that there is no firewall on your computer that would be blocking connections.  For instance windows firewall would block this by default.

**Comment by manojbhardwaj** [comment]
Real issue is https://github.com/ionic-team/ionic/issues/11935

**Comment by jamesharvey2** [comment]
Yes, this happens on one of my kitkat devices too. 

The solution is waiting for release of capacitor. Capacitor will come with a new splash screen.
Cordova splash screen is full of bugs... and it's outdated. 
As soon as capacitor splash screen comes out, I would consider cordova as a deprecated project.
