### ISSUE TITLE
UserAgent plugin_not_installed

### ISSUE THREAD

**Issue by smxdevst** [ionic-team/ionic#13870]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

```
[17:33:56]  console.warn: Native: tried calling UserAgent.set, but the UserAgent plugin is not installed. 
[17:33:56]  console.warn: Install the UserAgent plugin: 'ionic cordova plugin add cordova-plugin-useragent' 
[17:33:56]  console.error: plugin_not_installed 
```

Installed `ionic cordova plugin add cordova-plugin-useragent`. I am running userAgent.set after platform ready, tried to reinstall everything and install it back. Any suggestions?

package.json
`"im.ltdev.cordova.UserAgent": "https://github.com/LouisT/cordova-useragent"`

config.xml
`<plugin name="im.ltdev.cordova.UserAgent" spec="https://github.com/LouisT/cordova-useragent" />`

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

This could also be an issue with the plugin or with Ionic Native: https://github.com/ionic-team/ionic-native

Thanks for using Ionic!

**Comment by codewise-nicolas** [comment]
I dont know how long I spent on this problem, but i finally figured it out.
The pluginRef in the ionic-native is set wrong.

The cordova plugin has the "clobbers target" set to "UserAgent", however the ionic-native plugin's node_modules/@ionic-native/user-agent/index.js has the pluginRef set to "plugins.useragent". They should match.

Not sure where the difference/discrepancy happened but it did, and the fix is to change the node_modules/@ionic-native/user-agent/index.js of the ionic-native user-agent plugin's pluginRef to "UserAgent". (dont forget to remove, re-add the ios/android platform for the change to get picked up)
Alternatively change the plugin's clobbers target to plugins.useragent, i found the former easier.

I dont have the time/knowledge to submit a patch to Ionic's repo, but thats the fix you can do locally.
