### ISSUE TITLE
Opens application switcher dialog instead of running app on android

### ISSUE THREAD

**Issue by Maxim-Mazurok** [ionic-team/ionic#13922]
**Ionic version:**
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**
[ x ] bug report
[ ] feature request

**Current behavior:**
When I run `ionic cordova run android --device`, it runs the app, but also application switcher dialog opens. You can view it using `adb shell input keyevent KEYCODE_APP_SWITCH` command on terminal.

**Expected behavior:**
Just run the app, do not open application switcher dialog

**Steps to reproduce:**
Just run `ionic cordova run android --device`. It repeats on any app for me.

**Other information:**
I'm using Xiaomi Redmi 4 phone with android 6.0.1 (MMB29M), stable MIUI 9.2.3.0 (MBEMIEK), not rooted.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/path/to/app/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0 
    OS   : Linux 3.10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by FdezRomero** [comment]
Hi @Maxim-Mazurok! I believe this command is run by Cordova rather than Ionic itself. Do you have the same problem when just running `cordova run android --device` after building with Ionic?

I have a Nexus 5 with the same version of Android and it does open the task switcher first, then the app is launched. I'd say this is the normal behavior when running any Cordova app on Android.

**Comment by Maxim-Mazurok** [comment]
Hi @FdezRomero, I'll try to check it later this week once again, thanks for advice.
