### ISSUE TITLE
Error: Uncaught (in promise): removeView was not found on pressing browser back button in ionic 3 PWA

### ISSUE THREAD

**Issue by viveksinha9** [ionic-team/ionic#13953]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
In my Ionic 3 PWA, everything is fine apart from an issue. If I navigated to some page from root page through other pages, then press browser back button, I receive

Ionic - Error: Uncaught (in promise): removeView was not found

issue & it directly jumps to root page. If I press navbar back everything is good i.e. navigating pages back one by one. Similar issue reported but those are not related to browser back button. Though I tried all those (e.g. loadingController dismiss, alertCtrl dismiss etc.), but no luck. I am using tabs at root page and lazy loading with IonicPage decorator.

**Expected behavior:**
Pages should be navigated back one by one without any issue on browser back button press.

Ionic Info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by cnothegger** [comment]
Hello,
any news on this? 
I have the same error like @viveksinha9.

I have a tab bar with 5 tabs (First tab: index=0 is Home)
My route to this problem: 
1. Start on Home or any other page
2. Go to Category Page (There is a list of product categories shown) and click on a category
3. ProductListPage getspushed on the category page 
`this.navCtrl.push('ProductListPage', {category: category})`
4. On ProductListPage products with the selected category are shown --> click on a Product
5. ProductDetailPage gets pushed 
` this.navCtrl.push('ProductDetailPage', {
      product: product
    });`
6. Clicking Back Button of Browser --> ProductListPage is shown correctly 
7. Again clicking Back Button of Browser --> Error instead of Category Page
> Error: Uncaught (in promise): removeView was not found
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at Tab.NavControllerBase._fireError (nav-controller-base.js:223)
    at Tab.NavControllerBase._failed (nav-controller-base.js:216)
    at nav-controller-base.js:263
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3

It works like expected when I use the Back Button in the NavBar

I also investigated that the url changes from http://localhost:8100/#/page-tabs/search/product-detail to http://localhost:8100/#/page-tabs/**search**/product-list when I use the Back Button of the NavBar and when I use the Browser Back Button it changes from http://localhost:8100/#/page-tabs/search/product-detail to http://localhost:8100/#/page-tabs/**home**/product-list

Thanks in advance
