### ISSUE TITLE
white screen on click ionic 3 prod mode application

### ISSUE THREAD

**Issue by manojbhardwaj** [ionic-team/ionic#13952]
Hello ionic when i try with ionic cordova run android --prod it's showing first page but after that when i click on any button it's gona white and nothing showing and on ionic cordova run android it's work perfect how can i resolve this issue and no issue on chrome://inspect

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Here are a couple of things you can try:

- make sure you are using the latest version of `@ionic/app-scripts`
- connect via Chrome while it is running with `--prod` and see if you get any messages in the console
- try duplicating with a minimal Ionic application to see if you can isolate the trigger to this

If you can do that last bit, and it turns out to be an Ionic bug, please create a new issue with the issue template fully filled out, including a link to the GitHub repo containing your sample application.

Thanks for using Ionic!

**Comment by manojbhardwaj** [comment]
Thank you but i resolve it because by mistake i added incorrect provider
