### ISSUE TITLE
Color variable seemingly not passed to generated button element

### ISSUE THREAD

**Issue by nesbocaj** [ionic-team/ionic#14065]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The generated button element does not display the passed `primary-text-md-light` color but instead looks to prefer the regular `primary` color when inspecting the generated css:

``` css
.button-clear-md {
    border-color: transparent;
    color: var(--ion-color-md-primary,var(--ion-color-primary,#488aff));
    background-color: transparent;
    box-shadow: none;
    opacity: 1;
}
```
Additionally, neither of the components in `@ionic/core` seems to respond to using color literals, eg. `#fff`, `#ffffff`, `rgb(255, 255, 255)` or `rgba(255, 255, 255, 1)`, as arguments for the `color` property, is this a bug or by design?

**Expected behavior:**

The button element should display the passed `primary-text-md-light` color.

**Steps to reproduce:**

**Related code:**

``` scss
$colors: (
  primary:               #488aff,
  secondary:             #32db64,
  danger:                #f53d3d,
  light:                 #f4f4f4,
  dark:                  #222,
  primary-text-md-light: rgba(#000000, 0.871)
);
```

``` html
<ion-button color="primary-text-md-light" fill="clear">Button text</ion-button>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Jacob\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.5.0
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\ProgramData\Android\android-sdk

Misc:

    backend : pro
```

**Comment by davec21** [comment]
I am not sure if you are trying to use just a css file or SCSS but in SCSS I do:

```
.button-clear-md {
    border-color: transparent;
    color: color($colors, 'primary-text-md-light');
    background-color: transparent;
    box-shadow: none;
    opacity: 1;
}
```

Additionally, as far as I know when it comes to the color property on buttons you need to use variable colors not actual colors.

**Comment by nesbocaj** [comment]
I see, that doesn't really help me though as I need to set the color via TypeScript.

**Comment by davec21** [comment]
Not quite sure what you mean, you could bind the color to a variable and set the variable value to the name of your scss variable ie: primary?

**Comment by aphex** [comment]
Hey maybe I can help out here. Apologies for the lack of documentation on this, I am hoping to get to putting together something more visible soon, but for now here are the main points.

With ionic 4 there was a move to pure CSS for theming. Ionic itself, internally, is using sass but when compiled out it is all pure CSS. 

Out of the box you will have the following color options available.

```
primary
secondary
tertiary
success
warning
danger
light
medium
dark
```

Those are translated to css variables in the following form
```
--ion-color-primary
--ion-color-secondary
--ion-color-tertiary
...
```

So setting `--ion-color-primary` anywhere in your application would cascade down and apply to any element under it. For example using `:root` would apply to everything

```
:root {
  --ion-primary-color: #ff0000;
}
```
or you could target a specific button by class if needed
```
.my-fancy-button {
  --ion-primary-color: #ff0000;
}
```

This can also be done at runtime using `setProperty`
```
const el = document.querySelector('.my-fancy-button');
el.style.setProperty('--ion-primary-color', '#ff0000');
```

It is also important to remember that an ionic color is not just one value. It is actually 5, and it is important to set all of these colors as they are always considered to be in sync. A color should be made up of **base**, **contrast**, **shade**, **tint** and **rgb**. They are broken down as follows

```
--ion-color-[name]-[variation]
```
*base is always the variable name without a variation*

For example primary would look like the following
```
*base*: --ion-color-primary
*contrast*: --ion-color-primary-contrast
*shade*: --ion-color-primary-shade
*tint*: --ion-color-primary-tint
*rgb*: --ion-color-primary-rgb
```

in CSS they would look like this
```
--ion-color-primary: #488aff;
--ion-color-primary-rgb: 72,138,255;
--ion-color-primary-contrast: #ffffff;
--ion-color-primary-shade: #3f79e0;
--ion-color-primary-tint: #5a96ff;
```
I know this might seem a bit confusing, and sadly it all comes down to CSS not supporting any color modification methods (mixing colors, tint, shading, etc) but its really not to bad, here is a general rule on how to create these.

* base: The main color you would like to use.
* contrast: A color then when applied over **base** would result in readable text
* shade: A slightly darker version of **base**. Ionic defaults to **base** mixed with 12% black
* tint: A slightly lighter version of **base**. Ionic currently defaults to **base** mixed with 10% white
* rgb: The RGB list version of **base**. This is used to allow variable alpha colors

Looking back at your code example I am seeing that you are attempting to add a new color to the color map. This is not possible in CSS but would be possible in SCSS. In order to do this you would need to rebuild ionic from source with your new color map variable. 

Again ionic uses SCSS but it only compiles out CSS, so if you want your custom color to be applied in all the right styles you would need to do this compilation step. Hopefully you are able to use one of the colors provided in css (maybe secondary or tertiary?) otherwise you are always welcome to tinker with the SCSS in the source itself and pump out some custom CSS for your specific application.

In the Ionic 4 source you no longer need to provide everything to the color map. You are able to simply take over a single color or just add one of your own. For example to add a custom **quaternary** color it could look like this

```
$colors:              (
  quaternary: (
    base: #ff0000,
    contrast: #ffffff,
    base: #ae0000,
    base: #ff3633,
    rgb: unquote("255,0,0")
  )
)
```
I hope this helps, if you have any other questions I will do my best.

**Comment by brandyscarney** [comment]
Thanks for the issue! I am going to close this as the original issue should be resolved by switching to css variables. Please see my comment here for how to add a new color: https://github.com/ionic-team/ionic/issues/14624#issuecomment-402795342

If you are still seeing an issue with the latest beta please create a new issue. Thanks!
