### ISSUE TITLE
No doc or demo to describe how to upgrade to v4

### ISSUE THREAD

**Issue by alanhg** [ionic-team/ionic#14287]
ionic v4 is alpha.No doc or demo to describe how to upgrade to v4.

please

**Comment by brandyscarney** [comment]
We are keeping it mostly private right now because we know there are going to be issues found. Here is the doc though, since you asked: https://docs.google.com/document/d/1hQzp0Z2gRHN5aoMCv-RCqSEe2DmSNUPoTxbt-bQEwb0/edit?usp=sharing

It is still a work in progress, and we are actively updating the documentation and API. We'll have an official blog out soon when we feel more comfortable with it. 🙂

**Comment by alanhg** [comment]
@brandyscarney thanks!
