### ISSUE TITLE
ion-fab no longer handles horizontal and vertical props as expected

### ISSUE THREAD

**Issue by kgroat** [ionic-team/ionic#14307]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
The `ion-fab` remains inline, even when the `horizontal` and `vertical` props are provided.

**Expected behavior:**
The `ion-fab` should be rendered towards the bottom right of the page (or containing positioned element)

**Steps to reproduce:**
Add the following to HTML:
```html
<ion-fab horizontal='right' vertical='bottom'>
  <ion-fab-button>
    <ion-icon name='options' />
  </ion-fab-button>
</ion-fab>
```

**Related code:**
Working in previous version (0.1.4-9):
https://codepen.io/kgroat/pen/GxeLwW

Fails in 4.0.0-alpha.1:
https://codepen.io/kgroat/pen/pLYBQO

**Additional Information:**
It looks like the `fab-horizontal-right` and `fab-vertical-bottom` are no longer being applied as expected.  Also fails for other `horizontal` and `vertical` values.

**Comment by manucorporat** [comment]
@kgroat that's for the report! this is already fixed in alpha.2!
https://codepen.io/anon/pen/eMwzeJ

We have been removing "left", "right" from everywhere in the framework. Now it's called "start", "end" this is because of our support for right-to-left languages.

Start/end is the right thing to do regarding UI.

Left -> start
Right -> end

Thanks!
