### ISSUE TITLE
i'm use ion-button，The content is converted to the upper case

### ISSUE THREAD

**Issue by mengxiaof** [ionic-team/ionic#14340]
ionic2
I don't want to turn into a upper case
![image](https://user-images.githubusercontent.com/19354837/38860265-6327a2a8-4262-11e8-9328-5a9590c095a5.png)
```
<button ion-button>asdfJ</button>
```

**Comment by synga** [comment]
We need more context to know how to help you. Is this button beeing displayed in an android env? Because if it is it's the default behaviour for the ionic button. You can see that in Android it adds the class `.button-md` whose have the css property `text-transform: uppercase`. You can override this behaviour in two ways:

1 - Change the `$button-md-text-transform` SASS variable adding it to your `variables.scss` file with the value you want.

2 - Override it in your global css file (`app.scss`) using the `.button-md` class selector or adding it for every platform using `.button`.

The styling of your app is all up to you.
