### ISSUE TITLE
ion-badge inside ng-container rendered incorrectly

### ISSUE THREAD

**Issue by all43** [ionic-team/ionic#14634]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.10
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v10.0.0
    npm  : 6.1.0 
    OS   : macOS High Sierra

Misc:

    backend : legacy
```

**Describe the Bug**
*ion-badge* incorrectly positioned if placed inside *ng-container*

**Steps to Reproduce**

Here is some code to reproduce. Both items have no difference, except *ng-container* as container for a badge. First item acts as expected (placed on item-end), second - acts like it have no position attribute. Probably old bug, because I was able to reproduce on plunker with a bit outdated template:
https://plnkr.co/edit/9XRrhxr5ybdnnMfSkEZg?p=preview

```
  <ion-list>
    <ion-item>
      <ion-badge item-end>1</ion-badge>
      Some text
    </ion-item>
    <ion-item>
      <ng-container>
        <ion-badge item-end>2</ion-badge>
      </ng-container>
      Some text
    </ion-item>
  </ion-list>
```

**Additional Context**
Tested only in Safari and Google Chrome, but probably works in any context

**Comment by brandyscarney** [comment]
Thanks for the issue! `item-end` is an attribute used by item for content projection. More info can be found on that here: https://ionicframework.com/docs/api/components/item/Item/#item-placement

In order for content projection to work properly, the element with `item-end` must be a direct child of `ion-item`. You can work around this by changing your code to the following:

```
<ion-item>
  <ng-container item-end>
    <ion-badge item-end>2</ion-badge>
  </ng-container>
  Some text
</ion-item>
```

This is something that we have changed completely as part of Ionic 4, as we have run into issues with content projection for awhile (see my comment here: https://github.com/ionic-team/ionic/issues/12252#issuecomment-317062521). Since this is something that is fixed in latest, I am going to be closing this issue. Thank you!
