### ISSUE TITLE
v3: Modal lost response when modal was over an alert and it only happened on device

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic#14703]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

In my app, there were an alert and a modal, depends on http response, the alert and the modal displayed in random sequence. Only when modal displayed over the alert and only on the device, the modal lost response, user clicked the modal content and no response. If on Chrome simulator, everything was ok

**Expected behavior:**

No matter modal over alert or alert over modal, the user interaction should properly work

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:

    ios-deploy : 1.9.2
    ios-sim    : 6.0.0
    Node       : v8.4.0
    npm        : 6.1.0
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

```

**Comment by derek90** [comment]
I'm dealing with the same problem.
An alert blocks the UI until the alert is dismissed, and it can't be dismissed by the user because there's a modal over it. Check if you have the alert reference when you are about to open the modal, and if the reference has an alert instance, close the alert.
Another option is to create an alert service which creates and presents the alerts, and using it from any place where you want to show an alert. This service will have a method to dismiss the alert, which you could call from any component across the app
