### ISSUE TITLE
[Ionic v4] Missing margin-top attributes to h1, h2, etc. if included in a padded element

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#14863]
**Ionic Info**
@ionic/angular: "4.0.0-alpha.12"

**Describe the Bug**
In Ionic v3, when included in a padded element, h1, h2, etc. (if first-child) received a smaller margin-top value

In Ionic v4 this is missing

**Related Code**

    <div padding>
        <h1>something</h1>
     </div>

**Expected Behavior**
Ionic v3:

    [padding] h1:first-child,
    [padding] h2:first-child,
    [padding] h3:first-child,
    [padding] h4:first-child,
    [padding] h5:first-child,
    [padding] h6:first-child {
       margin-top: -.3rem;
    }

**Comment by brandyscarney** [comment]
Thank you for the issue. We have decided that we will not be adding this CSS back in Ionic 4. We feel that it may cause more issues than it solves. In a non-shadow DOM component it would work, but we would end up with some headings that have it and some that don't since it is global CSS. If there are any specific Ionic components where you think this looks bad or broken with this missing, please create a new issue. I am going to close this one though, thanks!

**Comment by peterpeterparker** [comment]
No worries, it's all good for me. Thx for your time
