### ISSUE TITLE
[ionic v4] ionic serve think the plataform is Android 

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#14953]
Ionic Info
Run ionic info from a terminal/cmd prompt and paste the output below.

Ionic:

ionic (Ionic CLI) : 4.0.1 (C:\Users\Computer\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.0.0-beta.0
@angular-devkit/core : 0.7.0-rc.3
@angular-devkit/schematics : 0.7.0-rc.3
@angular/cli : 6.0.8
@ionic/ng-toolkit : 1.0.0
@ionic/schematics-angular : 1.0.1

Cordova:

cordova (Cordova CLI) : 8.0.0
Cordova Platforms : none

System:

NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
npm : 6.3.0-next.0
OS : Windows 10

Environment:

ANDROID_HOME : not set

insert the output from ionic info here

ionic serve think the plataform is Android when is with browser on windows computer, without any emulator

**Comment by brandyscarney** [comment]
There aren't many details here, but I am assuming you're expecting windows mode instead of material design on a windows computer? We have removed the windows mode from v4. There are only two modes currently: `ios` and `md` (see the preview on the right): https://beta.ionicframework.com/docs/components#action-sheet

Material design (`md`) is the default for all browsers on desktop. More info on that in the theming docs: https://beta.ionicframework.com/docs/theming/platform-styles#ionic-modes

We've discussed adding in [Windows fluent design](https://www.microsoft.com/design/fluent/) but no development has started on it. 

I'm going to close this as working as designed. Thanks!

**Comment by goelectricstations** [comment]
@brandyscarney 

import { Platform } from '@ionic/angular';
  constructor(
                public plt: Platform
              ) {

    console.log(this.plt.is('android'));
  }

this give me: this.plt.is('android')) --> true
when I use browser should be "core"?
