### ISSUE TITLE
Accessibility issues in components 

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#14976]
Back-button does not provide any context that it is a button/back-button
Menu button does not provide any context 
Searchbar clear button does not provide context
Searchbar cancel button does not provide context
IonIcon does not provide context

**Comment by Nigh7Sh4de** [comment]
I'd like to add another one that was mentioned in a previous ticket but was never resolved:
Scrolling to past last visible item in scroll view will cause focus to leave the scroll view (instead of scrolling down to reveal more items in the scroll vew)

https://github.com/ionic-team/ionic/issues/5970
