### ISSUE TITLE
CSS Not loading properly using the CDN

### ISSUE THREAD

**Issue by gpiccon** [ionic-team/ionic#15047]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Calling the "node_modules/@ionic/core/dist/ionic.js" in index.html loads all the CSS well, but loading from https://unpkg.com/@ionic/core@latest/dist/ionic.js makes look to not show correctly.

**Expected behavior:**
Both methods should make the same style to appear
<img width="387" alt="captura de pantalla 2018-08-05 a las 10 42 48" src="https://user-images.githubusercontent.com/3017280/43684221-5a3c4424-989c-11e8-9bb8-6067412a0dcb.png">
<img width="379" alt="captura de pantalla 2018-08-05 a las 10 42 41" src="https://user-images.githubusercontent.com/3017280/43684222-5a5822d4-989c-11e8-8296-2e5143dfbff8.png">

**Steps to reproduce:**
Not necessary

**Related code:**

-->

```
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Do you possibly have an older version in your `node_modules`? In the latest versions it is required to import specific css files (or the one minified ionic css file) in order to get the font & color styles. There's an overview of this in the breaking changes document here: 

https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#global-css
https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#including-the-css-files

This is already setup in our starters here: https://github.com/ionic-team/starters/blob/master/angular/base/src/global.scss

Please let me know if this doesn't resolve your issue, thank you!
