### ISSUE TITLE
@Ionic/core 4 blank page with cordova

### ISSUE THREAD

**Issue by Deadowln** [ionic-team/ionic#15125]
This is working for me on cordova (android platform)

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8">
        <title>Ionic App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
    </head>
    <body>
        <ion-app>
            <ion-header>
                <ion-navbar>
                    <ion-title>Ionic</ion-title>
                </ion-navbar>
            </ion-header>

            <ion-content padding>
                <p>Just like normal!</p>
            </ion-content>
        </ion-app>

        <script src=https://unpkg.com/@ionic/core@0.0.2-20/dist/ionic.js"></script>
    </body>
</html>
```

But when I try to use the latest version all I get is a blank page 
<script src=https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>

**Comment by brandyscarney** [comment]
Thanks for the issue! There are a few things going on here.

1. Version `0.0.2-20` is very old. We have removed the `ion-navbar` component completely, see the breaking changes (for angular) here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#navbar

2. The global CSS has been moved out to a separate file. More info on why can be found here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#global-css as well as [steps for including this css](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#including-the-css-files). (Replace all uses of `@ionic/angular` with `@ionic/core` if you are not using Angular.

I moved your code into a codepen and updated it to use an `ion-toolbar` and include the css: https://codepen.io/brandyscarney/pen/oMmvmJ?editors=1000

### Resources

- Beta documentation: https://beta.ionicframework.com/docs/
- Stencil conference app: https://github.com/ionic-team/ionic-stencil-conference-app
- Angular conference app: https://github.com/ionic-team/ionic-conference-app/tree/core-update

I'm going to close this since this should get you up and running, but if you run into more problems please use our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/) for assistance! Thanks! 🙂
