### ISSUE TITLE
[Ionic v4] Uncaught Error: cordova already defined

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#15143]
**Ionic Info**
@ionic/angular: "4.0.0-beta.2"

**Describe the Bug**
When I run my app on a real Android device (Samsung Edge / Android v7)  and plug the device with a cable to my laptop, I found the following error in the Chrome Debugger console

    Uncaught Error: cordova already defined
        at cordova.24be14f7eb59f2cab434.js:1
        at require (cordova.24be14f7eb59f2cab434.js:1)
        at cordova.24be14f7eb59f2cab434.js:1
        at cordova.24be14f7eb59f2cab434.js:1

**Related Code**
I double checked, I only have got the following in the `<head/>` of `index.html` once

     <script src="cordova.js"></script>

**Expected Behavior**
No such error

**PS**

Not sure if it's Ionic related or Ionic-native v5 related, therefore I opened the issue here, hope you don't mind too much

**Comment by NisStrom** [comment]
Same issue here. If `cordova.js` is not included in `indext.html`, then in runs fine witch `ionic run`. When we build the app and create a package for both android and ios  the app throws an error, that `cordova.js` should be included because a native cordova plugin (in our case cordova-plugin-advanced-http) requires it to work. 
Now when `cordova.js` is included in  `indext.html` it works with the packaged builds but fails with `ionic run` as described by @peterpeterparker

**Comment by peterpeterparker** [comment]
As described in https://github.com/ionic-team/ionic-native/issues/2067#issuecomment-425117241 I had to remove `cordova.js` from my `index.html` because I think that now `cordova.js` will be added automatically at bundle time (with `vendor.js`)

Doing I then see the following warning in the console, not sure if I should ignore it or not:

     Could not find cordova.js script tag. Plugin loading may fail.

**Comment by peterpeterparker** [comment]
I've tested successfully my app on both (real) iOS and Android. Therefore I close this issue.

`cordova.hash.js` is added by the Ionic CLI in v4 and therefore no extra reference to `cordova.js` in `index.html` should be added manually
