### ISSUE TITLE
IONIC V4 : Cannot find module Issue..

### ISSUE THREAD

**Issue by jackryu** [ionic-team/ionic#15180]
Hello,
I am working on ionic v4 project and i am facing one issue, my all imports modules showing "Cannot find module Issue". but my application is working.

> Note : I have read lot of online post related to this issue but its not resolved in any post.
> Refrancs : https://github.com/Microsoft/vscode/issues/33209

**ERROR**

![screen shot 2018-08-15 at 16 17 00](https://user-images.githubusercontent.com/6933841/44138494-b8d133ac-a0a6-11e8-94e5-4bd8176ffe32.png)

**TSCONFIG**

![screen shot 2018-08-15 at 16 14 50](https://user-images.githubusercontent.com/6933841/44138428-7fe04236-a0a6-11e8-9a4e-0751452492f2.png)

**IONIC INFO**

![screen shot 2018-08-15 at 16 18 14](https://user-images.githubusercontent.com/6933841/44138570-e9bccda0-a0a6-11e8-9c41-371a6a83ef6a.png)

**Project Structure**

![screen shot 2018-08-15 at 16 26 11](https://user-images.githubusercontent.com/6933841/44138907-077bd8c6-a0a8-11e8-82bb-3e65b3ac4c51.png)

**Comment by kensodemann** [comment]
Looking at the other issues, it may have to do either with a plugin you are using or with the contents of your `tsconfig.json`. Here is a copy of mine.

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

I would like to try yours in one of my projects just to see if I get the same results, but you posted a picture of yours instead of the actual contents. Can you please post the actual contents in a comment so I can copy it and try it?

Also, I am going to close this as it is totally off-topic for this issues list.
