### ISSUE TITLE
ion-item 'lines' attribute does nothing (docs incorrect?)

### ISSUE THREAD

**Issue by a11smiles** [ionic-team/ionic#15185]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Please see forum conversation [here](https://forum.ionicframework.com/t/ion-item-attributes-in-beta-4/138485).

Your documentation is incorrect.  The documentation states that the `lines` attribute must be placed on the `ion-item` component.  However, that didn't work.  Instead, the `lines` attribute needs to be placed on the `ion-list` component.

**Expected behavior:**

Hide lines when `lines` attribute is supplied on the `ion-item` component.

**Steps to reproduce:**

**Related code:**
Forum link.

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The `lines` attribute works on both the `ion-list` component (to affect all items) or a single `ion-item` component. Our documentation for that is here:

- https://beta.ionicframework.com/docs/api/list/#properties
- https://beta.ionicframework.com/docs/api/item/#properties

## Examples (all in iOS):

### Default list, without lines property:

```
<ion-list>
  <ion-list-header>Default lines</ion-list-header>
  <ion-item>Pokémon Yellow</ion-item>
  <ion-item>Super Metroid</ion-item>
  <ion-item>Mega Man X</ion-item>
  <ion-item>The Legend of Zelda</ion-item>
  <ion-item>Pac-Man</ion-item>
</ion-list>
```

<img width="377" alt="screen shot 2018-08-15 at 11 38 20 am" src="https://user-images.githubusercontent.com/6577830/44157156-bd2e0280-a07f-11e8-978e-94c9467538d8.png">


### Default list, item with `lines="none"`:

```
<ion-list>
  <ion-list-header>Item lines: none</ion-list-header>
  <ion-item lines="none">Pokémon Yellow</ion-item>
  <ion-item lines="none">Super Metroid</ion-item>
  <ion-item lines="none">Mega Man X</ion-item>
  <ion-item lines="none">The Legend of Zelda</ion-item>
  <ion-item lines="none">Pac-Man</ion-item>
</ion-list>
```

<img width="375" alt="screen shot 2018-08-15 at 11 36 20 am" src="https://user-images.githubusercontent.com/6577830/44157097-98d22600-a07f-11e8-9e02-0ec0efe191e3.png">

### List with `lines="full"`:

```
<ion-list lines="full">
  <ion-list-header>Lines: full</ion-list-header>
  <ion-item>Pokémon Yellow</ion-item>
  <ion-item>Super Metroid</ion-item>
  <ion-item>Mega Man X</ion-item>
  <ion-item>The Legend of Zelda</ion-item>
  <ion-item>Pac-Man</ion-item>
</ion-list>
```

<img width="378" alt="screen shot 2018-08-15 at 11 34 38 am" src="https://user-images.githubusercontent.com/6577830/44156960-3b3dd980-a07f-11e8-88b1-0782b403cc4f.png">

If you could point to where our documentation is incorrect that would be helpful. 🙂 

With that said, it seems that the issue here is actually with the following rule being applied because of the `ion-menu-toggle` element wrapping the item:

```
.list-ios:not(.list-inset):not(.list-ios-lines-none) .item:last-child {
    --inner-border-width: 0;
    --border-width: 0 0 0.55px 0;
}
```

**Comment by a11smiles** [comment]
@brandyscarney I'm not necessarily saying the documentation isn't correct.  As a matter of fact, the _lab environment_ rendered correctly in Safari with the `lines="none"` on the `ion-item` element.  However, the **Ion DevApp** still rendered the lines.

The _only_ way for the **Ion DevApp** to hide the lines was me applying the`lines` attribute to the `ion-list`.

To refresh...

This **did not** work:
```html
    <ion-list>
      <ion-menu-toggle *ngFor="let page of appPages">
        <ion-item lines="none" detail-none [routerLink]="page.url" [routerDirection]="'root'">
          <ion-icon slot="start" [name]="page.icon" color="primary"></ion-icon>
          <ion-label>{{page.title}}</ion-label>
        </ion-item>
      </ion-menu-toggle>
    </ion-list>
```

This **did*** work:
```html
<ion-app>
  <ion-split-pane>
    <ion-menu type="overlay">
      <ion-header>
        <ion-toolbar>
          <ion-title>
            Menu
          </ion-title>
        </ion-toolbar>
      </ion-header>
      
      <ion-content padding>
        <ion-list lines="none">
          <ion-menu-toggle *ngFor="let page of appPages">
            <ion-item detail="false" [routerLink]="page.url" [routerDirection]="'root'">
              <ion-icon slot="start" [name]="page.icon" color="primary"></ion-icon>
              <ion-label>{{page.title}}</ion-label>
            </ion-item>
          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet main></ion-router-outlet>
  </ion-split-pane>
</ion-app>
```

Perhaps, it's a bug in the **Ion DevApp**? Or, as you suggested, a CSS issue?

Thanks.

**Comment by brandyscarney** [comment]
It's a bug because of the `ion-menu-toggle` wrapper. Because our CSS is targeting the `item:last-child` to apply a border on it, and it is wrapped in another element, it is always considered the `last-child` of that element so it is getting the border even with `lines="none"` applied to the item. This is something we need to fix. 

> With that said, it seems that the issue here is actually with the following rule being applied because of the ion-menu-toggle element wrapping the item:
> 
> ```
> .list-ios:not(.list-inset):not(.list-ios-lines-none) .item:last-child {
>     --inner-border-width: 0;
>     --border-width: 0 0 0.55px 0;
> }
> ```

**Comment by RHinderiks** [comment]
Any news on this issue in beta.12 is still have a final border on the last ion-item even with lines="none"
