### ISSUE TITLE
Popover is always shown down

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic#15237]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
  ionic (Ionic CLI)          : 4.0.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.1
   @angular-devkit/schematics : 0.7.1
   @angular/cli               : 6.1.1
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5
```

Hello, see the image below
![print](https://user-images.githubusercontent.com/28517010/44321665-ae4ca480-a41f-11e8-9270-b59f44182c56.png)
clicking on the button Popover is displayed from the button down, but in this
scenario (without space down) it should be displayed up.

**Expected Behavior**
Since the user's current view is what matters, the Popover should be displayed upwards when the button is on the bottom half of the screen.

**Comment by bleuscyther** [comment]
I was about to post the same. I see the issue in the demo too. Weird thing is that if i am on live-reload and i edit a code when reloading it is at the correct position,

popover-arrow is a the correct position but popover-content is created on top instead of on the bottom

Also PopoverOptions is missing some props like : mode...
