### ISSUE TITLE
[ionic3] ion-searchbar dont trigger ionCancel

### ISSUE THREAD

**Issue by EnricoVogt** [ionic-team/ionic#15255]
# Bug Report

**Ionic Info**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v10.4.1
    npm  : 6.1.0 
    OS   : Linux 4.4

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Describe the Bug**
the output-event "ionCancel" is not trigged if the user use the cancel button in the ion-searchbar-component

**Steps to Reproduce**
https://stackblitz.com/edit/ionic-kapa6b

**Expected Behavior**
If the user clicks the cancel button the event should be triggered

**Comment by brandyscarney** [comment]
The cancel button isn't enabled on your searchbar. You need to add `showCancelButton="true"` in order to enable it and trigger the `ionCancel` event. Updating your test to include this shows them working: https://stackblitz.com/edit/ionic-u4befa?file=pages/home/home.html

Note that on `md` mode the back arrow is the cancel button. 

If you're trying to capture the event when the input is cleared, you should use the `ionClear` event. Thanks!
