### ISSUE TITLE
VirtualScroll should keep references to detached components, rather than rebuild them during scroll

### ISSUE THREAD

**Issue by GordoRank** [ionic-team/ionic#15272]
# Feature Request

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.0 (C:\Users\****\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set



```

***Feature Request***

VirtualScroll currently destroys any child components that get detached from the DOM as it scrolls.  For simple use cases this isn't an issue, but when you have relatively complex components, with reasonably expensive initialization paths, this can become unbearably slow.   For my particular use case, the virtual scroller slows to a crawl on a modest 3 year old laptop with some frames.

As an example of virtual scrolling complex components, think of something along the lines of numerous graphs rendered with canvas.  Every time one of the components comes into view it's canvas will be setup all over again, probably causing layout thrashing, then it will be re-rendered all over again.

If you are developing an application for the financial services industry that contains hundreds of charts, you can see how this becomes a problem.

In pure JS virtual scrollers that I have written myself in the past, the item would only ever be initialized and rendered once, and when it becomes detached from the DOM, a reference to it would be held in memory so that it could simply be reattached again when it comes back in to view, without the performance cost of re-initializing and re-rendering the component all over again.

**Comment by kael** [comment]
Ok, I see your point, and that's why I'm not using data binding for large lists, because yes, elements get destroyed and re-created each time.

But actually, I'm not using Ionic/Angular (anymore), only Stencil with Ionic/Core. Perhaps you could write a custom component for VirtualScroll (with an `update` function instead of using a "data-bound" list) with Stencil and integrate it into your app.

Because looks like there'a much more finer (granular) way to handle data update of elements being "virtually scrolled". That's the example of code I wrote above, it allows to decide what to do with the element, which part of it you want to modify.

See this [example for Ionic/Core](https://github.com/ionic-team/ionic/blob/d40d0a706fa6b6087c1c9a96638d8751ab716407/core/src/components/virtual-scroll/test/basic.html#L60) where only the `textContent` of the "virtual element" is updated (hence no reflow), or that [other example](https://github.com/ionic-team/ionic/blob/master/core/src/components/virtual-scroll/test/cards.html#L54-L60) which although applied for the call of `renderHeader` can also be applied in the `renderItem` function where the "virtual element" id reused.

Interestingly, I've been testing Virtual Scroll scalability with IEX using that [charts list](https://api.iextrading.com/1.0/ref-data/symbols) and connecting to the IEX SocketIO (WebSocket in disguise) endpoint for real-time updates, and it scales quiet well, though. I tested with [Chart.js](https://www.chartjs.org/), but yes Canvas is difficult to redraw fast, perhaps there's a smart way to update them (I'm no graphics expert).

Also, as a side note, to increase performance of the app, I'm using a Web Worker to handle connectivity and data management, that way the main thread is mainly, theoretically, dedicated to rendering, and having a second thread changes really the perception of the flow when scrolling fast.
