### ISSUE TITLE
[Ionic 4] - Ionic slides, not able to use options and unexpected results

### ISSUE THREAD

**Issue by elinfinitoindia** [ionic-team/ionic#15327]
# Support Question
When I change the device from chrome debugging tool, the options start working, also pager is true and that is only visible when i change the device. Also, the autoplay is not working either. 

https://www.useloom.com/share/df97417509e845ba93be73271ca77bd5

**Comment by kensodemann** [comment]
This could be a bug in the framework or it could be an issue with the code. The thing is, we can't really tell without a reproduction app. If you believe this is due to a bug in the framework, please create a new issue fully filling out the "Bug Report" template, including a GitHub repo with an app that duplicates the issue.

If you believe this is an issue in your code, then please visit one of the support forums mentioned in the "Support Question" template: ```Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.co```
