### ISSUE TITLE
[4.0.0-beta.5] ion-spinner hidden

### ISSUE THREAD

**Issue by Anthony2539** [ionic-team/ionic#15362]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.1.0
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 7 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.1
   NodeJS     : v10.6.0 (/usr/local/bin/node)
   npm        : 6.4.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F200

```

**Describe the Bug**
Since update 4.0.0-beta.5 my ion-spinner are hidden.

**Expected Behavior**
Same behavior like 4.0.0-beta.3

**Comment by Anthony2539** [comment]
You can see it on my repo: https://github.com/Anthony2539/waygng-ionic-v4

On my home page, i use a custom component « my-header-loader » that should display a spinner

**Comment by brandyscarney** [comment]
The `ios` spinner was renamed to `lines`: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#spinner

It looks like we removed the deprecation warning in a recent beta, so that is why it stopped working: https://github.com/ionic-team/ionic/commit/ae9c6f2adbe67925a4920c604afccf29120a485a#diff-d28a06b0f379d83d7a6c434dc6afdcbfL59

Please update the spinner's code to:

```
<ion-spinner margin-end class="header-spinner" name="lines"></ion-spinner>
```

Thanks!
