### ISSUE TITLE
let select component use picker as an interface

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#15390]
# Feature Request

**Describe the Feature Request**
Currently picker is used by datetime component only but I think it is very suitable for a select interface. 

**Describe Preferred Solution**
Selecting picker as an interface for select component like alert, popover and action sheet.

**Comment by comfortme** [comment]
Hi 
Any plans for this feature?

**Comment by kerosin** [comment]
Would be great to be able to use the DateTime picker without the nesting DateTime component.

This probably requires some refactoring, because the datetime value needs to be stored on the picker instead on the component itself. But might be worth separating picker and input-component logic.

Currently the only workaround is to create <ion-datetime> element that is hidden on the DOM and fire the *open()* method.

**Comment by brandyscarney** [comment]
Thank you for the issue! I'm going to close this in favor of https://github.com/ionic-team/ionic/issues/20317. I know this one is older but the more recent one has more upvotes and we use upvotes for sorting feature request priorities. Thanks!
