### ISSUE TITLE
[4.0.0-beta.7] Relative routing does not work after returning to same page

### ISSUE THREAD

**Issue by doender** [ionic-team/ionic#15449]
When I use relative routing to go from page A to page B like so:
```
openPageB(id) {
   this.router.navigate(['b', id], { relativeTo: this.route });
}
```

and then go back to page A (via the browser back button or an `ion-back-button`), calling `openPageB` again does nothing. When I use absolute routes everything works normally.
  
I've created a repository to demonstrate the issue here: https://github.com/doender/routingError

**Comment by giacomocerquone** [comment]
@mhartington this has been moved to forum and another issue as you asked. Do you have some new info about this?

**Comment by biesbjerg** [comment]
Seeing this as well, using both Angular's `Router` directly as well as using `NavigationController`. @giacomocerquone Can you provide a link to the post in the forums?

**Comment by mhartington** [comment]
Relative routing is not something that is going to be supported. I added a note in our new navigation docs. 

https://beta.ionicframework.com/docs/navigation/angular#navigating-to-different-routes

**Comment by giacomocerquone** [comment]
@biesbjerg yes that is the post (see below for a good solution)

@mhartington really sad. I suppose this decision has been taken since it isn't a problem easy to tackle since the bug has been tracked down in angular.

There is this other issue I opened to collect all the others and tivomaker gave a wonderful solution https://github.com/ionic-team/ionic/issues/15959 have a look
If not supported, at least let's add in a recipe section, or wherever you want, that code.
And some support should be given to the users in order to give them a solution because as it is, it's really problematic... it's more a bug than a missing feature
