### ISSUE TITLE
[Vue] v-model not working on <ion-input> tag

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#15532]
Hi,

I'm using the latest Ionic beta with Vue.js and I have noticed that if I use:
```
<ion-input v-model="msg" />
```

This is not working at all... the `v-model` attribute is not set on ion-input and its input element.

What do you advise me to work around that?

Thanks,

PS: It's also related to #14912

**Comment by mhartington** [comment]
👋 Hi, this is a known limitation in Vue. For custom input component, you need to bind to different events in order to mimic `v-model`. For example, in an app that uses searchbar, you to use `ionInput` instead

```html
        <ion-searchbar
          placeholder=""
          showCancelButton="true"
          debounce="0"
          :value="searchInput"
          @ionInput="searchInput = $event.target.value; onInput$.next($event.target.value)"
          @ionClear="searchCleared($event)">
        </ion-searchbar>
```

This isn't needed in Angular as it has the idea of Control Value Accessors which can enable ngModel support. I don't think Vue has anything similar, so this might be needed until we work on a proper vue integration layer and investigate things
