### ISSUE TITLE
ionic 4 camera plugin 

### ISSUE THREAD

**Issue by Ramakrishnatp** [ionic-team/ionic#15597]
Hi,
When I am trying to display the image which I captured with Camera. It's showing the error like "**not allowed to load local resource**" in ionic 4 version. Please have a look at the attached screenshot.
Please respond as early as possible that would help me a lot.

Thanks in advance.
![image 1](https://user-images.githubusercontent.com/34594130/45550846-c3172f00-b849-11e8-9236-b1f65dfa8871.png)

**Comment by ptitjes** [comment]
@Ramakrishnatp I believe this is an issue for [ionic-team/ionic-native](https://github.com/ionic-team/ionic-native), right ?
And by the way, GIYF: [cordova camera not allowed to load local resource](https://www.google.com/search?source=hp&ei=8dWbW53MI8aWaJi1m9AK&q=cordova+camera+not+allowed+to+load+local+resource&oq=cordova+camera+not+allowed+to+load+local+resource&gs_l=psy-ab.3..0.716.716.0.1183.2.1.0.0.0.0.123.123.0j1.1.0....0...1c.2.64.psy-ab..1.1.122.0...0.pvLuaTUoyYU).

I think this issue is related to [ionic-team/ionic-native](https://github.com/ionic-team/ionic-native) and that it can be closed.
