### ISSUE TITLE
Ionic 3: Deeplinks

### ISSUE THREAD

**Issue by kodeine** [ionic-team/ionic#15631]
hello, so i enabled deeplinks in my project and i am getting `Uncaught in promise: invalid link: IntroPage` and my intro page looks like this.
```
@IonicPage({
    segment: 'auth'
})
@Component({
    selector: 'page-intro',
    templateUrl: 'intro.html',
})
export class IntroPage {...}
```

app.module
```
links: [
                { component: TabsPage, name: 'Feed', segment: 'feed', defaultHistory: [TabsPage] },
                { component: TeamsListPage, name: 'Teams', segment: 'teams', defaultHistory: [TabsPage] },
                { component: IntroPage, name: 'Auth', segment: 'auth' },
```
this happens only when i enable links in `app.module`

Also, deeplinks support strings for lazy loaded pages because all of my pages are lazily loaded.

any ideas?

**Comment by mhartington** [comment]
In V3, you dont need to create a links array in the app.module file. The `@IonicPage` decorator should take care of all of that. That could be what the issue is.

Please see this reference project for examples.

https://github.com/mhartington/star-track-ionic

Please feel free to continue this on the [ionic forum](https://forum.ionicframework.com)
