### ISSUE TITLE
Ionic.Events: Eliminate danger source ...

### ISSUE THREAD

**Issue by Martin-Luckow** [ionic-team/ionic#15639]
# Feature Request

**Ionic Info**
4.3.2

**Describe the Feature Request**
I like Ionic.Events ... it's intuitive and easy. 
But dangerous at one point too: imagine, you work in a team on components that consume events. And one of you accidentally writes events.unsubscribe("sometopic"); ... without specifying a handler. He deletes ALL REGISTRATIONS on "sometopic" and the colleagues start looking for non-existent mistakes and never occuring events in their components and get into despair :)
Btw: this "killing feature" is undocumented.

**Describe Preferred Solution**
Deleting all registrations should only be possible by an explicit call, i.e. events.unsubscribeAll("sometopic"). 
The parameter list of events.unsubscribe("sometopic", handler) should be required to contain the intended handler (or produce an exception if none is specified).

**Comment by ghybs** [comment]
Hi @Martin-Luckow,

While I certainly agree with your point that unsubscribing all event listeners / handlers by mistake can lead to difficult to debug situations, it seems to me that we should also consider that such behaviour is already a common practice unfortunately.

See for example jQuery's [`.off()`](http://api.jquery.com/off/):

> Calling `.off()` with no arguments removes all handlers attached to the elements.

(so jQuery is even more powerful / dangerous since you do not even need to provide any event / topic name)

Of course that does not mean that all new libraries should stick with it. But that shows what many developers would implicitly expect from such feature.

I like your `unsubscribeAll` proposition.
