### ISSUE TITLE
Translation only works after clicking element instead of instant upgrading from beta 7 to 11

### ISSUE THREAD

**Issue by warntjo** [ionic-team/ionic#15704]
I've a problem with translations in beta 11 which is not present in beta 7. In the versions in between it sometimes works and other times not. The translation is only done in beta 11 after i click an element instead of directly after running the code.

The following code works in beta 7:

```
import { TranslateService } from '@ngx-translate/core';
...
...
this.translateService.use(languageItemCode);
this.translateService.reloadLang(languageItemCode);
```

Following is a gif with the problem.

![2018-09-21_10h15_35](https://user-images.githubusercontent.com/1901660/45868955-6060ee80-bd87-11e8-8739-741d3632097b.gif)

I hope someone has any idea what could be the reason it stopped work.

**Comment by peterpeterparker** [comment]
maybe?

    this.zone.run(() => {
      this.translateService.use(languageItemCode);
      this.translateService.reloadLang(languageItemCode);
    });

**Comment by jordanpurinton** [comment]
Having the same kind of problem in this issue I opened <a href="https://github.com/ionic-team/ionic/issues/15765">here</a>. Additionally, someone else an issue that may be related to this <a href="https://github.com/ionic-team/ionic/issues/15744">here</a>.

As @peterpeterparker described, `ngZone.run()` might work, but I've had mixed success with using that. Ideally, the Ionic team will see some us talking about this and hopefully work it into a new version in the future. 

As for me, I'm staying on beta.7 for now until this issue is hopefully resolved.

**Comment by mhartington** [comment]
Hi there! Does anyone have a sample app that they could provide to debug?

**Comment by warntjo** [comment]
We solved it by adding this.appRef.tick();

**Comment by paulstelzer** [comment]
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

And if this is still an issue, could someone add an repo like @mhartington says so we can debug the issue?
