### ISSUE TITLE
CodePush Failure: no such file or directory, lstat './platforms/android/assets/www/'

### ISSUE THREAD

**Issue by dc165015** [ionic-team/ionic#15718]
I followed the official ionic codepush example.

It used the platforms/android/assets/www folder, but there is neither assets folder, nor www folder under platforms/android in my project.

I also tried: ionic build, ionic cordova build android, ionic cordova prepare android. They are the same. The assets folder wasn't created at all.

How I can solve this problem?

**Comment by dc165015** [comment]
I found the assets folder is located in /platforms/android/app/build/intermediates/assets when used --debug option in ionic cordova run.   Or located in  /platforms/android/app/src/main/assets w/o debug option.  
I don't get why. But I think it should be documented at least.

**Comment by mhartington** [comment]
This is due to Cordova-android adopting a proper Android studio project setup. Those paths are not valid anymore. CodePush needs to update their docs.

As this is not an issue with the framework itself, I'm going to close this. For future reference, please open a question on the Ionic forum or slack if there are problems that are not directly related to the core framework.
