### ISSUE TITLE
[Ionic V4-beta.12] When Ionic 4 will be stable? 

### ISSUE THREAD

**Issue by Papamilo** [ionic-team/ionic#15791]
**I don't need to know the precise day but just to have an idea if it is 3 months, 6 months or a year?**

I will start a project at the beginning of 2019 (January or February). Maybe a bit later.

Will it be better to start with the actually 3.9 version even it will be very soon (but when ???) the 4 version, or should I start with the 4 version even it is actually beta but maybe in three months it will be released..depending on the Ionic team lifecycle development. Any advise ideas are welcome

Any info about their roadmap? (I search everywhere and don't find this info..blog, website, twitter, etc...)

**I know it's not the best location to ask ... But I think that some people are wondering the same question!**

Thanks in advance

**Comment by kensodemann** [comment]
Just to add to what @RHinderiks (which I think is absolutely correct), you are looking at a starting timeframe that is between 3 and 5 months out, depending on exactly when you start. Given that timeframe and the current state of things, I would _expect_ v4 to have had a GA release plus maybe a couple of bug-fix releases by then, but the future is always hard to predict.

If I were to be starting a project in 3 to 5 months, I would be choosing specific technologies and strategies now (hybrid mobile vs. native vs. pwa vs. some combo, which frameworks to use, etc), but I would hold off on specifics like which version to use until I got closer to starting the project. A lot can change in that timeframe.

Having used both versions, though, I would pick v4 even if I were starting today.

Hopefully that was helpful. I am going to have the bot close this since it isn't really a bug or feature request.
