### ISSUE TITLE
Ionic 4 Beta 12 - Ion-content does not take footer into height calculation on iOS 10.3

### ISSUE THREAD

**Issue by hghammoud** [ionic-team/ionic#15799]
# Bug Report

The height calculation on iOS 10.3 does not take the footer into consideration

![image](https://user-images.githubusercontent.com/8034427/46210476-1ea8e880-c331-11e8-86b3-0a5cfa67ed71.png)

```
</ion-content>
<ion-footer>
  <ion-toolbar>
    <div class="bottomTabbar">
      <a ion-activatable href="/#/tabs/(find:find)">
        <boink-icon-button iconSrc="search" [dark]="true" [showRipple]="true" boinkIcon="true" label="Find" [routerLink]="['/tabs/', {outlets: {'find': 'find'}}]"
        routerLinkActive="active"></boink-icon-button>
      </a>
      <a ion-activatable href="/#/tabs/(find:find)">
        <boink-icon-button iconSrc="explore" [dark]="true" [showRipple]="true" boinkIcon="true" label="Explore"
        [routerLink]="['/tabs/', {outlets: {'about': 'about', 'menu': null}}]" routerLinkActive="active"></boink-icon-button>
      </a>
      <a ion-activatable href="/#/tabs/(find:find)">
        <boink-icon-button iconSrc="brightness-46" [dark]="true" [showRipple]="true" boinkIcon="true" label="Inspire"
        [routerLink]="['/tabs/', {outlets: {'about': 'about', 'menu': null}}]" routerLinkActive="active"></boink-icon-button>
      </a>
      <a ion-activatable href="/#/tabs/(saved:saved)">
        <boink-icon-button iconSrc="heart_empty" [dark]="true" [showRipple]="true" boinkIcon="true" label="Saved"
        [routerLink]="['/tabs/', {outlets: {'saved': 'saved'}}]" routerLinkActive="active"></boink-icon-button>
      </a>
    </div>
  </ion-toolbar>
</ion-footer>
```

Adding display: flex; to ion-content class solves the issue.

**Comment by mhartington** [comment]
Hi there! Is this still an issue with the latest release?

**Comment by cannocan** [comment]
> Hi there! Is this still an issue with the latest release?

I think it's still a problem 
iphone 6 : ios10.3
ionic:  4.0.0 Neutronium 

Android and ios 11、12 is OK!

**Comment by supperdsj** [comment]
same issure here

**Comment by keyvan-m-sadeghi** [comment]
Same issue

**Comment by keyvan-m-sadeghi** [comment]
Same issue on `ion-header` as well.

**Comment by liamdebeasi** [comment]
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.
