### ISSUE TITLE
[Ionic@4.0.0-beta.12] ion-content background can't be set with css background property

### ISSUE THREAD

**Issue by UVKApps** [ionic-team/ionic#15849]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\{myname}\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.8
   @capacitor/core           : 1.0.0-beta.8

System:

   NodeJS : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10
```

**Describe the Bug**
Background color of ion-content can not be set with background or background-color css property.  To style the background --background property has to be set. 

Because of Background color delegation to ion-scroll component the background property of ion-content was changed to --background. Therefore css won't overwrite its value. 

**Steps to Reproduce**
1. Go to any page
2. Add css class with background property to ion-content
3. Still displaying white background
4. set --background as property in css class instead of background
5. background color is working

**Expected Behavior**
Background can be styled by overwriting background property on ion-content

**Comment by paulstelzer** [comment]
Take a look at this #15841

This is not an issue because Ionic uses css variables now.

You can also change the background of ion-content by adding color to it:

`<ion-content color="primary">`

**Comment by brandyscarney** [comment]
Thank you for the issue. This is not a bug, but rather the desired behavior for a few reasons.

1. The inner scroll element needs to have the background in order to work with `fullscreen` mode.
2. The `ion-content` element uses [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) which means the inner scroll element needs to use CSS variables in order to change its background from the parent `ion-content`. 
3. For consistency. All elements with the `color` attribute should be overridden using `--color` or `--background`. This is because the `color` attribute on elements will take precedence over any `--color` or `--background` variables set. This is on purpose because if you were to do the following:

    ```
    ion-content {
     --background: blue;
    }
    ``` 

    It would be a quick way to set **all of the `ion-content` elements** to a `blue` background, **unless** they have the `color` attribute applied. The `color` attribute overrides the `background` property directly so if you were to set it like the following example, and if we had the `background` applied to `ion-content` instead of the inner scroll element, there would be conflicts in what takes precedence (in our testing the `color` attribute was not taking priority). 

    ```
    ion-content {
      background: blue;
    }
    ```

    We decided that the colors set by the `color` attribute should always take higher precedence, because if you don't want those colors then the `color` attribute shouldn't be used on the element.

I recommend reading through our [Theming documentation](https://beta.ionicframework.com/docs/theming/basics) for more information on setting colors and CSS variables and if you have any feedback for ways to improve our documentation, please [create an issue on the ionic-docs repository](https://github.com/ionic-team/ionic-docs/issues/new). Thanks!
