### ISSUE TITLE
[Ionic V4.0.0-beta.13] <ion-tabs> "color" attribute not working anymore

### ISSUE THREAD

**Issue by raphjutras** [ionic-team/ionic#15942]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Raphael\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.13
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 6 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Describe the Bug**
After updating to beta.13, the <ion-tabs> "color" attribute does not work anymore.

**Related Code**
```
<ion-tabs color="primary">
  <ion-tab label="xyz" icon="md-apps" href="/layout/(home:home)">
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>
  <ion-tab label="xyz" icon="md-time" href="/layout/(about:about)">
    <ion-router-outlet name="about"></ion-router-outlet>
  </ion-tab>
   <ion-tab label="xyz" icon="md-time" href="/layout/(about:about)">
    <ion-router-outlet name="about"></ion-router-outlet>
  </ion-tab>
   <ion-tab label="xyz" icon="md-time" href="/layout/(about:about)">
    <ion-router-outlet name="about"></ion-router-outlet>
  </ion-tab>
</ion-tabs>
```

**Expected Behavior**
The tab Style should change to "primary" colors like it did before.

**Comment by philmerrell** [comment]
It looks like there might be a breaking change. I see a ion-tabbar component that now handles the `color` property in:

[core/src/components/tabs/test/colors/index.html
](https://github.com/ionic-team/ionic/blob/545db2e4c496c9ed6ce5e86a82e87334bcf0b9ba/core/src/components/tabs/test/colors/index.html)

Unfortunately, when I try to use the ion-tabbar component, it is not a known component:

`ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-tabbar' is not a known element:`

If that test file represents the new usage, I don't see `tabbar` is established as a declaration in the [ionic angular module](https://github.com/ionic-team/ionic/blob/master/angular/src/ionic-module.ts).

**Comment by lukeisontheroad** [comment]
Same issue here. Upgraded from beta 11, now my tabs lost their primary color and are at the wrong position.

**Comment by hebra** [comment]
Same issue here. As @philmerrell already figured out the main problem is the missing declaration in the ionic/angular module definition.
 For me this is a blocker right now.
@manucorporat can someone of the Ionic angular team please have a look on push a bugfix release?

**Comment by wenisy** [comment]
@philmerrell Yeah, lots of breaking changes in this this commit https://github.com/ionic-team/ionic/commit/e3bbfd0b05962591af317613d83599e97d384211#diff-e5cd10973d20ca128cfbb4124d84c71c .

If you check tabs.tsx file you would find they just removed these code.
```javascript
<ion-tabbar	      
  mode={this.mode}	        
  tabs={this.tabs.slice()}	     
  color={this.color}	      
  selectedTab={this.selectedTab}	        
  highlight={this.tabbarHighlight}	          
  placement={this.tabbarPlacement}	          
  layout={this.tabbarLayout}	        
  translucent={this.translucent}	        
  >	      
</ion-tabbar>
```

That's the reason why we can't not use color, highlight, placement and other attributes.

And just like what you said, the doesn't declare <ion-tabbar>, it's still an unknown component.

Hope they could fix it ASAP.

**Comment by wenisy** [comment]
I just found seems @manucorporat has already fixed it.
https://github.com/ionic-team/ionic/pull/15954/commits/49d3f1b306af988119205e1eb4ad5f225b79f069

Could they just release a bug fix version?

**Comment by hebra** [comment]
A workaround until the fix is released is to use ng-deep in the (S)CSS to force a background color like this 
```
::ng-deep ion-tabbar {
    background: red !important;
}
```

**Comment by brandyscarney** [comment]
Thanks for the issue! There was a change made prior to the `4.0.0-beta.13` release where in order to customize the Tab Bar (which was added for you) you would have to add an `ion-tabbar` component. So the solution to this issue (in `4.0.0-beta.13`) would be to do the following:

```diff
- <ion-tabs color="primary">
+ <ion-tabs>
    <ion-tab label="xyz" icon="md-apps" href="/layout/(home:home)">
      <ion-router-outlet name="home"></ion-router-outlet>
    </ion-tab>
    <ion-tab label="xyz" icon="md-time" href="/layout/(about:about)">
      <ion-router-outlet name="about"></ion-router-outlet>
    </ion-tab>
    <ion-tab label="xyz" icon="md-time" href="/layout/(about:about)">
      <ion-router-outlet name="about"></ion-router-outlet>
    </ion-tab>
    <ion-tab label="xyz" icon="md-time" href="/layout/(about:about)">
      <ion-router-outlet name="about"></ion-router-outlet>
    </ion-tab>

+   <ion-tabbar color="primary"></ion-tabbar>
  </ion-tabs>
```

but as you can see the following error is popping up `ERROR Error: Uncaught (in promise): Error: Template parse errors: 'ion-tabbar' is not a known element:`.

So after this change was implemented we had some team discussions surrounding the API and implementation. We decided that we would remove some of the magic that happens to generate the Tabs (and tab bar) so that users have full control over customizing it. We came up with the following API:

```html
<ion-tabs> 
  <ion-tab-bar>
    <!-- No ion-tab, just a link that looks like a tab -->
    <ion-tab-button href=”https://stenciljs.com”> 
      <ion-icon name="globe"></ion-icon>
      <ion-label>Schedule</ion-label>
    </ion-tab-button>

    <!-- No ion-tab, just a button that looks like a tab -->
    <ion-tab-button (click)=”showDiv()”> 
      <ion-icon name="clock"></ion-icon>
      <ion-label>Timer</ion-label>
    </ion-tab-button>

    <!-- Connected to ion-tab, on click will show the ion-tab with tab="home-view" -->
    <ion-tab-button tab=”home-view”> 
      <ion-icon name="home"></ion-icon>
      <ion-label>Home</ion-label>
    </ion-tab-button>
  </ion-tab-bar>

  <ion-tab tab=”home-view”>
    <ion-content></ion-content>
    <!-- or -->
    <ion-nav></ion-nav>
    <!-- or -->
    <ion-router-outlet></ion-router-outlet>
  </ion-tab>

</ion-tabs>
```

**ion-tabs**: container element
**ion-tab-bar**: container for the tab buttons
**ion-tab-button**: actual tab button that will be clicked to change content/view
**ion-tab**: container for the tab’s content/navigation

- `ion-tabs` is the container element
- `ion-tabs` is composed of 2 child components: `ion-tab-bar` and ion-tab 
  - `ion-tab-bar` is a container for the actual tab buttons to click
    - contains an `ion-tab-button`, which can contain an `ion-icon`, `ion-label`, or `ion-badge` (or any other element if the user wants to style it)
    - The `ion-tab-button` has a layout property to support different element/icon positions
    - `layout` is not provided at the `ion-tab-bar` level, but can be changed by the global config
- `ion-tab` is a container for the content/view/navigation
  - can hold static content or a router outlet/navigation component
- `ion-tab-button` has a `tab` property which will reference the `ion-tab` with the matching `tab` property

The above was implemented in the following PR and will be in the `4.0.0-beta.14` release: https://github.com/ionic-team/ionic/pull/16048

This will also allow users to use an `ion-tab-bar` as a standalone component. 

As you can see from the comments above, you could also use the global theme variables to update all of the tab bars in an application. However, there were some bugs surrounding the variables that will be fixed in `4.0.0-beta.14` and several of the variables have been renamed to be more consistent with our other variables and the new API. See the following PR: https://github.com/ionic-team/ionic/pull/16003 and the updated documentation here: https://beta.ionicframework.com/docs/theming/advanced#application-colors

Please let me know if you have any questions, thank you! 🙂

**Comment by hebra** [comment]
Thanks @ brandyscarney  for the details on the changed behaviour. Now the only open question is: when will beta.14 be available? It's almost 2 weeks now since the bug was originally reported.

**Comment by brandyscarney** [comment]
I'm going to close this as `4.0.0-beta.14` was just released, thanks!
