### ISSUE TITLE
[V4] Keep navigation history individual when using tabs

### ISSUE THREAD

**Issue by yannbf** [ionic-team/ionic#16192]
# Feature Request

**Describe the Feature Request**
On Ionic 3, when using tabs, it was possible to keep individual navigation history stack per tab. On Ionic 4, with Angular router, it is currently not possible.

**Describe Preferred Solution**
Ideally the views should be persisted when switching between tabs. 

**Describe Alternatives**
There is currently an alternative described on https://www.joshmorony.com/creating-a-tabs-layout-with-angular-routing-and-ionic-4/ and using that + subscribing to a navigation event on angular router to keep a stack for each router-outlet, it might be possible to achieve it.

**Comment by toriphes** [comment]
keeping the navigation history on each tab is a design principle on native platforms. Looking in the issues I can not understand if ionic team will implement this behavior that was already available in ionic 3.

The alternative would be to use `ion-nav` instead of `ion-router-outlet` within the `ion-tab` component even if not recommended because it seems that in the future `ion-nav` will be deprecated.
Am I Wrong?

Do we have to find a workaround by ourselves or is there any plan to implement the navigation history in the tab component?

**Comment by toriphes** [comment]
I think this issue can be closed.
Navigation history is now available in ionic 4.0.0-beta.16
