### ISSUE TITLE
4.0.0-beta.15 ionic-split-pane bad positioning for slides

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#16252]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
C:\ae\adaept.com\aetabs>ionic info

Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.10.4
   @angular-devkit/schematics    : 7.0.4
   @angular/cli                  : 7.0.4
   @ionic/angular-toolkit        : 1.1.0

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10


C:\ae\adaept.com\aetabs>
```

**Describe the Bug**

**Steps to Reproduce**
https://aetabs.adaept.com
![slide-position](https://user-images.githubusercontent.com/140737/48113696-f4402a00-e210-11e8-87f5-d9c0169d50e9.gif)

Compare with:
https://aeion4.adaept.com
![slide-position3](https://user-images.githubusercontent.com/140737/48113912-bdb6df00-e211-11e8-82fd-437a9945f59a.gif)

**Related Code**
https://github.com/peterennis/aetabs
https://github.com/peterennis/aeion4

**Expected Behavior**
Correct resizing and positioning of slides when using split-pane.

**Comment by almothafar** [comment]
Yeah got the same issue even in previous versions, I noticed that the issue kinda better if you use https://github.com/zefoy/ngx-swiper-wrapper instead of ionic swiper (they both are the same), just try it and use the component version, not the directive.

You will get some other issues, but give it a try, from my side I gave up the split at all and removed it, and used `Platform` from `import { Platform } from '@ionic/angular'`  and `*ngIf="platform.is('mobile')"` to render menu and its button for mobile and `*ngIf="!platform.is('mobile')"` for desktop, not really best practice but it gives me some progress instead of wasting time catching that component issues.

**Comment by peterennis** [comment]
@almothafar 
Thanks for that! It works on mobile with the split-pane code still in place. I can live with the poor desktop slide presentation on PWA at the moment, but it's good to know a workaround.

**Comment by peterennis** [comment]
Still an issue in beta.19
