### ISSUE TITLE
Possibility of customizing ion-content scrollbar in Chrome Browser

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic#16336]
# Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.15 
   @angular-devkit/build-angular : 0.10.3 
   @angular-devkit/schematics    : 7.0.3 
   @angular/cli                  : 7.0.3 
   @ionic/angular-toolkit        : not installed

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.0.1
   OS     : Windows 10
```

**Describe the Feature Request**
Possibility to customize scrollbar in chrome

**Describe Preferred Solution**

  ::-webkit-scrollbar {
    width: inherit
    height: inherit;
  }

::-webkit-scrollbar-track {
  background: inherit;
}

::-webkit-scrollbar-thumb {
    background: inherit;
    border-radius: inherit;
    border: inherit;
}

**Comment by GuilhermeBCC** [comment]
I can not change because of the SHADOW DOM

**Comment by almothafar** [comment]
@GuilhermeBCC that Shadow DOM is related to `[ViewEncapsulation](https://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html)` of Angular, not Ionic issue, but I got that style to work inside my application, because actually `-webkit-scrollbar` related to browser styling, not the component itself, it is style directive for how browser should render the scrollbar.

Anyway, you maybe need to provide an example, because I do totally understand your issue, I got that before, but it was an issue with my template and got things fixed when I fixed my template.

**Comment by lgmnemesis** [comment]
@GuilhermeBCC  I think you're right. I'm facing the same issue, can not change the .inner-scroll class which is inside the SHADOW DOM of the ion-content component
