### ISSUE TITLE
[4.0.0-beta.15] css var to set max width of ion-select

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic#16341]
Currently the ion-select receives a max-width of 45% by this class :host(.in-item). I suspect this is done with the intent to fit a label in front of it or something similar. However, we would like a 100% ion-select box where the function of the label is basically taken over by the placeholder.

The current solution would be to overwrite the max width by putting a class on the ion-select.

My preferred solution would be to have a css var to overwrite and change its max width

**Comment by brandyscarney** [comment]
Thanks for the issue! In general, we are trying to only add CSS variables when it cannot be accomplished by pure CSS. For example, many components don't have variables for changing their text properties such as `font-weight` or `font-family` because these properties can be set using CSS:

```
ion-button {
  font-weight: 500;
}
```

Since you can easily modify the max-width of a select by using the following:

```
ion-select {
  max-width: 100%;
}
```

I do not see a need for a CSS variable here. I've added an example to this codepen where it is working: https://codepen.io/brandyscarney/pen/aQPQaz

However, if you're seeing problems where this isn't working, please let me know. Thanks!
