### ISSUE TITLE
Ionic 4 core using with vuejs without CDN creates 100s of files

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#16391]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic beta.15
```

**Describe the Bug**
On using ionic 4 via package.json with VueJS. It creates so many chunk files in dist/js folder. The app does works but is there any way we can combine all these to a single file.

In package.json
```
		"@ionic/core": "4.0.0-beta.15",
		"@ionic/vue": "0.0.1",
```

Now in main.js I am doing

```
import Ionic from "@ionic/vue";
Vue.use(Ionic);
```

On doing a build many files are created
<img width="351" alt="screenshot 2018-11-20 at 2 30 43 pm" src="https://user-images.githubusercontent.com/8480351/48762703-9b24cb80-ecd1-11e8-83b2-9d3e23a0b0d2.png">

**Comment by manucorporat** [comment]
Ionic includes hundreds of components, and styles for both iOS and MD, a single file would be huge. This is actually a feature, not a bug.

**Comment by stripathix** [comment]
Thanks for clarification.

**Comment by zwacky** [comment]
Hey there, I was also asking myself this. I'm aware of the big configuration possibilities in Ionic.

I probably miss something here... To me it feels weird to load 50+ (small) files at once. Especially for users with a slow/unreliable connection. How can this work? Are there any plans to change this or it doesn't really pose a disadvantage because of some http protocol feature or something?
Thanks for reading!

**Comment by stripathix** [comment]
@zwacky  What I feel is ionic does not load all components at once rather it load only those components that are needed by the application.

**Comment by zwacky** [comment]
I just had a more precise look at those many requests (I'm also using Ionic with Vue).
It turns out the the requests themselves in the dev console are `prefetch`es and Ionic only loads content for the components that are currently used like you mentioned, @stripathix. 

Now it makes sense to me as I understand what these many entries in the dev console are.

(Vue basically adds all *.js files as prefetches. And with HTTP 2.0 this shouldn't give any headaches as far as I understand.)
