### ISSUE TITLE
[Feature Request] Input press enter to submit form

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#16547]
# Feature Request

**Describe the Feature Request**
If I wrap my inputs inside a form and I press enter in the ion-input field, nothing happens. There should be a possibilty to submit the form.

**Describe Preferred Solution**
If a user pressed enter the form will be submitted if there is a ion-button type="submit" and form has `(ngSubmit)="sub()"`

**Describe Alternatives**
Get access to onKeyDown events of the input field

**Related Code**
-

**Additional Context**
-

**Comment by selipso** [comment]
Angular has a built-in way to do this with the `(keyup.enter)` event and it works with `ion-button`. Try it out!

**Comment by selipso** [comment]
That's a little trickier to do since you are accessing the native element from another element (Angular tries to discourage direct DOM manipulation) but if they are both part of the same component, you can do something like this.

**template.html**
```
<ion-input [hidden]="editingItemIndex !== idx" required type="text" 
  value="{{eachItem[displayKey] || eachItem}}"
  (keyup.enter)="finishEditing($event, idx, eachItem)"
  #editableInput
></ion-input>
<ion-button (click)="editItem($event, editableInput)></ion-button>
```
The above code will pass a native reference to the ion-input through the template variable that was declared, `#editableInput`. Then in your `editItem()` function in the input, you can do something like:

```ts
...
editItem(event, inputRef) {
  inputRef.nativeElement.focus();
}
...
```

The above technique works well for repeating items in a list. I haven't tested the code so you may need to debug it. Another alternative is this answer on StackOverflow for smaller forms: https://stackoverflow.com/a/46483038

**Comment by paulstelzer** [comment]
Thanks will test it :)
