### ISSUE TITLE
Rename interfaces and classes with Prefix (IonInput instead of Input) - @ionic/angular

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#16550]
# Feature Request

**Describe the Feature Request**
At the moment the components of Ionic have the interface and class names like "Input" or "Select". Problem is that this interface and class names are used by other packages, "Input" for example by `@angular/core`.

If you now want to declare variables (for example in ViewChild) it collides with it (see Related Code).

**Describe Preferred Solution**
I think it would be great if these classes and interfaces get a Prefix like "IonInput" instead of "Input".

**Describe Alternatives**

**Related Code**

![code_2018-12-01_13-00-27](https://user-images.githubusercontent.com/20501666/49328000-5159a200-f569-11e8-812d-9e7ebaad648b.jpg)

`@ionic/angular `code:

```
export declare interface Input extends StencilComponents<'IonInput'> {

}
export declare class Input {

}
```

**Comment by manucorporat** [comment]
interesting! i see how this can become a problem! thanks a lot for the feedback, we will review it before RC.

It also seems nice to have a better consistency between Vue, React and Angular, since we are using the `Ion` prefix there...

But it would be a "breaking change", need to talk with the team!

**Comment by manucorporat** [comment]
I removed [Feature request], since it's more of an API thing, than a feature 👍
