### ISSUE TITLE
Opening Modal Multiple Times on demo site - Causes it to be no longer visible

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/ionic#16601]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.
```
N/A - As the bug is on the ionic framework website - docs - demo phone / frame.  
```

**Describe the Bug**
On the ionic demo site https://beta.ionicframework.com/docs/components/#modal, interacting with the modal multiple times causes it to stop being visible / you can no longer open it. Also interaction with the screen is blocked and you would need to restart the page. 

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/components/#modal
2. Click on Golum => watch how the modal comes up, click on Cancel to dismiss
3. Click on Frodo Baggins - watch how the screen freezes
4. Attached mini demo below
![modal-issue-ionic4](https://user-images.githubusercontent.com/3638322/49541795-d1ea0c80-f8a1-11e8-80cf-c2d227a816b5.gif)

**Related Code**
N/A
**Expected Behavior**
The modal should be able to be closed and re-opened many times.

**Additional Context**
N/A

**Comment by peterpeterparker** [comment]
@tonyawad88 I don't think that the problem is "interacting multiple times cause it to be no longer visible" but rather that the website options "Frodo Baggins and Sam" doesn't open the modal

If you try just with "Gollum" then you could open/close as many times the modals you want

If you try the other options, nothing happens and the modal can't be opened
