### ISSUE TITLE
[4.0.0-beta.18] ion-refresher has other content behind it when pulled down

### ISSUE THREAD

**Issue by jordanpurinton** [ionic-team/ionic#16730]
**Ionic version:**
[x] **4.x**

**Current behavior:**
After upgrading to beta-18, the `ion-refresher` component is behaving really strangely. Basically, when I go to pull down my refresher on a tab page, the content that was on the screen when the app initially loaded is still there. 

Kind of hard to explain entirely through text so I'll provide a gif and a gist of my html tab pages as well.

**gif**: https://i.imgur.com/BQdeuZp.gifv
**gist**: https://gist.github.com/jordanpurinton/7ce25e7ed351554ead2ce188795cd4ea

**Expected behavior:**
For there to be nothing behind the refresher when I pull down.

**Ionic info:** 
```
  Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\path\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.18
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.2
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.3
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 11 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by paulstelzer** [comment]
Thanks for your issue! This change go back to me. The reason is to make it look like in Ionic v3 -> https://ionicframework.com/docs/api/components/refresher/Refresher/

The Refresher is BEHIND the content if you pull down and will be  visible if you pushed enough.

In your gif everything looks like expected.

You self added the content behind 

`<span *ngIf="isLoading">Getting vehicles<ion-spinner name="dots"></ion-spinner></span>`

If you don't want the loading spinner and pullingIcon just add the following:

<ion-refresher-content [pullingIcon]="null" [refreshingSpinner]="null"></ion-refresher-content>

**Comment by jordanpurinton** [comment]
I'm afraid I can't reproduce the whole project as it's confidential, but I've included the routing modules if that helps.

**Comment by paulstelzer** [comment]
@jordanpurinton make a repo where we can see the issue :)

**Comment by hghammoud** [comment]
I would also add that the ion-refresher  it's not showing in beta.19. z-index= -1.

**Comment by paulstelzer** [comment]
The refresher should be visible after you push down the content. But if this problem stays, I will reset to z-index: 0 like before but then it looks ugly

A repo would be this best

**Comment by hghammoud** [comment]
With z-index: 0 since its automatically added to the fixed slot in the IonContent its always on top of the other scrollable content -> the ticket at hand.

However if I can suggest a different implementation. Instead of a fixed height why not make the height dynamic with the pull deltaY? 

I hooked into the ionPull event to dynamically increase my own refresher content. This was my workaround. **By the way the "detail" in the IonPull event is always null.**

**Comment by jordanpurinton** [comment]
This issue still remains on rc

**Comment by paulstelzer** [comment]
@jordanpurinton Until now I have ot seen a Gihub repo with the issue . in My repo everything is working -> https://github.com/ionic-team/ionic/issues/16730#issuecomment-447766646

So it would be great if you create a repo where I can test it
