### ISSUE TITLE
beta.19 - serious jitter for svg animation

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#16776]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

![jitter](https://user-images.githubusercontent.com/140737/50063776-b6fd7f00-0162-11e9-8d0f-6685c0921739.gif)

![jitterdesktop2](https://user-images.githubusercontent.com/140737/50063959-8cf88c80-0163-11e9-9d4e-16199e42ba15.gif)

Jitter on desktop and on android device when deployed.
Initially looks good.
Click on Contacts
Click on Home and the problem is seem

**Expected behavior:**

Smooth animation like previous versions.
This was ok in beta.17 

**Steps to reproduce:**

**Related code:**

https://github.com/peterennis/aetabs
https://aetabs.adaept.com

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by paulstelzer** [comment]
I think the problem occurs because your Home tab will be hidden in the DOM, if you switch back to Home, the component becomes active again and so the jitter happens. This not happened in beta.17 and before because the component in the tabs was active all time (so also the animation was active).

Try the following:

```
ionViewDidLeave() {
 // Deactive the animation / svg here
}

ionViewWillEnter() {
 // Activate the animation / svg here
}
```

So the svg will stops the animation and if you come back you start it again

More information about the lifecycle hooks: https://medium.com/@paulstelzer/ionic-4-and-the-lifecycle-hooks-4fe9eabb2864

So from my point of view, your issue is not something what we can fix, instead you have to take care of it

**Comment by manucorporat** [comment]
Indeed it's a bug in your code: 
https://github.com/peterennis/aetabs/blob/104d4da37bcb1a6efb9dab884fb74ec2edfe05fb/src/app/home/home.page.ts#L75-L78

ionViewDidEnter can be called many times, use `ngOnInit` instead of remove the stars in ionViewWillLeave.
