### ISSUE TITLE
[4.0.0-rc.0] ion-tab-button requires tab contradictory to the docs and preventing 'plain buttons'

### ISSUE THREAD

**Issue by tehXor** [ionic-team/ionic#16845]
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.0**

**Current behavior:**
An `ion-tab-button` without a `tab` attribute but only a `(click)` attribute will throw an exception on load that tab is required. On click it will try to navigate to `<current-route>/undefined` which again will lead to an exception which also prevents `(click)` to be executed.

**Expected behavior:**
Like the docs say at https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#tabs this should be _"No ion-tab, just a button that looks like a tab"_ and therefore `(click)` should be executed.

**Steps to reproduce:**
Build an example like shown at https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#tabs under **"New Usage Example:"** and here under **"No ion-tab, just a button that looks like a tab"**

**Comment by goelectricstations** [comment]
I know same for me!

**Comment by JeeDay** [comment]
Hello @manucorporat,

First a triple GREAAT thank you ( All Ionic Team ) for great job you are doing with this Ionic 4's version.

----------------------- I CONTACT YOU FOR THIS ------------------------

I tried to add ( click a event, then a href attribute ) on the ion-tab-button component.

But it raise the error that the "tab" attribute is mandatory etc ..

- [When I watch your PR, the error is fixed. SO It is OK ] 

- [When I watch the doc of the ion-tab-buttons component (https://beta.ionicframework.com/docs )
I see it is updated with href attribute etc .. SO It is OK ] 

- [ When I create a new project based on the latest Ionic's version ( 4.0.0-rc.0 ), the problem is still present.] 

----------------------------- MY QUESTION ------------------------------

Please do you know when the next release ( 4.0.0-rc.1 or other ) is planned ?
