### ISSUE TITLE
[4.0.0-rc.0] Ionic 4 back button callback method executing twice

### ISSUE THREAD

**Issue by UmairYasin** [ionic-team/ionic#16925]
I am using ionic platform backbutton to over ride the hardware back button functionality. Its working fine to load the previous page but its calling the callback method of backbutton subscribeWithPriority twice. So if i display the pop up in callback method, that pop up is displaying twice which is very annoying. Below is the code i have added in constructor of my app module.

I am only using this back button subscription at one place in my app and that is the main app module as i wanted to show the exit popup msg to user when back button is pressed.

Below is the code for back button subscription:

```
this.backBtnSubscriber = this.platform.backButton
    .subscribeWithPriority(9999,
      () => {
        this.alertDialogService.presentAlert();
      });
```
Details about my ionic version are below:

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.7.2
   @angular-devkit/schematics    : 0.7.2
   @angular/cli                  : 6.1.1
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.4.1 
   npm               : 6.1.0
   OS                : Windows 10
```

**Comment by manucorporat** [comment]
where are you calling `this.platform.backButton` can you share some context?

**Comment by UmairYasin** [comment]
> where are you calling `this.platform.backButton` can you share some context?

In the constructor of Root Module as shown below:

```
export class  AppComponent implements OnInit, OnDestroy, DoCheck  {
  private backBtnSubscriber: Subscription;

  constructor(public router: Router,
              private alertDialogService: AlertDialogService,
              private platform: Platform) {
    this.backBtnSubscriber = 
          this.platform.backButton.subscribeWithPriority(9999,
        () => this.alertDialogService.presentAlert());
  }

ngOnDestroy(): void {
    if (this.backBtnSubscriber) {
      this.disposeSubscription();
    }
  }
 }
```

**Comment by olivermuc** [comment]
I have also looked at using exclusively the `platform.backButton` function (read: overwriting the default routine) to find a workaround for the camera opt out issue documented here:
https://github.com/ionic-team/ionic/issues/16505

**Unfortunately the issue is still not resolved - found it in beta.16, but really it's probably been around in v4 from the get-go.**

Please please please @ionic allow the devs to better control when the default backbutton routine is being executed and when not. Or better yet, please fix it in our code, my ticket above outlines the issue and suggestion to fix.

**Comment by fer-fullstackdev** [comment]
Hello. @UmairYasin @manucorporat 
I have same issue. 
The callback function is fired twice.
Is this issue not solved yet???
Thanks for your help in advance.

**Comment by fer-fullstackdev** [comment]
@liamdebeasi

**Comment by fer-fullstackdev** [comment]
Please let me know. @liamdebeasi
Thanks.

**Comment by fer-fullstackdev** [comment]
Any update yet? @liamdebeasi , @UmairYasin , @manucorporat

**Comment by clemishow** [comment]
The problem's still there. Anyone hear anything in the last nine months?

**Comment by liamdebeasi** [comment]
Hi everyone,

Can you try this on the latest version of Ionic Framework? (v5.1.1). There were many hardware back button fixes that have gone into the framework since this issue was created.

We have also launched new documentation that gives a comprehensive look at how to control the hardware back button in Ionic apps: https://ionicframework.com/docs/developing/hardware-back-button.

I have tried the example provided in https://github.com/ionic-team/ionic/issues/16925#issue-395092384 on Ionic Framework v5.1.1 and am no longer able to reproduce the issue.

Also, if you want to show an alert before exiting the application, we recommend setting the priority to `-1` instead of `9999`. This way, pressing the hardware back button again will dismiss the alert: https://ionicframework.com/docs/developing/hardware-back-button#exiting-the-app.

**Comment by liamdebeasi** [comment]
Hi everyone,

I have not heard back regarding my previous comment https://github.com/ionic-team/ionic/issues/16925#issuecomment-631507177, so I am going to close this issue.

Like I mentioned previously, there have been many hardware back button fixes since this issue was created, so I recommend trying this out again on the latest version of Ionic Framework.

If you are still running into bugs, please create a new issue, and provide a repo we can use to reproduce the issue. Thank you!

**Comment by svrakata** [comment]
I want to appologies in advance if this is not the right place to write my comment.
For those who struggle with the double firing of the handler of the "ionBackButton" event, the problem in my code was rendering IonApp component twice with ReactDOM.render method.
Cheers.
