### ISSUE TITLE
[4.0.0-rc.0] Menu button is offset

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#16950]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In a toolbar with a menu-button, the menu-button's padding will be offset differently if there is a `ion-title` vs `ion-segment`

**Expected behavior:**

The padding should be consistent.

**Steps to reproduce:**

**Related code:**

Here the button's padding is wrong

```html
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-segment>
      <ion-segment-button value="all">
        All
      </ion-segment-button>
      <ion-segment-button value="favorites">
        Favorites
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-header>
```

Here is is correct

```html
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>Speakers</ion-title>
  </ion-toolbar>
</ion-header>
```

Ionic conference app

![screen shot 2019-01-03 at 2 40 54 pm](https://user-images.githubusercontent.com/2835826/50659401-7b3c2500-0f6a-11e9-9135-2739c4d9606a.png)
![screen shot 2019-01-03 at 2 40 48 pm](https://user-images.githubusercontent.com/2835826/50659402-7b3c2500-0f6a-11e9-88e1-5f641288fd9c.png)

**Comment by brandyscarney** [comment]
Okay finally got to debug this. The source of this bug is the following CSS: https://github.com/ionic-team/ionic/blob/master/core/src/components/toolbar/toolbar.md.scss#L33-L38

```css
:host(.toolbar-segment) {
  --padding-top: 0;
  --padding-bottom: 0;
  --padding-start: 0;
  --padding-end: 0;
}
```

This was added in Toolbar so that when a segment is the only component in the toolbar it won't have any padding around it, but I agree that it looks weird with buttons in the toolbar with it. I don't want to remove this in it's entirety since it's needed for that use case so I will look into a better solution.
