### ISSUE TITLE
ion-input display error (visual error)

### ISSUE THREAD

**Issue by ygr757326** [ionic-team/ionic#17027]
# Bug Report

**Ionic version:**

[x] **4.x**
4.5.0
**Current behavior:**

ion-input 使用 ionChange 和ngModel时， 更改数据时，显示的文本只会改变一次，之后永远不会发生改变

**Expected behavior:**

我想要ion-input 显示的文本为2
**Steps to reproduce:**

**Related code:**

```
<ion-input (ionChange)="change($event.detail.value)" [(ngModel)]="data.num">

change(){
  if(this.data.num>5)this.data.num=2;
}
```

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```
输入9 显示 2
继续输入 1显示 21
继续输入2 显示 212
继续输入3 显示  2123

**Comment by brandyscarney** [comment]
**Translated version (through Google):**

**Current behavior:**
When ion-input uses ionChange and ngModel, when the data is changed, the displayed text will only change once and never change.

**Expected behavior:**
I want the text displayed by ion-input to be 2

**Steps to reproduce:**
Enter 9 to display 2
Continue to enter 1 display 21
Continue to enter 2 display 212
Continue to enter 3 display 2123

**Related code:**

```
<ion-input (ionChange)="change($event.detail.value)" [(ngModel)]="data.num">

change(){
  if(this.data.num>5)this.data.num=2;
}
```

**Comment by manucorporat** [comment]
Thanks for the issue! Could you please provide a repository or plunker that has a minimal amount of code to reproduce this?
