### ISSUE TITLE
[4.0.0-rc.2] ion-slides loop is not working correctly

### ISSUE THREAD

**Issue by Manivannandurairaj** [ionic-team/ionic#17152]
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.2**

**Current behavior:**
Ion-Slides loop options is not working correctly. The second time loop options is struck for first image 

**Expected behavior:**
The loop options are working good

**Steps to reproduce:**
I integrated 4 slides with slideOptions with loop but the looping is not working correctly. If i disable loop property it is working fine,

**Related code:**

```
<ion-slides [options]="slideOpts">
    <ion-slide *ngFor="let slide of slides">
        <ion-img [src]="slide.image"></ion-img>
    </ion-slide>
</ion-slides>

 slideOpts = {
    autoplay: true,
    // loop: true,
    delay: 10000,
    speed: 300
  }
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (C:\Users\z022390\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

```

**Comment by paulstelzer** [comment]
Could you add a repo? Thanks!

**Comment by manucorporat** [comment]
It's unlikely we will find a fix for the feature, unless a PR is submitted or the root of the problem is pinpointed and the solution is easy.

`ion-slides` uses swiper under the hood, which was not the best idea. If you have problem with `ion-slides` using exotic configuration, I would suggest to use swiper directly (http://idangero.us/swiper/).

We will add a new modern and much smaller alternative very soon: https://github.com/ionic-team/ionic/pull/16958 

Feel free to reach me out to reopen the issue if you think a solution is trivial!
