### ISSUE TITLE
Ionic windows build high CPU usage

### ISSUE THREAD

**Issue by cristopherahsay** [ionic-team/ionic#17259]
Hello,
We are having performance issue in our ionic UWP app. After adding and successfully build the app in windows platform. We noticed that the app consume too much CPU just by moving the mouse around the application which performance issue. The app is too slow, hangs and completely unusable.

To investigate, we run the app on Visual Studio analyzer. The screenshot below is the result and as you’ll notice the build is adding DOM event named “pointermove” on very element on the app. It is also clear from the screenshot that this event causes high CPU performance.

How can we solve this? has any of you encounter the same problem? are there any solution?
![vs-report](https://user-images.githubusercontent.com/45188819/51731376-bb984a00-20b5-11e9-91e2-24bddd2692e8.png)

**Comment by manucorporat** [comment]
Without further code examples, and fulfilling the issue template we can't help.
Ionic does not use any pointermove event that I know. Are you using ion-slides?

**Comment by cristopherahsay** [comment]
No, we don't use ion slide. The pointermove is added all over our app. It is present in every html element.

**Comment by brandyscarney** [comment]
Please create a new issue and fill out the provided template if you are still running into this problem. We need to know which Ionic version you are using, where you are running it at, and a **minimal** amount of code and steps to reproduce the problem. If it's possible please use one of our starters and modify it to reproduce the problem so we know the problem is with Ionic. Unfortunately there isn't much we can do with a screenshot, we need to have steps to follow. Thank you! 🙂
