### ISSUE TITLE
Ionic 4: Action Sheet cssClass styles are not taking precedence

### ISSUE THREAD

**Issue by sukheja-varun** [ionic-team/ionic#17300]
# Bug Report

**Ionic version:**

Ionic cli
[x] **4.8.0**
@ionic/angular
[x] **4.0.0**

**Current behavior:**

Css class given to action sheet controller is not applied
Here is a image https://imagebin.ca/v/4VAY5ipacINn

**Expected behavior:**

It should successfully apply css class to action sheet modal
Here is a image https://imagebin.ca/v/4VAXiJ17wt4d

**Steps to reproduce:**

1. Use steps from docs to open a action sheet modal.
2. Create a class in your scss file, like the one below
```
.match-item-action-sheet{
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}
``` 
3. Now provide the css class name to cssClass attribute in options of action sheet controller as shown below
```
 const actionSheet = await this.actionSheetController.create({
      mode: 'md',
      cssClass: 'match-item-action-sheet red',
      buttons: [{ ...
      }]
    });
```
4. You can see your class is not applied to action sheet modal. 

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
Can you debug if the class is being applied or not in the DevTools? If you can share an screenshot, that helps

**Comment by sukheja-varun** [comment]
@manucorporat Here is the image https://imagebin.ca/v/4VAy11L0YXBI

**Comment by davayd** [comment]
same issue

**Comment by sukheja-varun** [comment]
Hi @brandyscarney,
I tried adding !important but it did not work for me.

**Comment by mntdragon** [comment]
> same issue:
> 
> 1. .ts file (class "**delete**")
>    ![screenshot at 2019-02-04 16-12-50](https://user-images.githubusercontent.com/17270614/52210354-de85e380-2897-11e9-9461-177fed8c1c8e.png)
> 2. .scss file
>    ![screenshot at 2019-02-04 16-12-24](https://user-images.githubusercontent.com/17270614/52210361-e47bc480-2897-11e9-9a46-7ca601ed586d.png)
> 3. DevTools
>    ![screenshot at 2019-02-04 16-11-23](https://user-images.githubusercontent.com/17270614/52210383-fbbab200-2897-11e9-9556-6491dd1a2b53.png)

you can add cssClass upper
```
 let actionSheet = this.actionsheetCtrl.create({
      title: 'XYXYXYX',
      cssClass: 'action-sheets-basic-page',
 buttons: [
        {
          text: 'Share',
          icon: 'share',
         cssClass: 'actionsheet-Share',
          handler: () => {
            console.log('Create clicked');
          }
}
```

scss

```
.action-sheets-basic-page {
  .ion-md-share, actionsheet-Shar {
    color: #ED4248;
  }
}
```

**Comment by mntdragon** [comment]
@sukheja-varun 

try this, I see it works when testing

```
 .action-sheet-md .action-sheet-group .button-inner {
            -webkit-box-pack: end;
            -webkit-justify-content: flex-end;
            -ms-flex-pack: end;
            justify-content: flex-end;
        }
```

**Comment by kyxiao** [comment]
把样式写在index.html的<style>里，就能识别了

**Comment by OnelifeOnelove** [comment]
![image](https://user-images.githubusercontent.com/22127597/69792399-84c52000-1201-11ea-91a3-235cbdf50812.png)
look at ion-router-outlet and ion-action-sheet, they are separate, so if you want your custom style works well,   you should put the style in global css file, not in your page scss file.

**Comment by hanibhat** [comment]
Write the following in your variables.scss:

```
.match-item-action-sheet {
  --color: red;
}
```

**Comment by ctfrancia** [comment]
any update? As this issue is persisting for me as well

**Comment by hanibhat** [comment]
@ctfrancia move all your .example css definitions to variables.scss instead. That works for me.

**Comment by ctfrancia** [comment]
@hanibhat  alright I'll give that a go, thanks!

**Comment by MT--** [comment]
I had classes like these in `app.scss` since they are to be used throughout the app (the mixins that I have defined here are working, but the classes do not); while moving them to `variables.scss` makes the classes work as intended, I'm not sure if I agree with placing them there for purely semantic reasons (they are not "variables").

**Comment by brandyscarney** [comment]
I've just reviewed this issue in its entirety. There are a few issues here which I'll go over, but overall this is a documentation issue.

### Targeting the wrong element

The below CSS from the main issue will never work as expected because the `.action-sheet-group` is what needs to be targeted. This is targeting the entire overlay:

```css
/* DOES NOT work */
.match-item-action-sheet {
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
}
```

So instead it would be this, which applies rounded borders only to the first group. The reason for `first-of-type` is because the cancel button is its own group and applying the border-top-*-radius to that group looks odd:

```css
.match-item-action-sheet .action-sheet-group:first-of-type {
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
}
```

![Screen Shot 2020-05-12 at 3 46 18 PM](https://user-images.githubusercontent.com/6577830/81739683-c244ff00-9469-11ea-8a73-ed2022808d6e.png)

### Adding the CSS in the wrong place

Steps

1. `ionic start myApp blank` (Angular)
1. Add a button that opens an Action Sheet with a css class passed: `cssClass: 'match-item-action-sheet',` in `home/home.page.ts`
1. Confirmed that the class was added on the Action Sheet in devtools:

    ![Screen Shot 2020-05-12 at 3 25 26 PM](https://user-images.githubusercontent.com/6577830/81739710-cec95780-9469-11ea-9e72-23a66c940bd6.png)


1. Observe that adding any CSS targeting it in the `home/home.page.scss` file does **NOT** show up in devtools:

    ```css
    .match-item-action-sheet .action-sheet-group:first-of-type {
      border-top-left-radius: 10px;
      border-top-right-radius: 10px;
    }
    ```

    ![Screen Shot 2020-05-12 at 3 44 18 PM](https://user-images.githubusercontent.com/6577830/81739750-dee13700-9469-11ea-8699-78bb7980f075.png)

    :warning: This is due to the fact that the `ion-action-sheet` element is attached to the `ion-app`, outside of the current page structure.  :warning:

1. Move the CSS to the end of the `global.scss` file, notice it is now showing up in devtools and applying properly:

    ![Screen Shot 2020-05-12 at 3 46 18 PM](https://user-images.githubusercontent.com/6577830/81739772-e6084500-9469-11ea-99d4-e29b15e90d0c.png)

    :warning: This is due to `global.scss` being added as a global stylesheet in the Angular config :warning:

    ```json
    "styles": [
      {
        "input": "src/theme/variables.scss"
      },
      {
        "input": "src/global.scss"
      }
    ],
    ```

### Using a lower CSS specificity

When using the CSS from this comment: https://github.com/ionic-team/ionic/issues/17300#issuecomment-575539790

```css
.example ion-icon {
  color: blue;
}
```

If you inspect in devtools you'll see that the CSS is there, but it isn't being applied:

![Screen Shot 2020-05-12 at 3 54 36 PM](https://user-images.githubusercontent.com/6577830/81739798-f1f40700-9469-11ea-9f03-13d08f682983.png)

This is because the Scoped CSS selector `.action-sheet-icon.sc-ion-action-sheet-md` has a higher precedence. In order to fix this, you can update it to the following:

```css
.example .action-sheet-icon {
  color: blue;
}
```

![Screen Shot 2020-05-12 at 3 56 36 PM](https://user-images.githubusercontent.com/6577830/81739819-fa4c4200-9469-11ea-9b3f-9cb7c0a61d1b.png)

Notice it now takes precedence. I recently updated our documentation to add a badge to scoped components, you can see it in the upper right on Action Sheet here: https://ionicframework.com/docs/api/action-sheet

This links to the following glossary item: https://ionicframework.com/docs/reference/glossary#scoped

Which includes more info on specificity: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

If you have any tips for improving our documentation on this, please let us know on the following repo: https://github.com/ionic-team/ionic-docs/issues

--------------------------------------------------------------------------------

Please let me know if I missed anything. Thanks!

**Comment by ctfrancia** [comment]
While I commented and has been an issue for a very long time and have since found a different way to kinda get around it, ultimately I had to create a separate action sheet for this, I think this speaks to a larger issue: docs. I feel like a majority of issues on here with ionic are due to docs. Every developer complains about it and every maintainer complains that no one reads them. If proper docs were to be written about plugins, prime example (for this the docs are awful for a reason probably in lieu of people purchasing the enterprise edition), then many issues could and would have been resolved.
In terms of wrappers for plugins, there is sparse documentation. In terms of APIs wording is often confusing and when there are pull requests for fixes within docs it sits there for ages. I have almost lost a job because of ionic and wasting many many many hours going into source code and finding discovering function/methods never discussed listed in the docs. I don't wish to make a big stink about it here, but, based on personal experience and how ionic is trying to diversify far too quickly(react/vue) before solidifying angular issues makes me never to recommend the company. I tried bringing this matter privately to other people within ionic, however, all were ignored or quickly dismissed. I really do hope that the issues plaguing the usage for ionic are resolved. Good luck

**Comment by brandyscarney** [comment]
Thanks for the feedback! As I stated at the beginning of my last comment, this issue is definitely a documentation issue. I get the frustration with the documentation, but saying "the docs are awful" is not something we can act on. The [ionic-docs](https://github.com/ionic-team/ionic-docs) repository I linked above is a perfect place to create actionable documentation issues that we can improve upon. 

After reviewing this issue I created my comment above to make sure I covered all of the use cases mentioned here and then added documentation [via this PR](https://github.com/ionic-team/ionic/pull/21283) to all of the scoped overlays to help clarify it. Reviewing the issue, commenting and adding the documentation took hours of my time, which is definitely important and needed to be done, but this takes away from time spent on bug fixes. This is why it's so helpful when a documentation issue is created that states "Angular's component level stylesheets don't work for overlays" as this is something that we can review and add documentation for. When issues are created here stating it's a bug we have to investigate it which is time consuming with so little of us and so many issues. This is why we often recommend asking support questions on the [Ionic Forums](http://forum.ionicframework.com/) as you are more likely to receive a faster response.

The plugin documentation is a community based effort, besides the enterprise plugins. We have outlined this in the Ionic Native docs [here](https://ionicframework.com/docs/native/community) and [here](https://ionicframework.com/docs/enterprise/community-vs-enterprise). Each one is maintained in its own repository. For example, [Analytics Firebase](https://ionicframework.com/docs/native/analytics-firebase) is located on [`appfeel`s GitHub](https://github.com/appfeel/analytics-google). While the usage on these is limited, the community plugins mostly serve as a listing to view the full documentation on their individual repositories.

> based on personal experience and how ionic is trying to diversify far too quickly(react/vue)

I know it seems like a lot of resources are going into React and Vue support, but because our core components are now web components — these integrations are simply bindings on top of the components. The entire time that the React integration was being worked on most of the framework team was working on including support for Angular 9 / Ivy and adding features and fixes to the core Ionic components (which Ionic React benefited from, but it was not done specifically for that integration). The important part here is that the core components & Angular have not suffered as a result of that work. It has always been our ultimate goal to expand framework support though.

> I tried bringing this matter privately to other people within ionic, however, all were ignored or quickly dismissed.

I'm not sure who it is you reached out to, and although I can't speak for them personally, I can say with confidence that it wasn't ignored or dismissed — at least not on purpose. Due to being a small company with a lot of moving parts, sometimes feedback falls through the cracks. I'll make sure the issue surrounding the plugins documentation is brought up with the rest of team again though and if you'd like to reach out to the team directly outside of GitHub you can email us at help at ionic dot io.
