### ISSUE TITLE
Ionic 4 <ion-back-button> issue

### ISSUE THREAD

**Issue by CraftingPanda** [ionic-team/ionic#17421]
**Ionic version:**

[x] **4.10.2**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
When I navigate back with an ion-back-button on a tabs template I always end up on the root page.
How do I solve this?

**Expected behavior:**
I expect it to navigate back to the site I was before and NOT to the root page.

**Steps to reproduce:**
 $ ionic start
Select the tabs template
$ ionic generate page [your page name here]
Add a ion-button to tab2
Add: (click)="go()" to the button.
Add: constructor(public router: Router){}
Add: import { Router } from '@angular/router';
Define go() in the TypeScript file like this: 
go() {
     this.router.navigate(['yourpagename'])
}
On the generated Page add in the toolbar an ion-back-button
$ ionic serve -l

**Related code:**

```
tab2.page.html:

<ion-button (click)="go()">Page 2</ion-button>
__________________________________________________________
tab2.page.ts:

import { Router } from '@angular/router';

constructor(private router:Router){}

go(){
  this.router.navigate(['page']);
}
__________________________________________________________

page.page.html:

<ion-header>
  <ion-toolbar>
    <ion-back-button></ion-back-button>
    <ion-title>Page</ion-title>
  </ion-toolbar>
</ion-header>



```

**Other information:**
The src folder of my App:
[src.zip](https://github.com/ionic-team/ionic/files/2841985/src.zip)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI) : 4.10.2

System:

   NodeJS : v10.15.0
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by 3alampro** [comment]
I'm having the same issues occur only with tabs pages but if I navigate from regular page into any page and hit the back button it work as expected the same page if I navigated from tab page and hit the back button i end up in the root page

**Comment by Caturix2199** [comment]
Same issue here. Also tried to update angular/router. Didn't change anything.

**Comment by sukheja-varun** [comment]
Can you try this 
```
<ion-buttons slot="start">
    <ion-back-button  defaultHref="/"></ion-back-button>
</ion-buttons>
```

**Comment by CraftingPanda** [comment]
@sukheja-varun it doesn‘t work
At defaultHref I tried many things:
/ 
/tab2
tab2
/tabs/tab2
tabs/tab2

Nothing works

**Comment by sukheja-varun** [comment]
Can you please check which ionic version is installed.
Use below command on your project terminal
`npm list @ionic/angular`

**Comment by kyleabens** [comment]
defaultHref only comes into play when you navigate directly to that page because it doesn't know the stack.

I'm also having this issue but I'm using ion-segment that changes based on url which I suppose is the same thing as tabs.  I have not found a solution yet.

**Comment by bossjon** [comment]
same issue [#15216](https://github.com/ionic-team/ionic/issues/15216) ?

**Comment by CraftingPanda** [comment]
@sukheja-varun I did the command and this was the output:

-- @ionic/angular@4.0.1

**Comment by 442623641** [comment]
same issue,I resolve this issue with `routerDirection` , eg:`<ion-button routerLink="/path/to/page" routerDirection="back"><ion-icon name="arrow-back"></ion-icon></ion-button>`

**Comment by kensodemann** [comment]
@442623641 - I have been being intentional about where I go back to, like this:

```
    <ion-buttons slot="start">
      <!-- <ion-back-button defaultHref="tabs/customers"></ion-back-button> -->
      <!-- see https://github.com/ionic-team/ionic/issues/15216 -->
      <ion-back-button
        defaultHref="tabs/customers"
        (click)="navController.navigateBack('tabs/customers')"
      ></ion-back-button>
    </ion-buttons>
```

Obviously, if the page is accessible from more than one parent, I would need to be a bit smarter about that, but doing so is a relatively trivial exercise.

**Comment by servrox** [comment]
@kensodemann When you navigating back like this, you will lose the state inside your tabs. This is because internally it navigates back to `/tabs` and then to the route specified in your `(click)` function. 

I also created a[ custom ionic component](https://www.npmjs.com/package/ion-back-button-tabs) to cover the _relatively trivial exercise_.

See my [solutions](https://github.com/servrox/demo-ionic-tabs-back-button#solutions-shown-in-demo) to navigate back without losing tab-states.

**Comment by zhiwo** [comment]
> same issue,I resolve this issue with `routerDirection` , eg:`<ion-button routerLink="/path/to/page" routerDirection="back"><ion-icon name="arrow-back"></ion-icon></ion-button>`

Child page repeatedly jump still can not return to the main page

**Comment by wkande** [comment]
<ion-back-button defaultHref=""  routerLink="/tabs/tab3"  routerDirection="back"></ion-back-button>

**Comment by Eraldo** [comment]
If I am coming from another page e.g. `SomePage` and then pushing a tabbed page "onto the stack" `this.navController.navigateForward('tabs/tab1')` and then click on the back button, I would expect to get back to `SomePage` however that is not what is happening at the moment. Instead I land at the tabs page instead of at the page where I came from.

If I use the browsers back button I do in fact get the desired behaviour (getting back to `SomePage`).

I guess this is because "back" first sends me back to the tabs page (on step back).
So the issue might be that navigating to `tabs/tab1` is actually creating 2 pushes onto the "back stack" instead of one?

I don't fully get it.

Sadly neither of the solutions above worked for me yet. (or I did something wrong)

Insights are welcome. ;)

**Comment by wkande** [comment]
Here is another idea using angular/common.

```
import { Location } from '@angular/common';


constructor(private router:ActivatedRoute, private modalController:ModalController,
    private events:Events, private _location:Location) { 
 }

myGoBackFunction(){
  this._location.back();
}
```

**Comment by liamdebeasi** [comment]
Hi there,

This issue has been resolved, and I have published a nightly build of Ionic with the fix. You can install it with `npm i @ionic/angular@dev`.

Please let me know if you are still running into any issues with this. 

Thanks!
