### ISSUE TITLE
@extend of globally declared class fails with selector not found

### ISSUE THREAD

**Issue by jperez1111** [ionic-team/ionic#17476]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

If I declare a class in global.scss as:
```
.sample-class {
...
}
```
and then try to extend that class in the style sheet of any page, e.g. und app/pages/sample.page.scss:
```
.page-sample-class {
  @extend .sample-class;
  ...
}
```
the compiler complains with:
> ".page-sample-class" failed to @extend ".sample-class".
> [ng] The selector ".sample-class" was not found.

So the selectors defined in global.scss can be used in a page's template, however they are not visible in a page's style sheet.

**Expected behavior:**

Selectors defined in global.scss should be accessible in other style sheets.
Note that in Ionic 3 extending selectors defined in app.scss is possible without any errors, so this bug is Ionic 4 specific.

**Steps to reproduce:**

See "Current behaviour" for instructions to reproduce the issue.

**Related code:**

```
See "Current behaviour" for sample code.
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.13.0
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 1 other plugins)

System:

   NodeJS : v8.11.3
   npm    : 6.7.0
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Ionic 3 had custom build tools that imported all of the page Sass files so that you could use the global Sass without having to import it in the pages. In Ionic 4 we are using Angular's build tools which is using their CLI to bundle the Sass. We have more information on this breaking change here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#including-sass

This isn't necessarily a bug with Ionic 4, but it is a change in how the Sass comes together. I would recommend creating some kind of app specific file that does not contain the Ionic imports, like we do in the Ionic Conference App here: https://github.com/ionic-team/ionic-conference-app/blob/master/src/app/app.scss

So add the following to the `app/app.scss` file:

```css
.sample-class {
  color: red;
}
```

and then in your page you will import it and extend it like below:

```scss
@import '../../app.scss';

.extended-class {
  @extend .sample-class;

  background: blue;
}
```

Please see this SO post: https://stackoverflow.com/questions/51480593/angular-2-extend-a-style-from-styles-scss

For future questions regarding how to style an application please refer to our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/). 🙂
