### ISSUE TITLE
Extra space is added above and below list

### ISSUE THREAD

**Issue by remisture** [ionic-team/ionic#17513]
# Bug Report

**Ionic version:**
[x] **4.0.1**

**Current behavior:**
Extra white space is added above and below `<ion-list />` in `md` mode.

**Expected behavior:**
No space is added, at least not with other color than specified.

**Related code:**
```
<ion-content color="dark">
	<ion-card color="light" margin>
		<ion-list color="light" inset lines="full">
			<ion-list-header color="light">
				<ion-label>Your account</ion-label>
			</ion-list-header>

			<ion-item routerLink="/start/tabs/account/signup" detail color="light">
				<ion-icon item-start name="person-add" slot="start"></ion-icon>
				<ion-label>Create account</ion-label>
			</ion-item>
			<ion-item routerLink="/start/tabs/account/login" detail color="light">
				<ion-icon item-start name="log-in" slot="start"></ion-icon>
				<ion-label>Log in</ion-label>
			</ion-item>
		</ion-list>
	</ion-card>
</ion-content>
```

**Other information:**

***md mode***

![md](https://user-images.githubusercontent.com/2372967/52899909-ef1b4f80-31ef-11e9-9a24-3b75cc2a7375.png)
***ios mode***

![iOS](https://user-images.githubusercontent.com/2372967/52899910-ef1b4f80-31ef-11e9-8004-a98b18c8b45a.png)

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/Users/remisture/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 12 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v10.15.0 (/Users/remisture/.nvm/versions/node/v10.15.0/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This may be a bit tricky to fix as the padding is necessary for the spec: https://material.io/design/components/lists.html#specs

So this rule is applying to list which gives it the white background only where the padding is:

```css
background: var(--ion-item-background,var(--ion-background-color,#fff));
```

If you're styling all of your lists and items this way you can get around this by using the global item CSS variable to theme all of them instead of `color`:

```
:root {
  --ion-item-background: #f4f5f8;
}
```

This could also be done at a page or content level. See this codepen: https://codepen.io/brandyscarney/pen/MLLWao?editors=1100

If you're only looking to style this one list, you can use a custom class and inherit the background for now:

```css
.custom-list {
  background: inherit;
}
```

We'll have to look into this more though, thanks!

**Comment by remisture** [comment]
Thanks for your workarounds 👍
