### ISSUE TITLE
ionic v4.0.2 --ion-item-background-activated not work 

### ISSUE THREAD

**Issue by microwin168** [ionic-team/ionic#17602]
When I only apply  `(click)` property  in `ion-item` , `--ion-item-background-activated` style is not work.  If I apply  with `[routerLink]` or `[href]` property , It works fine!
```
Ionic:
   ionic (Ionic CLI)             : 4.10.3 (/Users/microwin/.nvm/versions/node/v10.5.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.5.0 (/Users/microwin/.nvm/versions/node/v10.5.0/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! This is by design. If you want to apply a click handler, either by `(click)` or `addEventListener`, you need to add the `button` property to your `ion-item`. The reason for this decision is that there isn't a consistent/reliable way to detect click event handlers (since there are several ways to do it).

So your code should look like:

`<ion-item (click)="testFunction()" button></ion-item>`

Thanks for using Ionic!
