### ISSUE TITLE
React: Make components work without Shadow Dom

### ISSUE THREAD

**Issue by jthoms1** [ionic-team/ionic#17679]
Currently Ionic React only works in browsers that support Shadow Dom.  This issue is opened to track an update required to React components to ensure that the core components will work with non-shadow browsers.

**Comment by ebk46** [comment]
Any updates on this or an idea when this will be fixed? Or is there a workaround that we can use for now? Not supporting any Edge or IE browsers is a pretty big issue imo.

**Comment by ebk46** [comment]
I don't mean to spam this issue, but might we have a brief update on this? 8 months is a long time with no update on a pretty significant problem, especially now that ionic/react is "out" of beta; I'd like to at least know if this is likely to happen at all.

**Comment by myloc-ppl** [comment]
We are currently evaluating and maybe base our next mobile GUI on Ionic when we found this problem.

Some of our customers use Edge and IE and we really need to get an answer on this question. Please at least give us a hint on the time schedule when this can be fixed? (I just assume it is planned to be fixed since Edge and IE are on the compatibility list). 

/Thanks

**Comment by myloc-ppl** [comment]
Correction - IE is not on the compatibility list, only Edge, but still.

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the release of Ionic Framework v5 we updated our [Browser Support Table](https://ionicframework.com/docs/intro/browser-support#desktop-browsers) to state that Edge 79+ (Chromium Edge) is supported in Ionic Framework.

Chromium Edge has full support for custom elements, shadow DOM, etc so I am going to close this issue. If you run into any additional bugs, please feel free to create a new issue. Thanks!
