### ISSUE TITLE
Support for multiple messages for Toast

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic#17817]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Competing messages are displayed one on top of the other. This is very inconvenient.

**Describe Preferred Solution**
Add a new message underneath by pushing the previous message up. Each message has a duration until it disappears.

**Describe Alternatives**

**Related Code**

**Additional Context**
It can be done with a simple array that is displayed when it contains a message.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. Stacked toast notifications are not consistent with the Material Design spec (called "Snackbars" in this case) for showing multiple notifications: https://material.io/design/components/snackbars.html#behavior. We try to stay within the Material Design/iOS specs as much as possible in order to give users a "native" set of UI Components.

That being said, existing behavior for toast could possibly benefit from an update that only shows notifications one at a time (rather than overlaying) in order to bring it back in line with the spec. I will bring this up with the team.

Thanks for using Ionic!
