### ISSUE TITLE
--ion-toolbar-color and ios

### ISSUE THREAD

**Issue by kyawswarthwin** [ionic-team/ionic#17840]
```
  --ion-toolbar-color: #fff;
```

Android work
iOS did not work

ion-button and ion-back-button color did not change on ios

Adding this value work on ios. But i don't want to add. :D

```
  ion-toolbar {
    ion-button,
    ion-back-button {
      --color: #fff;
    }
  }
```

**Comment by tntwist** [comment]
+1. Having this issue in v4.1.1

**Comment by brandyscarney** [comment]
Thanks! I can confirm this issue: https://codepen.io/brandyscarney/pen/JzwZaQ?ionic:mode=ios

**Comment by topalavlad** [comment]
I gave this issue a go so that I could go through different style files around the ionic code and get more familiar with it. I mainly compared the `md` styles with the `ios` ones and found what was missing.

One thing I don't understand is why I was not able to import the `css` file with the path `href="toolbar.css"` and had to use `href="./preview/toolbar.css"`
