### ISSUE TITLE
Support safe-area-inset for normal content

### ISSUE THREAD

**Issue by rossholdway** [ionic-team/ionic#17848]
# Bug Report

**Ionic version:**

[x] **4.1.2**

**Current behavior:**
When viewing content on a device that uses the CSS env safe-area-inset-* such as the iPhone X, there is no support to contain general content within an element that applies `safe-area-inset-left` or `safe-area-inset-right` other than in specific items such as ion-item. Therefore content displayed in a landscape orentation on devices that use safe-area-inset is obscured.

**Expected behavior:**
I'd expect content to not be obscured behind device screen features such as the iPhone notch.

**Steps to reproduce:**
You can see this issue in the ionic-conference-app. Simply run the app in an emulator and rotate it's orentation to landscape. Some content is obscured.

![Screenshot 2019-03-21 at 15 14 15](https://user-images.githubusercontent.com/2728159/54762521-33817d00-4bec-11e9-962f-476a0d093d19.png)

**Other information:**
A possible fix could be to extend the grid to apply `safe-area-inset-left` and `safe-area-inset-right` by default.

I'd be happy to work though this and submit a pull request but would like to know community / your thoughts first! Thanks.

**Comment by rossholdway** [comment]
It'd be nice if something like this worked `--ion-grid-padding: 5px calc(5px + env(safe-area-inset-right)) 5px calc(5px + env(safe-area-inset-left));` or even expose as individual vars, setting the default to use safe-area-inset for left and right.

**Comment by daem0ndev** [comment]
Looked into this one, adding the safe area padding to the grid fixes the `Food` label, but the Breakfast and time/location are sibling h1 and p elements that dont get the padding since they are not in the ion-grid.

really the developer should be intentional about when and how they are compensating for safe area padding. e.g. simply adding the padding to content makes it hard for list items to properly fill the horizontal space as the padding should be inset to the child and not the parent.

that being said, adding a rule like this should be pretty safe and would correct the example markup in the ionic conference app: 

```
ion-content > [padding] {
  padding-left: calc(env(safe-area-inset-left) + 16px);
  padding-right: calc(env(safe-area-inset-right) + 16px);
}
```
