### ISSUE TITLE
[Ionic4] Disabled searchbar

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic#17921]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Hello,
Ionic 3 does not offer the possibility to disable an ion-searchbar, with ionic 4 it is still not possible.

But there was a technique to make it disabled in OnInit:
```
const ionSearchBarInputBox: any = this.searchBar.nativeElement.querySelector('input');
ionSearchBarInputBox.disabled = true;
```

Except with Ionic 4 this technique does not work anymore. The input element is not generated at the time of ngOnInit or ngAfterViewInit
You have to put these lines of code in a setTimeout of 500 for it to work. Which is not stable.

**Describe Preferred Solution**
The input should be disabled at the time of its generation

**Describe Alternatives**
It would be nice to have a disabled attribute as on other input to disable easily

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

Thanks!

**Comment by masimplo** [comment]
I would like to give this a go. @KyDenZ what do you think should be disabled when setting the disabled attribute to true? Of course the input, but there is also a cancel button that might be visible. Would you expect this to be disabled or not visible at all when there is text but the search bar becomes disabled? Same goes for clear button, which I am guessing is more straightforward since its visibility is not configurable as is the cancel button's.

**Comment by KyDenZ** [comment]
@masimplo it's a good reflection
 
I just tested by adding the attribute "showCancelButton" with a default value. The cancel button is not visible, which seems fine to me. If the field is disabled, we must not be able to change its content. Finally it's my point of view.

**Comment by masimplo** [comment]
Oh forks... I accidentally deleted my previous comment trying to edit it and cannot get it back :(
Anyway, yes I was mostly referring to the fact that the searchbar input is more complicated than other inputs since it has more than one components (i.e. clear and cancel) You are correct that cancel and clear buttons are not visible when the focus is lost, which is what happens if the input is disabled anyway, so there should be no issue there.

**Comment by AlekNiebla** [comment]
Hey can I take a look at this issue?

**Comment by KyDenZ** [comment]
The pull request has been sent
