### ISSUE TITLE
bug: ion-back-button direction icon is not correct in RTL in android 4.4

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#18047]
# Bug Report

**Ionic version:**

[x] **4.2.0**

**Current behavior:**

my app direction is rtl and back button position is top left in header then set arrow-forward(<-) to icon in ion-back-button.
in android 5 or above direction icon is correctly(<-).
but in android 4.4 direction icon is not correctly(->)

**Expected behavior:**

in all version android direction icon is <-.

**Steps to reproduce:**

**Related code:**

```
<ion-back-button defaultHref="home" icon="arrow-forward"></ion-back-button>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 15 other plugins)
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue. 

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.
