### ISSUE TITLE
bug: ion-icon not showing in ion-list-header

### ISSUE THREAD

**Issue by barocsi** [ionic-team/ionic#18064]
# Bug Report

**Ionic version:**

[x] **4.2.0**

**Current behavior:**
ion-icon not showing in ion-list-header
```        
<ion-list-header small class="cg-header">
<ion-icon name="pulse" slot="start"></ion-icon>
some stuff
</ion-list-header>
```

**Expected behavior:**
To be visible

**Comment by SherifMoShalaby** [comment]
as far as i know you cannot put ion-icon with property slot like you did it's not supported that way

you must wrap the ion-icon like

```
<ion-buttons slot="start">
        <ion-button>
             <ion-icon name="pulse" slot="icon-only"></ion-icon>
        </ion-button>
</ion-buttons>
```

any one corrects me if i`m wrong

**Comment by barocsi** [comment]
Actually it works on ion item but not on ion-list-header weird? Similar markup tho...
```
<ion-item >
           some text
            <ion-icon name="call" slot="start"></ion-icon>
            <ion-icon name="arrow-forward" slot="end"></ion-icon>
        </ion-item>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The item contains custom slots in order to position elements, you can see those in its API documentation here: https://ionicframework.com/docs/api/item#slots

List headers do not have any custom slots, so the element is not placed: https://ionicframework.com/docs/api/list-header

At the moment the following will work, but it will look a bit off in alignment:

```html
<ion-list>
  <ion-list-header>
    <ion-label>
      <ion-icon name="call"></ion-icon>
      List Header
    </ion-label>
  </ion-list-header>
</ion-list>
```

There's an issue open to align icons inside of labels here: https://github.com/ionic-team/ionic/issues/18033

I modified a Codepen to show this: https://codepen.io/brandyscarney/pen/PgQLYe

Is this what you're looking for?

**Comment by barocsi** [comment]
Yes indeed, however I think it should work just as ion-item. I do not understand the reason for different behavior that would require a hackish approach, since we are in the era of webcomponents.

**Comment by brandyscarney** [comment]
The reason for slots is to position elements inside of specific wrappers or add custom styles based on if the content is slotted. In the case of item, it behaves that way because item is set up to contain multiple wrappers around content and different ways to use it (with toggles, selects, datetimes, inputs, etc). The reason for the multiple wrappers is in order to match the different spec designs, mainly surrounding borders and margins. You can see that in the Material Design spec here: https://material.io/design/components/lists.html#anatomy

<img width="40%" align="left" src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1prXUCjUgB_6rLVjPP10Hmq43uu5uRD22%2Ftwo-line-example-2.png">
<img width="40%" src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Cdh8TPWcGTOeCpnCj40etdI3XiCF7g_x%2Fthreeline-sample-2.png">

Notice how in the examples above the items contain different elements and different borders (the first has no borders, the second has inset ones, there are other examples with full borders). In order for us to support all of the different use cases of items, we have to be able to position elements in certain places using slots in order to achieve those styles. 

List headers are more simple components. In the photos above they are the text that says:

- `4 items in your cart`
- `Summmer Recipes`

While I can understand the need to add icons to a list header, I don't think they need to be as complex as an item as then they end up becoming the same component. The issue I linked to needs to be fixed. The extra CSS provided is simply to vertically align the icon. 🙂

It would be helpful if you could provide an image of the design you are looking to achieve. I can add this as an issue that needs a design decision though. I am not aware of any list headers in native apps that have icons, so if you could send me any you know of that would be helpful too. Thank you! :smile:

**Comment by barocsi** [comment]
Thanks, but I have solved it with simple ion-item components.
