### ISSUE TITLE
feat: Get button color from the toast color

### ISSUE THREAD

**Issue by remisture** [ionic-team/ionic#18095]
# Feature Request

**Ionic version:**
[x] **4.3**

**Describe the Feature Request**
Instead of the toast button getting the primary color as default, I want the color to come from the toast color.

**Describe Preferred Solution**
Something like this:

```
.ion-color-success .toast-button {
   color: var(--ion-color-success-contrast, #fff)
}
```

**Describe Alternatives**
Or maybe the ToastButton interface can have a color property.

```
export interface ToastButton {
    text?: string;
    icon?: string;
    side?: 'start' | 'end';
    role?: 'cancel' | string;
    color?: Color;
    cssClass?: string | string[];
    handler?: () => boolean | void | Promise<boolean>;
}
```

**Additional Context**

<img width="389" alt="toast-button-problem" src="https://user-images.githubusercontent.com/2372967/56492406-06c2cd00-64ec-11e9-8a80-3469de4cfbc6.png">

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the request. Can you describe your use case a bit more? Why couldn't you just use the `--button-color` variable? https://github.com/ionic-team/ionic/blob/master/core/src/components/toast/toast.scss#L26

**Comment by cjorasch** [comment]
Auto setting the button color seems to be consistent with other Ionic components.  For example, toolbar buttons.  The text in the toast area already gets a color that depends on the color assigned to the toast (white or black to provide contrast with the background).

Setting css variables in a toast is a bit awkward because it is not nested within another component so you need to created a global css class and assign it to the toast.  This means that a component using the toast can not isolate its own css within the component.

**Comment by remisture** [comment]
@liamdebeasi, to be honest, I've completely missed the `--button-color` variable :hushed: - That being said, I still feel the framework should provide a smarter default color for button links.

**Comment by zakton5** [comment]
The `--button-color` variable is not working for me. It looks like there is some css that forces `--ion-color-primary` to remain active

**Comment by lkstnr** [comment]
@zakton5 I have the same issue. Can't seem to change the icon-color in my toast / toast-button. Did you solve it?

**Comment by zakton5** [comment]
@lkstnr Yep just fixed yesterday. This issue can be closed. @remisture

**Comment by brandyscarney** [comment]
Fixed by https://github.com/ionic-team/ionic/pull/18133, thank you!
