### ISSUE TITLE
feat: ion-datetime return format (YYYY-MM-DD)

### ISSUE THREAD

**Issue by skashanali** [ionic-team/ionic#18119]
Hi,
Is it possible to set the return (not the display or picker) format of ion-datetime?

I need the “YYYY-MM-DD” format, like “2019-04-24”.
By default, the component returns isoString like “2019-04-24T14:23:54.331+05:00”.

**Comment by ingljo** [comment]
It is easy to convert with for example [momentjs](https://momentjs.com/).
`moment(val).format('YYYY-MM-DD')`

**Comment by skashanali** [comment]
@ingljo I know this can be done by any third party library or simply using JS, that's why I'd opened it as a feature request to provide output-value-format just like display or picker format.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request! This is not something we are going to add to `ion-datetime` at the moment. Since the component outputs an ISO string, you should be able to do this formatting using JS Date methods such as `getFullYear` and `getMonth` (just be aware of some of the quirks with JS Date & timezones if you are trying to parse the time as well). 

The other option would be to use a library like momentjs or date-fns like @ingljo suggested. 

Thanks for using Ionic!

**Comment by skashanali** [comment]
Ok thanks.
