### ISSUE TITLE
bug: Extra information in console logs

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#18190]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Several components output information to the console during normal usage.

For example:
```
[ion-router] router will load
[ion-router] found nav
[ion-router] route changed [""]
Input: enableInputBlurring
Input: enableScrollPadding
[ion-router] nav changed -> update URL [{…}] ["x"]
Input: enableHideCaretOnScroll
Input: enableHideCaretOnScroll
input-base, pointerStart, type: touchstart
input-base, pointerEnd, type: touchend
native-input, hideCaret, shouldHideCaret: true, input value: x
native-input, hideCaret, shouldHideCaret: false, input value: x
```

**Expected behavior:**
Normal usage conditions should not output to the console unless specific logging is requested or configured.

Some issues with writing to the console:
- Extra logging information adds noise that makes it harder to see intended logging information
- Apps may be sending console output to cloud based loggers (like loggly) which results in lots of unneeded information being sent

If it is important to output detailed logging then it could be added as a config setting or a param to the component to specify logging is desired.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! This has been resolved via https://github.com/ionic-team/ionic/pull/18245 and will be included in the next Ionic release. I intentionally kept in some router debug logs since they have been helpful in the past for debugging.

A future Ionic update will introduce a setting that strips log/debug statements from production builds (allowing developers to keep debug statements in but not have it get shipped with every release). This is dependent on a Stencil change.

Thanks for using Ionic!
