### ISSUE TITLE
feat: toast html content

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#18204]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Current behavior:**
Currently, toast shows only plain text even if you pass an URL or image link.

**Expected behavior:**
Toast should show plain text, links and images properly.

**Describe Preferred Solution**

Allow strings including html in toast service.

**Describe Alternatives**

Allow providing a custom component to toast service (like modal service does).

**Related Code**

**Additional Context**

**Comment by jaipresto** [comment]
This would be good. I looked for a long time for something equivalent and compatible with Ionic/Angular. I settled on Popper.js (fantastic wrapper [here](https://www.npmjs.com/package/ngx-popper)), which is insanely flexible and very lightweight. But obviously native Ionic capability would be better.

**Comment by cjorasch** [comment]
There are lots of places where it would be useful for a property to have a JSX value so that it can handle complex content.  This includes alerts, pull to refresh, etc.  Some of these are currently handled as string html but that feels pretty awkward when working in JSX.  The simplest approach would seem to be typing the property as JSX but I think there are some use cases where a component is used from vanilla javascript that maybe prevents that approach.

Possibly use `JSX.Element | string` for the property and only complex content can be done in JSX?

JSX seems like it would simplify future component enhancements vs. constantly adding incremental properties of css values to change the displayed content.
