### ISSUE TITLE
feat: ion-item capabilities

### ISSUE THREAD

**Issue by iwantwin** [ionic-team/ionic#18210]
# Feature Request
Give ion-item more slots to handle more use cases.

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I want to handle click events on my ion-item's in an ion-list seperately from the ion-item click event (which, in my use case, is just toggling a checkbox, while my icon is supposed to give the user more options)

**Describe Preferred Solution**

I think the best way to do this is to create more slots so we can have an icon outside of the ion-item's clickable area.

**Describe Alternatives**

Perhaps there could be an extra property that enables the icon to have it's own click handler.

**Related Code**

My exact use case can be found here:
[CodePen](https://codepen.io/iwantwin/pen/eamemd)

Note that:
- i can toggle my checkbox by clicking on the item
- i want my console.log to fire when clicking on the 'more' ion-icon

**Additional Context**

Not applicable.

Possible related issue:
- https://github.com/ionic-team/ionic/issues/15627

**Comment by jaipresto** [comment]
I think that what you want to do can already be achieved. In the ion-item, put the ion-icon inside an _ion-button_ which has its own (click) method. If you're having trouble with multiple click events being fired, call [stopPropagation()](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) on the primary event.

Note that ion-items aren't clickable by default; they become so when you add a button attribute.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request. So what you are describing _should_ be possible, but there is a bug (https://github.com/ionic-team/ionic/issues/15850) that is preventing this from working properly.

I am going to close this issue since the functionality already exists, but feel free to follow the issue I linked to above as we are working on resolving that issue.

Thanks for using Ionic!
