### ISSUE TITLE
feat: Set color for <ion-select interface="alert" />

### ISSUE THREAD

**Issue by remisture** [ionic-team/ionic#18258]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I want the possibility to set the color of the checkboxes/radios in `<ion-select interface="alert" />`.

**Describe Preferred Solution**
```
<ion-select interface="alert" color="xxx">
    <ion-select-option>1</ion-select-option>
    <ion-select-option>2</ion-select-option>
    <ion-select-option>3</ion-select-option>
</ion-select>
```

**Describe Alternatives**
Or at least provide more css variables than just padding: https://ionicframework.com/docs/api/select#css-custom-properties

**Comment by brandyscarney** [comment]
Thanks for the issue! The select component itself is just the label that you see in an item: 

<img width="667" alt="Screen Shot 2019-05-13 at 11 14 18 AM" src="https://user-images.githubusercontent.com/6577830/57632768-47a08580-7570-11e9-84b1-2a2518420cc4.png">

Each interface uses the options of that component, so in the case of Alert it takes [these properties](https://ionicframework.com/docs/api/alert#properties) and [these CSS variables](https://ionicframework.com/docs/api/alert#css-custom-properties).

Because the Alert is a scoped component, the checkboxes/radios can actually be styled directly. For example, to change the checkbox icon background + border:

```
.custom-alert [aria-checked=true] .alert-checkbox-icon {
  background: pink !important;
  border-color: pink !important;
}
```

Here's a Codepen of this: https://codepen.io/brandyscarney/pen/oRzyJQ

There is an issue here for why `!important` or a more specific selector than Ionic uses is needed: https://github.com/ionic-team/ionic/issues/17425

**Comment by remisture** [comment]
Thank you, @brandyscarney, that solves my problem 👍
