### ISSUE TITLE
bug: ion-select multiple="true" not working properly

### ISSUE THREAD

**Issue by SherifMoShalaby** [ionic-team/ionic#18310]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Ion-selection with multiple="true" not working properly, you have to select the same chosen list 
twice to make it work.

**Expected behavior:**
should be working with no problems after selection whatever option i want.

**Steps to reproduce: please clone the git repo found below**

1. run the application
2. press the ion-select component and choose two or more, then press the ok button
3. the chosen items will not be reflected
3. you have to open the ion-select one more time and choose the same selection before then press the OK btn.

**Related code:**

https://github.com/SherifMoShalaby/IonicBugs.git

**Other information:**

I tracked the issue and found that the selectionEvent is called twice with two diff return values first time(first on is an array of strings, second is a comma separated string) !
when choosing the same selections before one more time the event only called on time

![IonicApp](https://user-images.githubusercontent.com/40992542/58011941-0114d300-7afc-11e9-9968-434eaa5a99b6.gif)
 

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\sshalaby\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by topalavlad** [comment]
@SherifMoShalaby I'm not sure this is a bug but either way, the documentation for `ion-select` is pretty bad. 

The problem is that in `ionChange` you're updating the `value` of the ion-select which then triggers another `ionChange` event with the stringified array so the first `ionChange` is triggered correctly with `['1', '2']` but another one is triggered with `['1,2']`.

Do you need `value="{{ionSelectChoosenList}}"` there? Without it, `ionChange` is triggered only once. The only reason I can see for using `value` is if you want to initialize the component with a selection but that doesn't seem to work anyway.

So, in your example `ionChange` works correctly without `value="{{ionSelectChoosenList}}"`, assuming you don't need it there.


@liamdebeasi do you know what the correct way of setting an initial value for `ion-select` would be?

**Comment by bunday** [comment]
Hello @SherifMoShalaby the problem here is because you are firing to events by having the 
`value="{{ ionSelectChoosenList }}"`  and also `(ionChange)="selectionChanged(ionSelectRef.value)"`.

 I will suggest you remove the `value="{{ ionSelectChoosenList }}"`  as you can easily have a two-way bind this way on your select input by simply having this `[(ngModel)]="ionSelectChoosenList"` and using the `ionChange` to handle your change event firing
