### ISSUE TITLE
feat: run ionic 4 components in ionic 3

### ISSUE THREAD

**Issue by jtushar53** [ionic-team/ionic#18320]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Ionic 4 components are made up of Stencil which helps Ionic components render individually as a web component, wish we can run Ionic 4 components in Ionic 3 or older projects, this can ease migration of large projects by replacing each components one by one.
I have 3 large projects with me which are very difficult to migrate.

**Describe Preferred Solution**

First preferred solution i can think of is to modify prefix of Ionic 4 components to avoid conflict.
 
**Describe Alternatives**

**Related Code**

**Additional Context**

this may be a naive feature request to ask for, sorry for that ;)

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the feature request! We definitely understand some of the frustrations with a big migration such as the migration from Ionic 3 to Ionic 4. However, updating Ionic 4 components to run in Ionic 3 applications is not something we are going to be doing at this time. This is mostly due to the technical considerations of that process. 

We offer a [migration guide](https://ionicframework.com/docs/building/migration), a [breaking changes list](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md), and a [migration linter](https://github.com/ionic-team/v4-migration-tslint) to help make the migration process easier. In particular, the linter should help address some of the more tedious syntax changes (such as changing `<button ion-button></button>` to `<ion-button></ion-button>`). That being said, we are absolutely open to feedback on how we can make this process easier!

Thanks for using Ionic!
