### ISSUE TITLE
feat: ion-toggle arbitrary hex color

### ISSUE THREAD

**Issue by jarrodkoch** [ionic-team/ionic#18416]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I would like to be able to provide a hex color value for ion-toggle.  Needing to know all possible colors ahead of time to create css variables is very limiting when one wants to allow the users of the application to select their own colors.

**Describe Preferred Solution**
The color property of ion-toggle could accept hex color values as well as the string variable names it currently accepts.

**Describe Alternatives**
A property separate from color which accepted hex color values would also be acceptable.

**Related Code**
N/A

**Additional Context**
In order to get around this we will have to create 66 css variables to hold all of the colors which we may need to set the toggle to.  It seems unnecessarily limiting for the control not to be able to accept hex color values as well.

**Comment by brandyscarney** [comment]
Thanks for the issue! CSS variables can be set via JavaScript: https://ionicframework.com/docs/theming/css-variables#variables-set-via-javascript

You could create your own CSS variables, or use the ones Ionic provides for toggle background:

```
const el = document.querySelector('ion-toggle');
el.style.setProperty('--background-checked', '#ff8866');
el.style.setProperty('--handle-background-checked', 'red');
```

Here's a Codepen example: https://codepen.io/brandyscarney/pen/Rmergq

Does this solve your problem?

**Comment by jarrodkoch** [comment]
Thanks for the reply.  The suggestion may not be a great workaround as we don't know how many toggles we're going to have when building the form because it's based on user data.  We could potentially have a couple hundred. We'd need to have the css variables pre-created and manage having each toggle having a unique variable name to be able to override its value, and also make sure nothing else uses those css variables so that the values aren't unexpectedly changed.

**Comment by brandyscarney** [comment]
So you wouldn't need to have any of the css variables pre-created, you can set css variables directly on an element like the following:

```
<ion-toggle style="--background: red">
```

The toggle will never inherit the `--background` of a parent element because it is set on the toggle itself, so there is no need to worry about it being overridden. This is actually very similar to how you would dynamically set the `color` based on user data. I've been writing the examples in vanilla JS as I'm not sure what framework you're using, but it can be changed to work with a framework as well. Here's an example with dynamic data:

```
const colors = [
  '#c1f0fb',
  '#f9ceee',
  '#e0cdff',
  '#dcf9a8',
  '#ffebaf'  
];

const list = document.querySelector('ion-list');

for (var i = 0; i < colors.length; i++) {
  const toggle = `
    <ion-toggle 
      checked 
      style="--background-checked: ${colors[i]}; --handle-background-checked: ${colors[i]}; ">
    </ion-toggle>
  `;
  
  list.innerHTML += toggle;
}
```

Here's a Codepen of that example: https://codepen.io/brandyscarney/pen/vwVwKw

The reason we don't allow hex values to be passed into the `color` property is because we need the different variations of a color (contrast, shade, etc.). We could take the hex value passed to color and do some calculations to find these variations, but you actually have more control by setting it directly via CSS variables.

**Comment by jarrodkoch** [comment]
Okay, thanks for the information.  I think we're going to try making a wrapper for ion-toggle for our use case that follows your codepen.  Closing the issue.
