### ISSUE TITLE
bug: platform shown as mobile when using a desktop with a touchscreen monitor

### ISSUE THREAD

**Issue by amkoehler** [ionic-team/ionic#18463]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
On windows laptop computers that have a touchscreen monitor, `platform.is('mobile')` returns true. 

**Expected behavior:**
`platform.is('mobile')` should be false in the situation described above

**Steps to reproduce:**
I am running an angular app on my thinkpad, which has a touchscreen monitor. In `platform.ts` the `isMobile` check is run by checking `window.matchMedia('(any-pointer:coarse)').matches`. On laptops with a touch screen, this `matchMedia` call returns true for its `matches` property. My best guess, based on reading the docs for `any-pointer`, is that the `matchMedia` returns true because my device is a touch screen.

**Related code:**

See https://github.com/ionic-team/ionic/blob/master/core/src/utils/platform.ts#L69

Demo (open console): https://stackblitz.com/edit/angular-klrn49

On laptops with a touchscreen monitor, this is logging `true` to the console

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! This is a known problem with the way we do platform detection. Unfortunately, in order to properly fix this we would have to introduce breaking changes. As a result, we will not be able to revamp this until the next major release of Ionic.

I am going to close this issue in favor of https://github.com/ionic-team/ionic/issues/17631, but feel free to post any follow up questions in that thread.

Thanks for using Ionic!

**Comment by amkoehler** [comment]
Ah, I missed that. Thanks Liam.
