### ISSUE TITLE
bug: no way to make ion-menu-button larger

### ISSUE THREAD

**Issue by liquidcms** [ionic-team/ionic#18667]
**Ionic version:**
[x] **4.x**

**Current behavior:**
The icon used in the ion-menu-button is set with a font size of 26px.

**Expected behavior**
There should be some way to style this (including making it bigger)

and in a similar vain, in general it should be possible to override the styling of any built in component. My guess will be that will end up as Ionic 5. :)

**Comment by brandyscarney** [comment]
Thanks for the issue! The fix for this in Ionic should be moving the `font-size` from `ion-icon` to the host in both `md` and `ios`:

```
:host {
  font-size: 24px;
}

ion-icon {

}
```

https://github.com/ionic-team/ionic/blob/master/core/src/components/menu-button/menu-button.md.scss#L19
https://github.com/ionic-team/ionic/blob/master/core/src/components/menu-button/menu-button.ios.scss#L27
