### ISSUE TITLE
bug: bug in side menu

### ISSUE THREAD

**Issue by clembou590** [ionic-team/ionic#18694]
ionic -v
5.2.1
node -v
v12.5.0
npm -v
6.9.2
cordova -v
9.0.0 (cordova-lib@9.0.1)

ionic start justTry sidemenu --type angular;
cd justTry;
npm install;
ionic cordova platform add android;
ionic cordova run android --prod;

The Menu in the bar is displayed as disabled, when tapping on the menu it shows very strange transparent things instead of a "normal side menu".
Please see screenshot

This issue is visible on ALL THE FOLLOWING DEVICES.
Tested in Android 6.0 (emulator only)
Tested in android 5.0 (emulator only)
Tested in android 4.4.4 (BOTH EMULATOR AND REAL DEVICE).

![Screen Shot 2019-07-02 at 16 52 26](https://user-images.githubusercontent.com/10899818/60523964-f8fba600-9ceb-11e9-9119-4203cc900699.png)
![Screen Shot 2019-07-02 at 16 52 44](https://user-images.githubusercontent.com/10899818/60523965-f9943c80-9ceb-11e9-908f-411499603dca.png)

The issue is not visible on an emulator with android 8.0

**Comment by clembou590** [comment]
Hello @liamdebeasi 
it s been 22 days the ionic side menu is broken... on almost 90% of the phones.
and around 95% of apps have a side menu...
Is fixing this is not high priority for you guys?

**Comment by liamdebeasi** [comment]
Hi there,

We are definitely still interested in fixing this issue. 

This issue only happens on older versions of the Android WebView. The webview autoupdates on Android 5.0+, so this issue should only happen on Android 4.4 devices. Android emulators cannot update their webview version which is why this issue appears to be happening on newer versions of Android as well. As a result, we do not recommend using the emulators for testing Ionic apps. 

We will look into a fix for this and will post here when there is an update. Thanks!

**Comment by clembou590** [comment]
@liamdebeasi thank you for answering. However as I said in the description the bug also appears with emular Android 6.0 . Are you telling me this bug would not appear on a real device with android 6.0  or android 5.0?

**Comment by liamdebeasi** [comment]
That's correct. The reason this bug is occurring is the emulator's webview is outdated and does not support some CSS/JS that Ionic uses. Newer versions of the webview do, and since physical Android devices have their webviews autoupdated, this issue should not appear on physical devices running Android 5.0+.

I would recommend doing as much of your testing on physical devices as you can, as that will give you more accurate results than testing on emulators.

**Comment by liamdebeasi** [comment]
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.
