### ISSUE TITLE
feat: Allow icon on ToastButton to allow resource paths and built-in icon names in toast component

### ISSUE THREAD

**Issue by jfspencer** [ionic-team/ionic#18968]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Allow the Ion Toast component to render SVGs inside declared buttons

**Describe Preferred Solution**
when adding a button to the Toast Component allow an `iconSrc` prop to pass in paths to assets (svgs, png, etc)

```
this.toastController.create({
      message,
      buttons: [
        {
          text: 'Some Button', 
          side: 'end',
          icon: 'a/path/to/svg',  <---------- permit pathed resource to be rendered
          handler: () => null
        }
      ]
})

```

**Related Code**
Created PR [here](https://github.com/ionic-team/ionic/pull/18969). This is my first PR, so may need some pointers on styles and making sure I updated the docs properly etc.

**Comment by brandyscarney** [comment]
Thank you for the issue and PR! So the `ion-icon` component actually has a property called `icon` that allows it to accept either a `src` or a `name`: https://github.com/ionic-team/ionicons/blob/master/src/components/icon/icon.tsx#L64

The fix for this should be changing this line: https://github.com/ionic-team/ionic/blob/master/core/src/components/toast/toast.tsx#L246

to

```
icon={b.icon}
```

Let me know if you have any questions!

**Comment by jfspencer** [comment]
@brandyscarney ah, awesome! should have looked more closely at the API, I'll get that updated, thanks!

**Comment by brandyscarney** [comment]
@jfspencer Thank you! I'm going to close this since it was fixed by your PR: https://github.com/ionic-team/ionic/pull/18969

It will be in the next release!
