### ISSUE TITLE
Getting Error only on prod build ionic 4

### ISSUE THREAD

**Issue by akshaykatale99** [ionic-team/ionic#19221]
getting this error only on prod build

ERROR in src\app\accounts\login\login.component.html(40,44): : Property 'forward' does not exist on type 'LoginComponent'.
src\app\accounts\register\register.component.html(96,49): : Property 'forward' does not exist on type 'RegisterComponent'.

Register Component file

<a [routerDirection]="forward" [routerLink]='registerUrl'>SIGN UP</a>

**Comment by ndrake** [comment]
Try removing the [] from around "routerDirection". The [] tells Angular to setup a binding for a property on your component classes.  When you build with --prod, the compiler fails with errors instead of warning (ignoring?) like the non-prod build does.

These types of issues are better asked on the [forum](https://forum.ionicframework.com/) or [Slack](https://ionicworldwide.herokuapp.com/).
