### ISSUE TITLE
feat: stop being inconsistent at the first place

### ISSUE THREAD

**Issue by barocsi** [ionic-team/ionic#19323]
there was first css
then you somehow figured out css attributes so everyone started using it for what? nonsense
and now we can rewrite our template base because its deprecated
congrats!
every release you put a lot of work on your peer developers
stop following fashion and build a strategy that avoids double work

**Comment by liamdebeasi** [comment]
Thanks for the feedback! Using CSS attributes causes type errors to be thrown in frameworks that use JSX and TypeScript. Rather than have developers use attributes in certain frameworks and classes in others, we opted to deprecate CSS attributes in favor of classes in order to create a more consistent development experience across frameworks.

**Comment by sahyun1** [comment]
I updated to 4.9.0 and see lots of deprecated warnings popping up.
Where's detail about this change?

**Comment by barocsi** [comment]
I also wonder when will ionic team realize that angulars flex layout is better than ion-grid and it was totally in vain to introduce that.

**Comment by liamdebeasi** [comment]
@sahyun1 The deprecation warnings should explain what is being deprecated and what you need to do to get rid of the warning. Additionally, you can find all deprecations in [CHANGELOG.md](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md).
