### ISSUE TITLE
bug: Support API level 29 (Android 10) 

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic#19429]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Ionic does not support Android 10

**Expected behavior:**

Support for it as it has been released since early September.

Depends on:
https://github.com/apache/cordova-android/issues/830

**Steps to reproduce:**

**Comment by jcesarmobile** [comment]
Ionic as framework supports Android 4.4+, that includes Android 10.

In terms of hybrid apps, both Cordova and capacitor target SDK 28, but that doesn’t mean they don’t support Android 10, apps compiled with SDK 28 work on android 10 devices.

**Comment by LifeIsStrange** [comment]
@jcesarmobile interesting!
That still means we can't use Android 10 new apis like e.g the new messenger like "bubble" api

**Comment by liamdebeasi** [comment]
Thanks for the issue. As @jcesarmobile said, Ionic Framework supports Android 4.4+. Compiling as a standalone app is something that is handled by Capacitor/Cordova.

If you find specific bugs in our components while running on Android 10, feel free to open a new issue. 

Thanks!

**Comment by LifeIsStrange** [comment]
@liamdebeasi sorry for spamming a little, but just to state the obvious:
Cordova has no paid developers, I guess you should use some of your developers to accelerate the fixing of major cordova issues like this one.

**Comment by jcesarmobile** [comment]
You can always use `<preference name="android-targetSdkVersion" value="29" />` on Cordova if you want to use latest SDK.

Not supporting SDK 29 by default is not a Cordova issue per se, the issues appear when SDK 29 requires code changes that are not done. But as far as I know, nobody have reported anything yet, so that's something you could do if you want to speed things up.
