### ISSUE TITLE
feat: Left-handed mode

### ISSUE THREAD

**Issue by Enteee** [ionic-team/ionic#19545]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
As a left handed user I would like to be able to switch all ionic components into left handed mode. Which means important UI-controls are moved from the right hand side of the screen to the left hand side, so that they are easy accessible when holding the phone on the left hand.

**Describe Preferred Solution**
The app should be able to toggle this (maybe by adding a class to `ion-content`) which then switches all `slot="start"` and `slot="end"` elements.

**Describe Alternatives**
[Forced use of the right hand](https://en.wikipedia.org/wiki/Bias_against_left-handed_people#Forced_use_of_the_right_hand)

**Comment by manucorporat** [comment]
Start and end is for RTL and LTR languages. Does the material-design or iOS design spec mention something about a left-mode? If they are not, it is unlikely we ever support this feature, but you can always code this in your app, and switch start/end

**Comment by Enteee** [comment]
Agree, a `start` and `end` - switch might not be the right approach for solving this. Also I search the two specs real quick and couldn't find anything about left-handedness. They seem to be happily ignoring 10% of the world's population...

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm also left-handed. 🙂 I don't think this is something we will add to Ionic though, since there are likely many different use cases where users may not want the sides to switch. I put together a Codepen example of what swapping some of the slots would look like:

https://codepen.io/brandyscarney/pen/BaaBggM?editors=1010

I personally would be thrown off by this switch, since I have gotten used to what buttons go where when using native apps, but everyone is different. I think this is something that should be handled on a per-app basis with user's feedback.

**Comment by Enteee** [comment]
@brandyscarney thank you for your example. I do like it. Due to it's simplicity i might actually just implement something similar in the app i am currently working on and then collect user feedback on it.

**Comment by liamdebeasi** [comment]
Thanks for the feature request! I am going to close this issue as we are not looking to implement this. Feel free to keep us updated on any user feedback regarding a left-handed mode 🙂.
