### ISSUE TITLE
ngIf on ion-menu -> no click event catched on content page

### ISSUE THREAD

**Issue by meriturva** [ionic-team/ionic#19677]
Here just a plunker to replicate the issue with ionic 4.11.1.

https://stackblitz.com/edit/ionic-v4-hide-fajnb6show-menu

As you can see there is just a timer where the side menu is removed or insert on-page.
On content page there is a simple button to click that produces a console log.

The issue is related when the timer hides menu when visible (after few seconds) you could test that button on content is not more clickable. After that effect, if you click on the side menu (when visible) you could start to see click console logs again.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I'm not sure I fully understand what the bug is. Can you clarify what I should be looking for?

If you are trying to programmatically disable/enable a menu, we recommend using the `enable` method on the menu controller rather than using an ngIf (see https://ionicframework.com/docs/api/menu-controller)

**Comment by meriturva** [comment]
Thanks, @liamdebeasi we have refactored our solution using just [MenuController](https://ionicframework.com/docs/api/menu-controller) and enable method.
It works like a charm!
