### ISSUE TITLE
bug: ion-input & setFocus() is not working in iOS 13.1.3

### ISSUE THREAD

**Issue by Livijn** [ionic-team/ionic#19699]
# Bug Report

**Ionic version:**
[@ionic/core] 4.11.1
[@ionic/vue] 0.0.9

**Current behavior:**
Using `setFocus()` is not setting focus on the input on my USB connected device in *iOS 13.1.3*. However it does work in the iPhone Simulator. Both in the native Safari browser and in my app. The Simulator is using *13.1* not *13.1.3*.

**Expected behavior:**
Using `setFocus()` should set focus on the input in *iOS 13.1.3*.

**Related code:**
This code is fired when clicking a button. The console logs the correct `<ion-input>` but the focus isn't getting set.

```
          setTimeout(() => {
            console.log(this.$refs.input);
            this.$refs.input.setFocus();
          }, 200);
```

I've also tried using `this.$refs.input.querySelector('input').focus()` and that doesn't work as well. I'm not sure if this is only related to ionic, but I can't seem to find any solution.

**Comment by sean118** [comment]
In case you didn’t figure it out yet: You can just remove the setTimeout and just fire `this.$refs.input.setFocus()` directly on click, which should work fine.

The actual underlying issue is somewhere in the webview implementation, that doesn’t allow pulling up the keyboard without direct user interaction - so its really an issue related to Capacitor/Cordova/WKWebView.

_For Capacitor the issue is probably right here, hidden in the `setKeyboardRequiresUserInteraction` function, but I also couldn't get it to work:_
_https://github.com/ionic-team/capacitor/blob/ab1ffd576d541c2423adf422b54d0b1b0483d00e/ios/Capacitor/Capacitor/CAPBridgeViewController.swift_

**Comment by Livijn** [comment]
This was a bug in Capacitor not Ionic. Also, @sean118, the bug is fixed in this commit: https://github.com/ionic-team/capacitor/pull/1995

**Comment by sean118** [comment]
Ah right, thanks, works perfectly 👍
