### ISSUE TITLE
bug: IonActionSheet uses non-standard cssClass instead of className

### ISSUE THREAD

**Issue by schontz** [ionic-team/ionic#19834]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Attempting to do: `<IonActionSheet ... className="dark" />` throws a TypeScript error:
```
Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<{ overlay?: HTMLIonActionSheetElement | undefined; el: HTMLDivElement; componentDidMount(): void; componentWillUnmount(): void; componentDidUpdate(prevProps: ActionSheetOptions & ReactOverlayProps): Promise<...>; ... 7 more ...; refs: { ...; }; }> & Readonly<...> & Read...'.  TS2322
```

**Expected behavior:**

The className `"dark"` should be added to my action sheet.

**Ionic info:**

```

Ionic:

   Ionic CLI       : 5.4.4 
   Ionic Framework : @ionic/react 4.11.3

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.11.0 
   npm    : 6.11.3
   OS     : macOS Mojave
```

**Comment by schontz** [comment]
If I open up Dev Tools and added the class name manually it behaves as desired.

**Comment by schontz** [comment]
I found `cssClass` in the docs. Any reason to use a different prop name than the rest of the components?

**Comment by elylucas** [comment]
Hi @schontz,

Yes, its a bit complicated, but using className doesn't work because there is no actual html rendered until the action sheet is shown. Once the isOpen is set to true, the ionic core components add the modal to the DOM, and then remove it when isOpen goes to false. The cssClass is used to pass any custom classes you want to the element.

It might be possible to just pass whatever is set in the className prop to cssClass, which would certainly avoid confusion like this. I'll investigate that some more and leave this issue open in the meantime.

Thanks!
