### ISSUE TITLE
bug: Switching between pages causing alot of rerenders

### ISSUE THREAD

**Issue by matis-dk** [ionic-team/ionic#19905]
# Bug Report

**@ionic/react-router version: 4.11.0**

**Current behavior:**
Switching between two pages causing alot of rerenders, which have negative impact on the performance for heavy projects, because of unnecessary work. Going from Tab1 to Tab3, is rendering a total of 10 times (6 times on Tab1, 4 times on Tab3). This is potentially really expensive and might degrade the ux if you switch quickly between pages. 

**Steps to reproduce:**

1. Start a Ionic React project with tabs as the 'Starter template'.
2. Add the following line for each page tab component before the return statement 
```
console.log("TAB [tab-number-here] ", Date.now())
```
3. Switch between the tabs.

**Comment by elylucas** [comment]
Hi @matis-dk,

You can cut down on a number of the renders by doing 2 things:

1) Memoize your tab component using React.memo. This essentially turns your functional component into a PureComponent that will only rerender on Prop/State changes. This cuts out a lot of the rerenders coming from parent changes.
```
export default React.memo(Tab1);
```

2) Change your Route to use the render prop instead of the component prop. When setting the component, you get the routing props passed into your component, which will cause a rerender even if you memoize because the location is changing. If you don't need the routing props in your component then you should be able to safely change your route to 

```
<Route path="/tab1" render={() => <Tab1 />} exact={true} />
```
On the tabs starter, these two techniques get the render down to only once per tab. However, do thorough testing on your app to make sure it doesn't break any and let me know if it does if you try it out.

We are looking into ways to cut down on the number of state changes that happen in IonReactRouter when a route changes, but these tips might help get you by.

Thanks
