### ISSUE TITLE
Could you remove shadow properties or set false for all the ionic core components?

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#19991]
Could you remove shadow properties or set false for all the ionic core components

**Comment by raphrmx** [comment]
+1

**Comment by liamdebeasi** [comment]
Thanks for the issue. Certain Ionic components were built with the Shadow DOM in mind, so disabling the Shadow DOM would break the current styling and interfere with component functionality.

We moved to the Shadow DOM for certain components because of the performance and encapsulation  improvements it brings. The Shadow DOM allows us to do things such as dynamically theme your app at runtime without having multiple CSS bundles. Having multiple bundles slowed down build times, startup times, etc. As of now, we do not currently have plans to disable the Shadow DOM on these components. Thanks!
