### ISSUE TITLE
bug: ion-nav do not run on iOS 10.3.3 

### ISSUE THREAD

**Issue by yupengfei** [ionic-team/ionic#20025]
# Bug Report

**Ionic version:**

[x] **4.9.1**

**Current behavior:**

ionic does not work on iOS 10.3.3 even with the starter project. 

**Expected behavior:**

It should show the demo page as android and PC.

**Steps to reproduce:**

1. npm init stencil
2. npm start --es5
3. open the page on iOS 10.3.3, it is blank

**Related code:**

**Other information:**

The error message is 

```
[Error] ReferenceError: Can't find private variable: @derivedConstructor
	(anonymous function) (ion-router.entry.js:138)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you trying to initialize a Stencil project, or are you using Ionic Framework? The steps you provided do not indicate any Ionic Framework usage.

**Comment by githubDiversity** [comment]
I can report the same issue on IOS 10.3.4 running safari.

In my case I have created an pwa using stencil with the ionic-pwa default template
then i am using:
 stencil build --dev --es5 --watch --serve
in safari I browse to the resulting webserver and then the error emerges.

**Comment by liamdebeasi** [comment]
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.
