### ISSUE TITLE
bug: ion-toolbar shows border

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic#20073]
# Bug Report

**Ionic version:**

[x] **4.11.6** 

**Current behavior:**

ion-toolbar shows small Black Border on iOS

**Expected behavior:**

With:
```
ion-toolbar {
    --border-width: 0;
}
```
there should be no Border

**Steps to reproduce:**

CSS:
```
 ion-toolbar {
    --border-width: 0;
}
```
HTML:

```
<ion-header>
<ion-toolbar>

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is happening because our styles to target the border are more specific than the styles you are writing.

Example: https://codepen.io/liamdebeasi/pen/MWYjaLB?ionic:mode=ios

Notice that the border is still there. If you uncomment the more specific style, the border disappears. We are aware of some difficulties overriding scoped component styles and have been working to resolve them: https://github.com/ionic-team/ionic/issues/17425

Additionally, if you want to remove the border you can add the `no-border` attribute to `ion-header`. Please note that this will be changed to the `ion-no-border` class in the next major release of Ionic Framework.
