### ISSUE TITLE
bug: IonRouterOutlet renders routes even if the path doesn't match

### ISSUE THREAD

**Issue by gdrbyKo1** [ionic-team/ionic#20093]
# Bug Report

**Ionic version:**

[x] **4.11.7**

**Current behavior:**

If you navigate to a path which matches a Route, and the Route returns a redirect to a different path, the Route will keep getting re-rendered in the future, even though the new (redirected-to) path doesn't match the Route's path.

**Expected behavior:**

A Route should only render if the current path matches the Route.

**Steps to reproduce:**

1. Start an Ionic app using the `blank` template, and choose React for the framework.
2. Replace the `App` function in `App.tsx` with the following:
```
const App: React.FC = () => {
  const [foo, setFoo] = useState(false);

  useEffect(() => {
    const timeout = setTimeout(() => {
      console.log("setFoo()");
      setFoo(true);
    }, 2500);
    return () => clearTimeout(timeout);
  }, []);

  const TakeMeHomeRouteComponent: React.FC = () => {
    console.log('App /take_me_home route handler. Redirecting to /home');
    return <Redirect to="/home" />
  }

  const HomeRouteComponent: React.FC = () => {
    console.log('App /home route handler. Returning Home component');
    return <Home />
  }

  return <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/home" component={HomeRouteComponent} exact />
        <Route exact path="/take_me_home" component={TakeMeHomeRouteComponent} />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
};
```
3. Start the app with `npx ionic serve`
4. Open http://localhost:8100/home in your web browser, and notice that the `TakeMeHomeRouteComponent` function is not called, as the path doesn't match
5. Now navigate to `/take_me_home`, and notice how the `TakeMeHomeRouteComponent` function gets executed when the `App` component is rerendered (caused by the registered timeout) even after the redirect has already taken place and the current browser's path doesn't match the Route's path anymore.

**Other information:**
Also notice how the path you navigate to within your browser changes the App's behavior. If you visit `/home` and wait until the timeout fires, you will witness an animation from the Home component into another, identical, Home component.
But if you visit `/take_me_home` instead, and wait for the timeout to fire, you will see that the Home component disappears completely and the whole App becomes an empty page. If you take a look in your browser's Dev Tools, you'll see that in fact the Home component is still there and rendered, only it gets an additional `ion-page-invisible` class, which applies an `opacity: 0;` CSS rule to it.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (C:\Users\gdrbyko1\AppData\Roaming\npm-cache\_npx\8256\node_modules\ionic)
   Ionic Framework : @ionic/react 4.11.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.1
   OS     : Windows 10
```

**Comment by elylucas** [comment]
Hi @gdrbyKo1,

There is an issue with your code above, and thats the HomeRouteComponent and the TakeMeHomeRouteComponent are defined in the App functional component, so every time the App renders these components will be redefined, which is whats causing them to be unmounted/mounted, and thus, re-rendered again. 

If you move the definitions of HomeRouteComponent and TakeMeHomeRouteComponent outside of App, then the re-render issue here will go away.

However, keeping some routes/views around even when the path for them doesn't currently match is by design and required for IonReactRouter. We do this to provide the page transitions, as well as to maintain the state between views when it is possible to go back to them. Because of this, you might need to safeguard when you are doing actions like this in a component. In this cause, you could probably provide a path to the redirect so that it will only redirect when on the /take_me_home route.

Hope this helps, let me know if you have any questions.
