### ISSUE TITLE
bug: Mobile browser on scroll status bar not hidden. A 4 years old BUG!!

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#20204]
Hi, 
It's the second time I asked it.
You say in your website that with Ionic you can have a mobile website and an app with the same code but you lied!
I spent months to develop my app+website and now the website really sucks, the problem is this: https://github.com/ionic-team/ionic/issues/19081 and people asked about it 4 years ago.
With angular there is no problems, on Ionic yes. 
Please if you can't fix it give me a work around because my website now seems an old fashion one and it's not really good. Here if you want to try it: https://roomlessrent.com

**Comment by liamdebeasi** [comment]
Thanks for the issue. As stated in the bug report you linked to, we are not scrolling on the `body` element which is why you are experiencing this behavior. Safari listens for scrolling on the `body` element in order to know when to collapse/show the address bar.

The issue you linked to provides a temporary workaround that you can use while we investigate alternatives. I am going to close this issue in favor of the one you linked to. Thanks!
