### ISSUE TITLE
bug: platform.is('tablet') returns true when running on an android phone device.

### ISSUE THREAD

**Issue by davidperis92** [ionic-team/ionic#20200]
# Bug Report

**Ionic version:**
[x] **4.11.8**

**Current behavior:**
```platfrom.is('tablet')``` returns true when running on an android phone device

**Expected behavior:**
It should return true only when is runt on a tablet device.

**Steps to reproduce:**
Run an app that uses platform.is('tablet') on an android phone and watch the returned value of the function.

**Related code:**
File in github repository:
core/src/utils/platform.ts

```
const isAndroidTablet = (win: Window) => {
  return isAndroid(win) && !testUserAgent(win, /mobile/i);
};

const isMobile = (win: Window) =>
  matchMedia(win, '(any-pointer:coarse)');
```
If we look at this functions we can see that the "mobile" condition is checked in two different ways (with matchMedia and testUserAgent). When I run the app on a Mi phone device it returns true for `platform.is('tablet')` because `testUserAgent(win, /mobile/i)` returns false.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this in favor of https://github.com/ionic-team/ionic/issues/19737.

Due to inconsistencies between platforms and across devices, it is not easy to achieve a 100% success rate with platform detection. For example Android phones typically have `mobile` in their user agent string; however, a small number of Android phones do not. 

We have opted instead to allow developers to override our platform detection methods with other methods that better suit an application's use case.
