### ISSUE TITLE
bug: [ios + v5] Ionic 5 ion-list-header with button: wrong alignment

### ISSUE THREAD

**Issue by cmaas** [ionic-team/ionic#20284]
# Bug Report

**Ionic version:**
[x] **5.0.0-RC0**

**Current behavior:**
`ion-list-header` with an `ion-button` doesn't align the button to the right side of the screen. I also couldn't figure out on how to override this at all. Tried float and flexbox magic, inline styles, important, nothing worked.

<img width="367" alt="now" src="https://user-images.githubusercontent.com/6094364/73062081-d4d80000-3e9b-11ea-8059-24402f7dd290.png">

**Expected behavior:**
Before: `ion-button` within `ion-list-header` was aligned to the right by default. Should be aligned to the right again.

<img width="371" alt="before" src="https://user-images.githubusercontent.com/6094364/73062091-da354a80-3e9b-11ea-9f1b-b04fafd411a3.png">

Couldn't find good examples from Apple's own apps. But the app store shows "Today" on the left side and the profile pic/button on the right side.

**Steps to reproduce:**
```
<ion-list-header>
  Address
  <ion-button fill="outline" size="small">Edit</ion-button>
</ion-list-header>
```

Note: When inspecting `ion-list-header`, it seems that `justify-content: space-between` is already set. I have no clue why it doesn't work at all.

**Comment by cmaas** [comment]
One more thing: This isn't iOS-only, it's also under Android/Material. `ion-button` can't be aligned to the right in `ion-list-header`.

**Comment by brandyscarney** [comment]
Thank you for the issue! List header actually needs the text content to be wrapped in a label now (like item). I can't remember if the [usage](https://ionicframework.com/docs/api/list-header#usage) has shown a label since v4 or if I updated it, but I can add a note about this to the breaking changes. Here's a Codepen showing the code: https://codepen.io/brandyscarney/pen/vYEPyNm?editors=1010

Please keep this issue open, I will close it when breaking changes are updated. 🙂
