### ISSUE TITLE
bug: Ion Item ripple effect and color is not working

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20351]
**Code:**
```
<ion-item mode="md" >
  <span>Test</span>
</ion-item> 
```

**SCSS**
```
 ion-item
  {
    --ripple-color:red;
  }
```

**Ionic Info**

   Ionic CLI                     : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

**Comment by brandyscarney** [comment]
An item needs to be clickable in order to have a ripple. This can be achieved by either adding the `button` attribute or the `href` attribute. See more information on this here: https://ionicframework.com/docs/api/item#clickable-items

I am not able to reproduce this with the `button` attribute added: https://codepen.io/brandyscarney/pen/yLydQGB

Please provide more code to reproduce if you are still seeing this after making it clickable, thanks!

**Comment by rajiramamoorthi** [comment]
Thank you for your reply. It is working with button attribute.
