### ISSUE TITLE
bug: IONIC 5 ionSelect event is not working and checked property can't bind a value

### ISSUE THREAD

**Issue by Manivannandurairaj** [ionic-team/ionic#20382]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
ionSelect event is not triggered and checked not working property binding

**Expected behavior:**

ionSelect event must be triggered and checked property is binding a value like [checked]="isChecked"

**Steps to reproduce:**

Implement ion-segement button in ion-segement below i shared my code

**Related code:**

```
<ion-segment [value]="segValue">
        <ion-segment-button layout="icon-start" *ngFor="let tab of tabList" [value]="tab.value"
            (ionSelect)="onSelectChanged($event)" [checked]="tab.checked">
            <ion-label>{{tab.name}}</ion-label>
            <ion-icon [color]="tab.color" *ngIf="tab.icon" [name]="tab.icon"></ion-icon>
        </ion-segment-button>
    </ion-segment>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15 (C:\Users\z022390\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.0-rc.2
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.3.24
   @angular/cli                  : 8.3.24
   @ionic/angular-toolkit        : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.3
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. As of Ionic 5, `ion-segment` has been updated. Two notable changes:

1. The `checked` property has been removed from `ion-segment-button`. You should set a value on the `ion-segment-button` and then the same value on `ion-segment` in order to select a segment button.

2. The `ionSelect` event has been removed. Developers should listen for `ionChange` instead. It looks like this is missing from the breaking changes doc, so I will be sure to add that. 

Please see https://github.com/ionic-team/ionic/blob/master/BREAKING.md#segment for more information.
