### ISSUE TITLE
feat:  Hooks in Firebase push notification system to perform message translation

### ISSUE THREAD

**Issue by rlcomte** [ionic-team/ionic#20623]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
We want to push notification messages to our app users, but translate these messages into the user's language. Actually we want to do more than only translation, it is applying all i18n capabilities in translating and formatting the message, including number and currency display.

**Describe Preferred Solution**
A standard hook into the Firebase Push Notification System (on Android it would probably be a derived class of the FirebaseMessagingService), that intercepts messages and calls a registered application hook function to perform manipulation of the message.

**Describe Alternatives**
Translation on the backend: it seems not the right place to put the responsibility of translation at the backend. And the complexity of doing full i18n would require access to the user's regional settings which is hard for a backend system.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I think a hook for Firebase is something better handled on a per application basis as not every Ionic user is going to be using Firebase. Additionally, the requirements for these notification hooks would likely be very specific to each use case.

It sounds like you want to do localization on the native level in which case the solution for this is likely not going to come from Ionic Framework, but rather one of the Cordova/Capacitor plugins that handles push notifications. I am going to close this issue, but you might also want to check out the Firebase Cloud Messaging documentation since they seem to provide some information regarding localization: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
