### ISSUE TITLE
bug: ion-button - overflow is overriden with hidden

### ISSUE THREAD

**Issue by svoelz** [ionic-team/ionic#20726]
I tried to set the --overflow to visible and it doesn't work in Ionic 5.

I checked the https://github.com/ionic-team/ionic/blob/master/core/src/components/button/button.scss
and the overflow is override with hidden at line 187. 
The value --overflow (which was set on line 185) does not work anymore.

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you provide all of the CSS you are applying or the design you're going for?

I can remove the extra `overflow: hidden` that was added. This was due to the changes for the button states in v5: https://github.com/ionic-team/ionic/blob/master/BREAKING.md#activated-focused-hover-states

However, setting this to `"visible"` will break the ripple effect and hover/focused states, so I want to make sure I understand your use case. It won't be noticeable on buttons that have the same font color as the content, but you can see it on a button with a different font & rounded corners the most:

<img width="116" alt="Screen Shot 2020-03-10 at 11 45 09 AM" src="https://user-images.githubusercontent.com/6577830/76331038-f747a080-62c4-11ea-9bbf-9029a06694c4.png">

**Comment by svoelz** [comment]
Thanks for the update.
I have a button without text (only an icon). In the upper right corner of the button appears a text element. The button is rather a “new message received” button. The text element should also be clickable. I fixed it temporarily by changing the width of the button and add some padding. 
The --overflow:visible shouldn't conflict with the ripple effect, here. The overflow: hidden results in a bad hover / click effect, because the background color appears in the background of the text element. 
It might be better to use the overlfow: visible option in this case.
