### ISSUE TITLE
feat: Attribute to disable validation underline on an input with ngModel validation and custom css property

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20739]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
In Ionic Angular, when you add a `<ion-input>` with the attribute `[(ngModel)]` it enables the validation underline. It causes the `bottom border color` of the input to change from `primary` (blue)  to `success` (green).

I would like an attribute on `<ion-input>` like `disableValidation` to get rid of the bottom border color changes and stays primary, I just want to use ngModel but the validation color doesn't make sense in my use case.

Maybe it would be nice to also have a custom css property to custom the color on a specified input (instead of changing the primary, success, etc color variables). So it would be possible to set color to transparent

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is already possible in Ionic Framework. In order to get this validation underline, your input needs to be inside of an `ion-item`. You can use the `--highlight-height` variable to disable the underline. You can also use the other highlight variables to change the border color.

Please see the docs for more information: https://ionicframework.com/docs/api/item#input-highlight
