### ISSUE TITLE
What feature make ionic5 don't support ios 10.

### ISSUE THREAD

**Issue by wangcode** [ionic-team/ionic#20915]
What feature make ionic5 don't support ios 10.
I need support ios 10+ but ionic4 has so match bug, like toggle tab and goBackButton wrong,
toggle page ion-title make flash.
sorry my terrible english.

**Comment by liamdebeasi** [comment]
Thanks for the issue. With Ionic Framework v5 we dropped support for iOS 10 for two main reasons:

1. It lacks support for certain Web APIs that the framework relies upon to provide a good user experience. Additionally, there are a few known bugs with its implementation of certain Web features that have been fixed in later versions.
2. Its usage among iOS devices is very low. See: https://developer.apple.com/support/app-store/

Hope this clears things up. Thanks!
