### ISSUE TITLE
feat: clear button for ion-select for multiple

### ISSUE THREAD

**Issue by mrSingh007** [ionic-team/ionic#20998]
It would be nice for have select and/or clear all button on multi select. 
I found one old ticket https://github.com/ionic-team/ionic/issues/12366 which also address this feature.

Current Version : 5.4.15 does not have this feature

Thanks

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you provide your use case for how you would use this feature?

**Comment by indraraj26** [comment]
You dont have to open again ion-select to unselect one by one (which one you dont want).

But clear icon cant be added in ion-select like we have in searchbar.

It would be great to have in ion-select popup, when you use ion-select as a multiple select. first item will be select all/unselect all.

**Comment by NikolaPeevski** [comment]
Alternatively you can wrap the ion-icon inside a div and make a custom button/use ion button with icon only and strip the rest with CSS

**Comment by liamdebeasi** [comment]
Thanks for the feature request. After discussing this with the team, we have decided not to add this. `ion-select` is intended for simple list selection. If there is a need for a select all/none button because there are many select options, we recommend using a modal instead. Using a modal allows for more customization such as select all/none and searching. Thanks!
