### ISSUE TITLE
Can't see popover arrow in dark mode(Chrome and Safari)

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#21021]
As it is visible from my screenshot, I am viewing my app on localhost on Safari and I'm facing this issue on Chrome too. 

Upon close inspection, I realized that the arrow exists but is not visible because it blends with the background. Is there a way to make the entire popover the same color

Here's the repo: https://github.com/assman/ticket-ionic

<img width="414" alt="Screen Shot 2020-04-12 at 9 35 51 PM" src="https://user-images.githubusercontent.com/14093665/79070108-0c6d8000-7d06-11ea-820e-9e71522af37a.png">

**Comment by NikolaPeevski** [comment]
Which arrow is not visible again? It seems the same with light/dark mode in Chrome.

**Comment by assman** [comment]
![Screen Shot 2020-04-13 at 10 03 20 AM](https://user-images.githubusercontent.com/14093665/79086322-36f32380-7d6e-11ea-92d5-35938912d68b.png)

The one shown in this screenshot

**Comment by NikolaPeevski** [comment]
@assman Add the following to your global scss

```
@media (prefers-color-scheme: dark) {
  .popover-arrow.sc-ion-popover-ios:after {
    background: var(--ion-item-background,var(--ion-background-color,#fff)) !important;
  }
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. In order to change the color of the background/popover arrow, you need to set the `--background` CSS variable on `ion-popover`. You may, however, run into a scenario where your variable is being overridden (https://github.com/ionic-team/ionic/issues/17425), in which case you will need to use `!important`.
