### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by pengcl** [ionic-team/ionic#21083]
# Bug Report

**Ionic version:**

[x] **5.0.4**

**Current behavior:**

ion-header and ion-footer has wrong position when i typing in ion-textarea,it's just happened on when ion-textarea overflow the ion-footer.

by the why it's just happened on ios `app`
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by pengcl** [comment]
this is my repo https://github.com/pengcl/ionic-house
please click middle button on tabs

**Comment by pengcl** [comment]
![avatar](http://wisp.ai-fox.net/WechatIMG3509.jpeg)

**Comment by liamdebeasi** [comment]
Can you please provide the repo with the minimum code required to reproduce the issue? This repo is quite large which will make debugging difficult.

**Comment by pengcl** [comment]
![17841587396535_ pic_hd](https://user-images.githubusercontent.com/11203323/79770143-97cabf00-835f-11ea-88e3-cdb17fa158ba.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the screenshot; however, I am unable to navigate to that page due to the login screen. Can you please provide the repo with the minimum code required to reproduce the issue?

**Comment by pengcl** [comment]
13800138000
123456

**Comment by liamdebeasi** [comment]
Thanks for the follow up. It looks like the screenshots are showing a Cordova/Capacitor application. I am unable to run your application in Cordova due to an error thrown by the QR Scanner plugin your app uses.

Like I mentioned in my previous comment, it is going to be difficult for me to run/debug this app unless I can get a reproduction with the minimum code required to reproduce the issue. I am not going to debug your entire application for you.

**Comment by pengcl** [comment]
https://github.com/pengcl/house-debug

i make minimum code it's reappear the problem

**Comment by liamdebeasi** [comment]
Thank you! I will take a look.

**Comment by liamdebeasi** [comment]
@pengcl Did you push your code? I just see a blank Ionic starter application.

**Comment by pengcl** [comment]
yes i am sure

**Comment by liamdebeasi** [comment]
I don't see any ion-textarea in your application. Can you check your commits to ensure you have added the code I need to reproduce the issue? https://github.com/pengcl/house-debug/commits/master

**Comment by pengcl** [comment]
sorry ,you can see now,i re- pushed

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am still unable to reproduce the issue. This is what I see on my iPhone 11 (iOS 13.4):

![IMG_6994](https://user-images.githubusercontent.com/2721089/79792391-cd9a8400-831c-11ea-9a37-8f990d2bfa19.PNG)

Can you provide some steps to reproduce the issue?

**Comment by pengcl** [comment]
[1587412479791500.mp4.zip](https://github.com/ionic-team/ionic/files/4505831/1587412479791500.mp4.zip)
here is a vedio

**Comment by pengcl** [comment]
[1587412703392272.mp4.zip](https://github.com/ionic-team/ionic/files/4505847/1587412703392272.mp4.zip)
it's easy to reappear

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I was able to reproduce the issue. This appears to be a platform quirk and not a bug in Ionic Framework.

I recommend looking at the alternative resize modes available in the keyboard plugin as those may help: https://github.com/ionic-team/cordova-plugin-ionic-keyboard#keyboardresizemode-for-ios-only

Additionally, I recommend looking into using Capacitor instead of Cordova: https://capacitor.ionicframework.com/

The issue seems to be resolved using the `"ionic"` keyboard resize mode in Capacitor. Thanks!

**Comment by pengcl** [comment]
when i using Capacitor, this problem **_`Still Exists`_**
