### ISSUE TITLE
bug: Swipe to close Modal

### ISSUE THREAD

**Issue by ishaiavrahami** [ionic-team/ionic#21100]
# Bug Report

**Ionic version:**
Ioinc latest CDN (5.0.7)

**Current behavior:**
Swipe to close modal only works when there ISNT <ion-content>.

**Expected behavior:**
Swipe to close modal should work when <ion-content> is wrapping the content of page. 

**Steps to reproduce:**
Wrap all the information in the page with <ion-content> and swipe to close should not work.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by ishaiavrahami** [comment]
For example:
`<ion-content> <ion-list> items.... </ion-list> </ion-content>` <---- this wont Swipe to close the modal

however if i render this:
`<ion-list> items.... </ion-list>` 

without `<ion-content>` like this:
` <ion-list> items.... </ion-list>`

it will work swipe to close the modal

**Comment by liamdebeasi** [comment]
Can you please provide a full repo with the code required to reproduce this issue? The code snippet does not give me enough context to understand the issue you are running into.

**Comment by ishaiavrahami** [comment]
Ive included a link below, to reproduce remove the <ion-content> from the innerHTML
https://codepen.io/ishaiavrahami/pen/gOagOMe?editors=1000

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Your page is setup incorrectly, which is likely the reason why the swipe to close modal is not working properly.

1. Your `presentingElement` is targeting the wrong element. It should target the presenting page, not `ion-app` as your modal will be added inside of `ion-modal`.
2. Your modal content needs `ion-content` otherwise styling may look off.

The swipe to close gesture listens on the `ion-header` of your modal, so you need to swipe from there in order to close the modal.

Here is a CodePen with the correct usage: https://codepen.io/liamdebeasi/pen/RwWKwQy
