### ISSUE TITLE
Ionic react displays white space after installation and debuts Typescript error reports

### ISSUE THREAD

**Issue by q5222777** [ionic-team/ionic#21123]
Ionic react  is not compatible with the android browser kernel webview  and displays white space when accessed.
Android Version：7.0
Google Webview Version：51.0.2704.91
@ionic/react Version：^5.0.7
![1587701241060](https://user-images.githubusercontent.com/35521129/80174066-2e2f0700-8624-11ea-8cbb-482fd9a395e8.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Stencil, the web component compiler Ionic is built with, only supports Chrome 60+. You will need to bundle certain polyfills in order to get the application to run. There are 2 things we recommend:

1. Modify the `browserslist` portion of your `package.json` to include support for older versions of Chrome. This is useful for indicating which polyfills to bundle with your application. For example, I was able to add `>0.2%` to the `development` array in `browserslist`, and additional polyfills were bundled during a dev build of the app. See https://github.com/browserslist/browserslist for more examples.

2. There may be polyfills you need even after modifying `browserslist`. If that is the case, we recommend bundling those polyfills yourself. You can usually find a polyfill for a certain API with a quick search. For example, here is a doc which contains a polyfill for `Array.from`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from.

Hope this helps!
