### ISSUE TITLE
bug: Ionic React pages that are not children of tabs still show the tabbar

### ISSUE THREAD

**Issue by q5222777** [ionic-team/ionic#21125]
ionic React

There was no way to hide the IonTabBar at the bottom when I entered the secondary page

If IonTabBar is removed, an error will be reported as shown below

Can you add a hidden bottom IonTabBar property?

![1587751306852](https://user-images.githubusercontent.com/35521129/80243274-805e3f80-8699-11ea-941a-54c14c80511f.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This looks like a bug in Ionic React.

Typically, if you wanted to hide the tabbar on navigating you should configure your routes such that the page is not child of a tab.

For example, the following configuration would cause the tabbar to appear because the page is a child of a tab:

```tsx
<Route path="/tabs/tab1/child" component={ChildPage} />
```

But this configuration would cause the tabbar to transition away because the page is a child of the root routing context, not a tab:

```tsx
<Route path="/child" component={ChildPage} />
```

**Comment by liamdebeasi** [comment]
Actually it looks like this is a duplicate of https://github.com/ionic-team/ionic/issues/20753. I am going to close this in favor of the bug I linked.
