### ISSUE TITLE
feat: add ionBackdropTap event listener when backdropDismiss modal property is set to false

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic#21200]
# Feature Request

**Ionic version:**
[x] **5.0.0**

**Describe the Feature Request**
When showing a modal, the `ionBackdropTap` event is only triggered when the modal's`backdropDismiss` property is set to true.

Would it possible that this event is triggered even when `backdropDismiss` property is set to false?

That would be useful typically when one wants to add their own handler on backdropTap, e.g. make sure there is no pending change, before dismissing the modal or not.

**Describe Preferred Solution**
Allow ionBackdropTap event to trigger when `backdropDismiss` property is set to false.

**Describe Alternatives**
Propose a way to abort the dismiss action from `onWillDismiss` method, if possible.

**Additional Context**
I first opened [a thread on Ionic forum](https://forum.ionicframework.com/t/modal-dismiss-how-to-abort-dismiss-if-changes-are-pending/188527) related to that.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The existing behavior is intentional. I think emitting `ionBackdropTap` when a backdrop should not be tappable would be confusing. If you would like to override this behavior, we recommend you add a custom click handler on the backdrop (You can select the `ion-backdrop` with a `querySelector`. Thanks!

**Comment by manu2504** [comment]
Great idea, I could select the ion-backdrop with a click event indeed. Thanks!
