### ISSUE TITLE
bug: preloadingStrategy: PreloadAllModules broken in IONIC 5

### ISSUE THREAD

**Issue by Bretto** [ionic-team/ionic#21380]
# Bug Report
All the IONIC components in my features are not being loaded lazily, so nothing works in offline mode. How can I load all the ```chunk {38} 38.js, 38.js.map () 27.9 kB  [rendered]``` so that my app will work in offline mode ?

**Ionic version:**

[x] **5.x**

**Current behavior:**

```index-e23c3ffd.js:1966 ChunkLoadError: Loading chunk 38 failed.```
**Expected behavior:**

Ionic should work in offline mode

**Steps to reproduce:**

try loading a feature in offline mode
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I double checked with the team, and `PreloadAllModules` preloads all routes, not the specific Ionic components since those are separate from Angular.

As I mentioned in the other issue you filed, all Ionic components are lazy loaded to improve initial render time: https://github.com/ionic-team/ionic/issues/21379#issuecomment-634648519

**Comment by kensodemann** [comment]
@Bretto - RE: offline, have you looked into using the Angular service worker package at all (https://angular.io/guide/service-worker-intro)?

I use it in a couple of different projects and find that it works great for that.
