### ISSUE TITLE
bug: Route components not being unmounted correctly

### ISSUE THREAD

**Issue by allforabit** [ionic-team/ionic#21558]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Route components aren't unmounted correctly after navigation and preserves the state of components.

**Expected behavior:**
It should be a "clean slate" when re-entering route components similarly to how it works with other react components.

**Steps to reproduce:**
I have linked a code sand box that shows the issue. Each route has a stateful component (using xstate) and on browsing between the two routes the state is preserved between the routes. Note this doesn't happen with react's `setState` but does happen in this case due to the use of `useRef`. As noted on the react docs, useRef should only last for the lifetime of the component which suggests that the components aren't being unmounted. 

**Related code:**

https://codesandbox.io/s/ionic-react-router-h9v54

**Comment by liamdebeasi** [comment]
Thanks for the issue. The application does not load for me, and there are several errors in the console. Can you double check the repo?

**Comment by allforabit** [comment]
Thanks for getting back to me. I don't know what happened there but the code sandbox seems to be completely broken. It was working properly when I posted, sorry about that. Will get back to you when I figure out what's up with it!

**Comment by allforabit** [comment]
I tried setting up a fresh sandbox but ionic and sandbox don't seem to be playing together for some reason: https://codesandbox.io/s/gifted-sun-62vvv I'll try again in a day or two.

**Comment by liamdebeasi** [comment]
Feel free to make a GitHub repo if that's easier.

**Comment by allforabit** [comment]
Here you go: https://github.com/allforabit/ionic-react-router I tried it on my local machine and is working. Let me know if you have any problems with it.

**Comment by elylucas** [comment]
Hi @allforabit,

This is by design. The lifetime of Routes in a IonRouterOutlet are handled by Ionic for page transitions and to return to the same state when you navigate back to the component.We have our own lifecycle methods that will let you detect when an Ionic Page is entered and left as well. 

See our navigation and lifecylce guides for more info:
https://ionicframework.com/docs/react/navigation
https://ionicframework.com/docs/react/lifecycle

However, we know this is always desired from the dev's perspective. We got some changes coming in the next release of ionic/react-router that will give some more control. Look for that soon.

Thanks

**Comment by allforabit** [comment]
OK that's brilliant to hear thanks very much! I've been working with react for a few years and I was finding it hard to wrap my head around how things were working with ionic. Looking forward to the new version as I'd prefer to use the react lifecycle if possible. I'm experimenting a little with directly using react router and adding my own transitions and it works reasonably well. A nice feature of ionic is being able to pick and mix like this.
