### ISSUE TITLE
feat: Max scroll distance for ion content scrolling

### ISSUE THREAD

**Issue by Husnain-Asharf** [ionic-team/ionic#21576]
# Feature Request

**Ionic version:**
[x] **5**

**Describe the Feature Request**
- Ion content should have property for max scroll distance. It will help to increase performance.
   If user in long list trying to scroll fast then there is chance of lagging or white blank screen 
  especially in virtual scroll case. 
- So there should be a way to to control ion content scrolling to not scroll very fast so that white 
   blank screen issue can be resolved.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you please clarify the problem you are trying to solve?

**Comment by Husnain-Asharf** [comment]
- Actually i have long list of card items almost 250px height. I am using virtual scroll. When i scroll fast, first white screen appear then it get painted. It looks not good. For that i was looking for solution if we can control maximum scroll distance. So user should be able to maximum scroll to specific distance  at a time.

- I can use infinite scroll for data load in chunks but once all data loaded then i will use virtual scroll but still same problem i will face.

**Comment by indraraj26** [comment]
I agree with you I had similar issue in my chat application. i don't think so there will be an reliable solution for that.

**Comment by Husnain-Asharf** [comment]
> I agree with you I had similar issue in my chat application. i don't think so there will be an reliable solution for that.

So what you did if you had same issue.

**Comment by indraraj26** [comment]
i just keep it that way there no otherway around to solve this problem, Great that you got virtual scroll working that i couldn't do it on my application because chat message has attachment like we are having in whatsapp so the height and width of each item is differ virtual scroll needs static height of your item. i am just using infinitescroll with top position. I have checked facebook lite application in that chat section you will see you can't scroll whole chat, either you will have to press previous message (top) or older message (bottom) with that their dom is clean doesnt have lot of elements.

**Comment by Husnain-Asharf** [comment]
Looking for authentic solution.

**Comment by roman-rr** [comment]
I don't think 250px height cards is a properly case to using with virtual scroll.

**Comment by Husnain-Asharf** [comment]
> I don't think 250px height cards is a properly case to using with virtual scroll.

But i want to use cards. What you suggest roman.

**Comment by roman-rr** [comment]
@Husnain-Asharf Have you try to use default *ngFor ?

**Comment by Husnain-Asharf** [comment]
> @Husnain-Asharf Have you try to use default *ngFor ?

@roman-rr  yes i tried but when list become large it become slow

**Comment by liamdebeasi** [comment]
Thanks for the clarification! I do not think Ionic Framework will be able to provide a solution here regarding managing scroll speed. Scrolling is handled by the browser, so we do not control that.

Regarding the white space when scrolling quickly, one thing I can recommend is using the Angular CDK Scroller instead of `ion-virtual-scroll`: https://material.angular.io/cdk/scrolling/overview. We are trying to move developers to this solution since it is less buggy and much more performant.

Hope this helps!
