### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by AlvaroZ-F** [ionic-team/ionic#21592]
My code is giving me this error...
![image](https://user-images.githubusercontent.com/56718986/85232323-5fe30500-b3fe-11ea-9458-705a64dc034d.png)

But if I look at all the modules, I'm loading the IonicModule. This ONLY happens when running ionic build. Not when I run ionic serve.
I saved the code in my rep: https://github.com/AlvaroZ-F/covid-track-pwapp

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am not getting that error when running `ionic build` using the repo you provided. Can you reproduce this issue with a blank Ionic starter?

**Comment by AlvaroZ-F** [comment]
Hello, and I tried to create a new blank project, and run build.
Runs without any issue, it's only with this repository.. I've tried to create a new project and replace the src files with the ones I've got in the repository, but with the same result

**Comment by liamdebeasi** [comment]
Thanks for the follow up. There is likely some configuration issue in your project as this issue is not found in Ionic starter apps. It sounds like Angular is not recognizing Ionic components based upon the error you received.

I am going to close this as this is more of a support question, but feel free to post on our [forum](http://forum.ionicframework.com/) for any additional support. Thanks!
