### ISSUE TITLE
bug: ion-select marked by AXE with "Certain ARIA roles much contain particular children"

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#21601]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
This is reproducible with the example mentioned in ionic site: https://ionicframework.com/docs/demos/api/datetime/index.html?ionic:mode=ios

This is item 8 in the document shared in the internal Framework Slack channel.

**Comment by liamdebeasi** [comment]
There are 2 issues here. The first is that `ion-select` is being treated as a combobox, which is not correct. There is no textbox in `ion-select` currently. This leads to the issue reported here, and is fixed by https://github.com/ionic-team/ionic/pull/21609.

The second issue is that axe seems to look at the elements passed in to `ion-select` as well as elements in the shadow root. This was verified by one of the axe developers: https://github.com/dequelabs/axe-core/issues/2318. As a result, axe will say that not all child elements have `role="option"`. This is going to require a refactor of `ion-select` and will be tracked in https://github.com/ionic-team/ionic/issues/21548.
