### ISSUE TITLE
bug: IonScroll event are not triggered

### ISSUE THREAD

**Issue by BeataG** [ionic-team/ionic#21681]
# Bug Report

**Ionic version:** 
3.6.0

**Current behavior:**
The ionScroll events are not triggered on ion-content if there is ion-slides inside it

**Expected behavior:**
IonScroll event should be triggered

**Related code:**

```
<ion-content (ionScroll)="scrollHandler($event)">
  <ion-slides>
    <ion-slide>
      <div> Something </div>
    </ion-slide>
    <ion-slide>
      ...
    </ion-slide>
 </ion-slides>
</ion-content>
```

Method scrollHandler is never triggered

Is the same issue as here: [https://github.com/ionic-team/ionic/issues/13188](#13188) but there is no solution for this and adding div below ion-slides as suggested is not working

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please see the documentation: https://ionicframework.com/docs/api/content#properties. It states that `scrollEvents` must be set to `true` for scroll events to be emitted.

Additionally, scroll events do not fire on `ion-slides` because there is no scrolling. All transforms of `ion-slides` are done with `translate3d` in CSS.
