### ISSUE TITLE
Please provide option to validate form elements like <ion-input>, <ion-select>, <ion-textarea>

### ISSUE THREAD

**Issue by dheran** [ionic-team/ionic#6040]
**ionic v2**

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You can already do form validation in Ionic 2 using the angular 2 forms/formbuilder module. Thats the great thing about Ionic 2, it includes all the awesomeness from Angular 2! Here is a link to the Forms docs on the Angular 2 site: https://angular.io/docs/ts/latest/guide/forms.html Thanks again!

**Comment by dheeran1** [comment]
in angular required attribute will work but in ionic (ion-select. ion-input) required attribute doesn't seems to work.

**Comment by dheeran1** [comment]
@adamdbradley @brandyscarney Is there a way to validate <ion-input>, <ion-select>, <ion-textarea>

**Comment by tlaverdure** [comment]
Wanted to point out an issue I've come across using the angular2 formbuilder with an ion-input using the required attribute. If you focus in and then focus out I would expect the input to have the ng-invalid class added, but it doesn't.

**To summarize:**
- The ion-item class wrapping the ion-input has a the class **ng-valid**
- The ion-input has the class **ng-invalid**
- The actual input field has the class **ng-valid**

**See also:**
https://forum.ionicframework.com/t/ion-input-and-ion-item-validation-classes-dont-match/48895

**Comment by xr0master** [comment]
@tlaverdure +1 
@brandyscarney Validation works but have some issues )

First:
.item-inner has padding-right 8px, but ion-input::after hasn't
![image](https://cloud.githubusercontent.com/assets/8962340/15182470/4a983a1c-1795-11e6-8c36-ac371a7329aa.png)
btw why do you use position: static instead of position: relative?
something like;
```
.item-input ion-input, .item-input ion-textarea {
    position: relative;
}
ion-input::after {
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    border-bottom-width: 2px;
    border-bottom-style: solid;
    border-bottom-color: transparent;
    content: "";
}
```

Second:
ion-select doesn't show an any notification. And it is always valid for NgForm. So I can submit invalid form. I think, it happens, because ngControl can't understand the not input element...

**Comment by WHarris22** [comment]
+1 it looks like you are already working on this but thought I would explain my reason for needing it... 

My reason for wanting `ion-input` to get updated with the valid / invalid class is so I can change the color attribute in the `<ion-label>`. I can't find a way of doing this at the minute, but once `ion-input` gets updated with the correct valid / invalid class is should be targetable with CSS selectors :)

**Comment by WHarris22** [comment]
What I have noticed is that `<ion-item>` gets updated with other classes such as `ng-dirty` and `ng-touched` but it always stays as `ng-valid` even when `<ion-input>` has `ng-invalid` assigned. Here is an image to show you what I mean...

![ionic2-form-validation](https://cloud.githubusercontent.com/assets/8298764/15245088/7b7271bc-18fc-11e6-962d-1cad1b94ca8b.png)

For me it would be useful if `<ion-item>` got updated with `ng-invalid` because I want to be able to change the text color of `<ion-label>` accordingly. At the minute I don't see a way of targeting it with CSS selectors.

**Comment by brandyscarney** [comment]
So there is a lot going on on this issue. I'm going to try to address everything but let me know if there is something I miss.

@dheran: I'm not sure what you are looking for in terms of validation. Could you please explain what you mean? The form validation Angular 2 offers should be what you need but if you could explain more of what you want, I can help more. :smile:

@tlaverdure: Thanks for bringing this to our attention. I have fixed this in the repo, and published a nightly version of the framework where it can be tested. Could you please take a look and let me know if you find any issues? To install the nightly version:

```
npm install --save ionic-angular@2.0.0-beta.7-201605211713
```

If you haven't updated to `beta.7` yet please follow the guide in the changelog to update: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#angular-update-to-200-rc1

@xr0master: Thanks for letting me know about the UI issues. I've updated the UI to extend the length of the item and added Sass variables for turning off success/error highlighting:

```
$text-input-md-show-success-highlight:      true !default;
$text-input-md-show-error-highlight:        true !default;
```

There is another issue for this ([#5052](https://github.com/driftyco/ionic/issues/5052)), could you please put any feedback you have for improving success/error highlighting on that issue? 

@WHarris22 I believe your issue is the same as @tlaverdure mentioned. Please read my above response to him. 

Here's a gif of my most recent changes:

<img src="http://g.recordit.co/OJNiMwGqXn.gif">

Source code for this is here:
https://github.com/driftyco/ionic/tree/7c0fe93061fc17d1e023698983b7b58d9b82f0a9/src/components/input/test/form-inputs

Thanks everyone! :smile:

**Comment by xr0master** [comment]
@brandyscarney Very cool! Can you implement it for ion-select too, please? And can you append ability to change the line color? It'll be amazing.

BTW iOS hasn't this validation syntax (bottom line); It will be fixed? Or iOS hasn't validation style?

About the another issue (https://github.com/driftyco/ionic/issues/5052). I think no special about it, any container with ngSwitch directive. Something like a ngMessages directive of md, IMO. You need be carefully with a long text and an animation (changing the error message to another). It'll be cool, if we could disable the animation and change the error text color too.

PS Thanks you for your amazing work

**Comment by brandyscarney** [comment]
Yes, I'll be working on adding it to the select next. :smile:

I'm not sure about adding validation style to iOS, it's something that needs to be discussed. 

I agree with the ngMessages directive. There has actually been an issue created with that in mind here: https://github.com/driftyco/ionic/issues/6785

**Comment by dheran** [comment]
@brandyscarney  after updating to beta 8, it show's red highlight for ion-input and ion-textarea even they got right inputs. I didn't explicitly mentioned required or * any where. Also I handled validation by myself, is there a way to disable it.

**Comment by brandyscarney** [comment]
@dheran 

The highlighting can be turned off via the following Sass variables:

```
$text-input-md-show-success-highlight:      false;
$text-input-md-show-error-highlight:        false;
```

and to change the colors:

```
// Input highlight - normal
$text-input-md-highlight-color:             color($colors-md, primary);

// Input highlight - valid
$text-input-md-hightlight-color-valid:      color($colors-md, secondary);

// Input highlight - invalid
$text-input-md-hightlight-color-invalid:    color($colors-md, danger);
```

The issue is a WIP so please add any feedback on #5052. Thanks!

**Comment by WHarris22** [comment]
As I discussed in [this closed issue](https://github.com/driftyco/ionic/issues/5916) I think it would be useful to be able to validate inputs inside the alert prompt component.

Not sure how you could go about this, but one idea is to have more options under the input option to provide validators and error messages? 

e.g.

```
inputs: [
      {
        name: 'username',
        placeholder: 'Username'
      },
      {
        name: 'password',
        placeholder: 'Password',
        type: 'password',
        validation: [ { validator: 'type of validation', message: 'error message' } ]
      }
    ]
```

**Comment by AntoineGermanique** [comment]
Hey, 
Is required supposed to work on ion-select now ? For me it doesn't .
Thanks for your help!

**Comment by BradyLiles** [comment]
Is there any update on making the classes on ion-item for ion-select, etc?
I can do a pull request, but i'm guessing that there needs to be a base class for these controls...
most likely the base class for ion-input: `IonicFormInput` 

And will need to implement some common functionality among all of them... Like the `setControlCss `function

```
function setControlCss(element: any, control: NgControl) 
{
  element.setElementClass('ng-untouched', control.untouched);
  element.setElementClass('ng-touched', control.touched);
  element.setElementClass('ng-pristine', control.pristine);
  element.setElementClass('ng-dirty', control.dirty);
  element.setElementClass('ng-valid', control.valid);
  element.setElementClass('ng-invalid', !control.valid);
}
```

As well as injecting and implementing NgControl into every input control component.

**Comment by abner** [comment]
@BradyLiles  Have you already started to work on this issue? I want to join forces with you.

**Comment by tommck** [comment]
ion-select still doesn't work with required attribute

**Comment by brianlittmann** [comment]
A bit of a hack, but a quick workaround for me for anything other than `ion-input` was to conditionally add classes based on the FormGroup control's `valid` state:
```html
<ion-item [class.ng-invalid]="!profileForm.controls.state.valid">
    <ion-label stacked>State</ion-label>
    <ion-select formControlName="state">
        ...
    </ion-select>
</ion-item>
```

**Comment by apappasmllrdev** [comment]
@brianlittmann ,
How do I implement it inside this kind of form?

```html
<form (ngSubmit)="save(f.value)" #f="ngForm">
    <ion-item [class.ng-invalid]="!f.controls.state.valid">
        <ion-label for="Person">Person</ion-label>
        <ion-select name="Person" [(ngModel)]="selectedPerson" formControlName="state">
            <ion-option *ngFor="let person of people" [value]="person .Id" required>{{person.Name}}</ion-option>
        </ion-select>
    </ion-item>

    <button ion-button block type="submit" [disabled]="!f.valid">Save</button>
</form>
```

I get this error:
` formControlName must be used with a parent formGroup directive.  You'll want to add a formGroup`

**Comment by cyptus** [comment]
ionic is automatically validating the input fields, but it misses to update the parent ion-item if a control is marked as touched (markAsTouched() Method on control) from code. I've a next button which should mark all untouched and invalid controls as invalid (red border). i have to update the parent ion-item style manually like this:

`  next()
  {
    for (var controlName in this.personForm.controls) {
      let ele = document.querySelector('[formControlName="' + controlName + '"]');
      this.personForm.controls[controlName].markAsTouched();

      if(ele) {
        this.setControlCss(ele.parentElement.parentElement.parentElement, this.personForm.controls[controlName]);
      }
    }
  }

  setControlCss(element: any, control: AbstractControl) 
  {
    this.renderer.setElementClass(element, 'ng-untouched', control.untouched);
    this.renderer.setElementClass(element, 'ng-touched', control.touched);
    this.renderer.setElementClass(element, 'ng-pristine', control.pristine);
    this.renderer.setElementClass(element, 'ng-dirty', control.dirty);
    this.renderer.setElementClass(element, 'ng-valid', control.valid);
    this.renderer.setElementClass(element, 'ng-invalid', !control.valid);
  }`

see also: https://forum.ionicframework.com/t/ionic-form-validate-from-code-remove-ng-untouched/98010/2?u=cyptus
