### ISSUE TITLE
NavController lifecycle events interfaces

### ISSUE THREAD

**Issue by ysgk** [ionic-team/ionic#7512]
#### Short description of the problem:

_NavController_'s lifecycle events should have interfaces.
#### What behavior are you expecting?

Provide interfaces, which compel us to implement the corresponding methods like `OnInit` in Angular2, in order to benefit from typing and editor tooling.

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind explaining a little more about your suggestion? To hook into a lifecycle event you simply use http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events , so I am a little unclear of why these would need an interface of any kind. Thanks for using Ionic!

**Comment by cither1** [comment]
If these interfaces are provided, it is visible that the component implements the feature correctly; it eliminates the possibility of typos. Even if the methods should be renamed in the future, we can detect that change.

Besides, we could benefit from an IDE.
We have to refer to the doc page to know the name of the methods every time without these interfaces. But some IDEs are intelligent enough to suggest apposite candidates in an `import` sentence.

For example, we only have to type `On` in the curly brackets below to see the list of the lifecycle interfaces provided by Angular2: `OnInit`, `OnChanges`, and `OnDestroy`.

`{ } from '@angular/core';`

We only have to choose one of them and declare it in order to know which methods should be implemented.

I think it would be nice that ionic could provide such features. Thanks. :)

**Comment by ValterSantosMatos** [comment]
+1

**Comment by fknop** [comment]
@jgw96 These interfaces follow the design of `Angular 2` with `OnInit`, etc.

I could maybe make a PR to add them.

**Comment by jgw96** [comment]
@fknop that would be awesome! Let me know if you need any help!

**Comment by fknop** [comment]
@jgw96 https://github.com/driftyco/ionic/issues/7770 But you already answered it!

**Comment by jvbianchi** [comment]
Any news?

**Comment by manucorporat** [comment]
@jvbianchi @fknop @ValterSantosMatos @ysgk 
please feedback!! https://github.com/driftyco/ionic/pull/10649

**Comment by BradyLiles** [comment]
I love it @manucorporat.
Is there a reason why this is not being included in the previous releases?
