### ISSUE TITLE
Tabs select method should return a promise

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic#8662]
Feels like it should.

Consider the following.

You want to change tabs from tab1 to tab2, then also push a page on tab2. With the current setup, it's not really possible.

It should be possible to do 

```
this.navCtrl.parent.select(1).then(
  ()=> this.navCtrl.push(Page2)
)
```

**Comment by AlGantori** [comment]
1st time I see this bug and I am surprised this is an **enhancement** request.  While I am trying to get the loose ends to work with RC0...RC6...2.0.0 upgrades I have hit on exceptions about .then() like so:
```
Error in ./MediaListComponent class MediaListComponent - caused by: Cannot read property 'then' of undefined
```
when this code executes
```
        if (Media._TYPE == "AMS") {
            this.NavController.parent.select(this.GlobalService.TabsIndex.AMSPlayer).then(() => {
                this.PlayersView.YTPlayerHide();
                this.PlayersView.AMSPlayerShow();
            });
```
I can't recall which URL exactly I picked up the select returning a promise, but I would swear the code above was working around December 2016 when I filed this bug
https://github.com/driftyco/ionic/issues/9431

Now under 2.0.0 when typing first via Tabs : Tabs = this.NavController.parent ;
it shows Tabs.select(..) will not return a promise.  However, when calling off of this.NavController.parent.select(...).then(()  no doc pops up I think because parent is type any.

Anyways, please review this because even though the tab selection occurs after select by calls to the target tab component don't see to take effect.
https://github.com/driftyco/ionic/issues/9431

Thank you.

**Comment by AlGantori** [comment]
I was not dreaming here someone questioning why it's gone. I could not find anything mentioned in the "breaking changes" 
https://forum.ionicframework.com/t/ionic-2-rc0-navcontroller-parent-select-0/65758

**Comment by AlGantori** [comment]
Any hope to get this addressed soon?  Can you show me how to code a workaround, somehow make a promise out the tab select so before I emit an event I ensure the target page at the new tab has loaded and has subscribed to the event.  Something equivalent to:

```
this.Tabs = this.NavController.parent;
this.Tabs.select(TargetTabIndex).then(()=> {
        this.Events.publish("Play");
});

```
Thank you.

**Comment by frystpingvin** [comment]
Any updates and/or workaround to this? The only workaround I seem to be able to use is to set a timeout on the page push, but that's far from a good solution.
