### ISSUE TITLE
back failed via system's back button

### ISSUE THREAD

**Issue by izee** [ionic-team/ionic#8895]
#### Short description of the problem:

Navigated  from tabsPage via ionSelect and NavController, could not back via system's back button.

**Steps to reproduce:**
1. in tabsPage like ionic2-starter-tabs.
2. modify an `ion-tab` without `root` and hook `ionSelect` event to push any other page.
3. click the modified `ion-tab` and then navigate to `other page`.
4. in `other page` click system's back button, **nothing happened**.
5. click system's back button again, navigate to tabsPage success.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

> Your system information:
> 
> Cordova CLI: 6.3.1
> Ionic Framework Version: 2.0.0-rc.1
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> Ionic App Scripts Version: 0.0.36
> OS:
> Node Version: v6.7.0

**Comment by kensodemann** [comment]
Hello! Is this still an issue with the latest version of ionic?

Several items have been fixed with regard to the hardware back-button with the most recent fixes being in version `3.6.1` of ionic-angular. I don't _think_ what you have above is still an issue, but I could be completely wrong.

If it is still an issue, please provide a sample application via GitHub that duplicates the issue (if possible) and I will be happy to reopen this issue.

Thanks!
