### ISSUE TITLE
Ionic 2 RC1 - ion-item with ion-select does no longer have input state classes like ng-untouched

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/ionic#8935]
#### Short description of the problem:

Since the update to rc.0 / rc.1 the ion-item containing an ion-select does no longer have input state classes like ng-untouched.
Not 100% shure but I think they were there in beta.11, but they should be there anyway.

Item with ion-select looks like this:

```
<ion-item class="item-block item item-md item-label-fixed item-select">
```

While an item with ion-input looks like this:

```
<ion-item class="item-block item item-md item-label-fixed item-input ng-untouched ng-pristine ng-invalid">
```

**Which Ionic Version?** 1.x or 2.0.0-rc.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v4.5.0

**Comment by lucasbasquerotto** [comment]
The `ion-item` also doesn't reflect the states `ng-valid` and `ng-invalid`, so there is no border bottom, green or red, according to the state.

The same happens with `ion-datetime` and custom inputs.

See: [https://forum.ionicframework.com/t/connect-my-custom-input-with-ion-item/84781](https://forum.ionicframework.com/t/connect-my-custom-input-with-ion-item/84781)

The inputs themselves have the correct state though, **the problem is that the state is not reflected** to the `ion-item`.
