### ISSUE TITLE
ion-content without ion-nav is not resized

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/ionic#8980]
See this plunk: [plnkr.co/edit/B8Itlq](http://plnkr.co/edit/B8Itlq?p=preview)

I'm preparing a simple example with a single page, no need for navigation, so I have a single component with a basic template

```
<ion-header>...</ion-header>
<ion-content>...</ion-content>
```

However the top of the content is hidden under the header. When using an `<ion-nav>` wrapping a page component I can see that the `div class="scroll-content"` inside the `ion-content` somehow gets a `style="margin-top: 56px;"` and the content is fully visible.

But without the `ion-nav` there is no such `margin-top` and the content is partially hidden. I don't see why I would need to use `<ion-nav>` if I don't need navigation?

Version: Ionic 2.0.0-rc.1

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So, this is actually expected behavior as our components have the expectation of being wrapped in an `ion-nav` and rely on that component to be there to have the correct styling. I am however going to leave this one open to discussion as it does, in a way, seem like too much magic, and in a case such as yours when their is no need for an `ion-nav` component, it does not make sense to have to add one anyways just to get the right styling.

**Comment by mirkonasato** [comment]
Seems like calling [Content.resize](http://ionicframework.com/docs/v2/api/components/content/Content/#resize) in `AppComponent.ngAfterViewInit` gives it the right `margin-top` even without `ion-nav`. I wonder if this resizing could be done automatically by the `ion-content` component?

**Comment by jgw96** [comment]
That "should" not have other side effects and "should" be a good workaround for the moment, but im not 100% on that.

**Comment by tleguijt** [comment]
I have the same issue.
Calling ``this.content.resize()`` from ``ngOnInit`` doesn't really does the trick for me since the content is initially empty and receives it's content after the Component itself is loaded.
Right now for me the best option was to move the content of the ``ion-header`` to ``ion-content``.

In my case it isn't a Page object, but a side-menu component.
The following was in my ion-header but now moved to ion-content:

      <ion-toolbar>
        <ion-title>Profile info</ion-title>
      </ion-toolbar>

**Comment by biesbjerg** [comment]
@tleguijt Try the ngAfterViewInit hook instead: https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html
