### ISSUE TITLE
Support for canLeave/canEnter in Tabs

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#9056]
As commented here:
https://github.com/driftyco/ionic/issues/9000#issuecomment-258672034

It seems legit to support canEnter/canLeave in tabs, since we already dispatch lifecycle events when switching between apps.

It should be straightforward to add, but I am not sure if this is a feature or a fix.

Probably we should wait until 2.0 final is released.

ping @adamdbradley

**Comment by FdezRomero** [comment]
Hi @manucorporat and @jgw96!

I'm refloating this issue because we are currently having issues with nav guards and tabs on Ionic 3.1.1.

If the root page of a tab returns `false` in `ionViewCanEnter`, the view is broken as nothing is rendered. This is supported when you `push()` a page as Ionic automatically does `pop()` if this happens. The Tabs component shouldn't activate the new tab when it returns `false` and stay at the current one, or if it has to activate the new tab at least automatically go back to the previous one.

I'm commenting this because I see you are fixing navigation issues for PWAs in #11101 and it may be a great time to address this as well.

Thanks!

**Comment by vovikdrg** [comment]
In addition to that i would like to be able to configure default login page.

`IonicModule.forRoot(MyApp, {OnRejectViewCanEnterPage: MyLoginPage }),`

So then i wouldn't need to even catch because framework should redirect me automatically to my login page

**Comment by vovikdrg** [comment]
I found dirty hack..
1. subscribe to event change
`ion-tabs (ionChange)="onTabChange($event)"`

2. Check if tab has any views.
public onTabChange($event, tabs) {
    if ($event._views && $event._views.length == 0) {
      $event.push(LoginPage);
    }
  }

PS. Potentially could be problem if tab root can be accessed and later child has ionViewCanEnter

**Comment by mavogel** [comment]
Nice hack @vovikdrg  :) That's what I needed but unfortunately after updating from from 3.0.1 to 3.3.0 the `canEnter` guard does not work any more -> see #11433

So I went back to the old `menu.enable` if the user is logged in until this and the other issue are solved

**Comment by vovikdrg** [comment]
@mavogel I am lucky that it works with tabs :)

**Comment by mchenx** [comment]
I have this issue too, I need some event like canEnter/canLeave to prevent switching a tab page to another

**Comment by Anthony2539** [comment]
I have the same issue, any update on this ?

**Comment by hiepxanh** [comment]
+1 guard for tab

**Comment by vovikdrg** [comment]
From what i understand ionic4 will fix this problem because if you use it with angular you can use angular guards. But lets wait :)
