### ISSUE TITLE
ion-item does not show line if it is in ion-card-content

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#9198]
#### Short description of the problem:
I tried to create a **ion-list** in an **ion-card**, but the ion-item does not show the expected line between the items if the **ion-list** is encapsulated in an **ion-card**.

#### What behavior are you expecting?
I'don't know if this is expected but I didn't found nothing in the documentation, and that's not the thing I expecting.

**Steps to reproduce:**
You can see here a plnkr with RC.2 which shows the two difference from a **ion-list** in and out of a **ion-card**
http://plnkr.co/edit/v8P1oV?p=preview

This is the result:

![image](https://cloud.githubusercontent.com/assets/3778892/20385997/f2e64b46-acb9-11e6-8202-f57551ae2314.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! This is by design to match the Material Design docs. See the following image of a list in a card:

<img src="https://material-design.storage.googleapis.com/publish/material_v_9/0Bzhp5Z4wHba3UERqREptcUE0VEE/components_cards_action6.png">

and the docs can be found here: https://material.google.com/components/cards.html#

**Comment by mburger81** [comment]
Hi @brandyscarney but in the docs you can also find some use cases like this.
Isn't this a card with a list which contains a divider in it?

![image](https://cloud.githubusercontent.com/assets/3778892/20518046/043b1222-b09e-11e6-96f2-6866fe6e7ca0.png)

**Comment by basvdijk** [comment]
I am running into the same problem. It would be nice if this was a attribute you could set instead of being forced to have no lines :)

**Comment by judgewest2000** [comment]
Using css you can throw these in...

https://forum.ionicframework.com/t/list-dividers-lines-in-cards/91734/5

**Comment by patrickmcd** [comment]
> This is by design to match the Material Design docs.

I'd like to question this decision as well. As shown by @mburger81 above, there are examples where lists in cards have lines, so it doesn't look like an actual MD spec. And even in the weather cards example above, the bottom "full report" item shows a separating line.

Since we have the `no-lines` attribute available to us, it should be up to the dev if that's the design we want to match.

Alternatively, you could add a `force-lines`, attribute but that feels cumbersome. I think it would be better for items to work the same way by default.

**Comment by brandyscarney** [comment]
Reopening to revisit, cc @bensperry @jgw96

**Comment by judgewest2000** [comment]
I concur with @patrickmcd - would prefer to have unless omitted specifically with `no-lines`

**Comment by lexyfeito** [comment]
any news on this, i having the same issue.. thank you

**Comment by JamboBuenna** [comment]
Any updates?
