### ISSUE TITLE
Keyboard Attatchement for Inputs, etc.

### ISSUE THREAD

**Issue by wbhob** [ionic-team/ionic#9199]
#### Short description of the problem:
Inputs in a footer bar generally do not show when they are active, as the footer bar does in native iOS. Tabs are occasionally raised with the keyboard (50% of the time or so).

#### What behavior are you expecting?
Active inputs to stick to the top of the keyboard.

**Steps to reproduce:**
1. Make ion-footer and put an input inside. (tested with just ion-footer and ion-footer > ion-toolbar)
2. Activate input on iOS.
3. Input stays beneath the keyboard.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2 RC2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by cozzbie** [comment]
+1. This right here is a major issue.

**Comment by cozzbie** [comment]
Why was this closed? @jqw96

**Comment by wbhob** [comment]
It was a duplicate... this issue is still open @cozzbie

**Comment by joshgarwood** [comment]
Any updates on this?  It's a UI-breaking bug at the moment for any inputs in an ion-footer element.

**Comment by burhanyldz** [comment]
Without this fix, creating a chat app with ionic is a pia :(

**Comment by joshgarwood** [comment]
Any feedback on this would be extremely appreciated.  It's been awesome seeing the advancement of the ionic platform recently, and how it can handle desktop apps now.  But there are still major/fundamental issues with your bread and butter mobile solution (which many many users need) that would be great to see fixed/stabilized before new features like the side panel for desktop are released.

Is this not being tended to because it's a possible duplicate of this? https://github.com/driftyco/ionic/issues/10678

**Comment by wbhob** [comment]
Any news on input attatchment ?@jgw96

**Comment by cozzbie** [comment]
You can make a chat app @burhanyldz if you want. Just use ionics forRoot and set `tabsHideOnSubPages: true` that way you dont get pesky tabs popping up on your keyboard
