### ISSUE TITLE
Windows 10 - The keyboard open itself without focusing an input

### ISSUE THREAD

**Issue by ericdesa** [ionic-team/ionic#9643]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The virtual keyboard of an app running on Windows 10 with Edge or Cordova appear even if the user click outside an input. It occurred only if an input was previously used.

**Expected behavior:**
When clicking outside an input, the virtual keyboard should not appear

**Steps to reproduce:**
* go to http://ionicframework.com/docs/v2/components/#inputs on a Windows 10 tablet without any keyboard plugged
* tap on an input > the virtual keyboard opens (OK)
* tap outside the input > the virtual keyboard dismiss (OK)
* tap again outside the input > the virtual keyboard opens, without targeting any input (NOK)

**Ionic info:** 
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3-201612122136
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
Node Version: v6.8.1

I reproduce it on RC.2 & RC.3

**Comment by jrmlt** [comment]
+1
I've got the same behavior. In my case, it only applies to windows 10 running on desktop. I don't have this issue on windows 10 phone.
Tried on my ionicv1 app and on current ionic version super template.

This strange behavior appears if the keyboard is closed by blur or the tryHide() method of the InputPane (from the ionic plugin). If the keyboard is closed using the close button of the keyboard itself, it doesn't reappear.
Also, the keyboard is almost never hidden on blur, have to close it through the app.

Not sure how to analyze this issue since native call to _Windows.UI.ViewManagement.InputPane.getForCurrentView().tryHide()_ still causes the issue.

**Comment by jrmlt** [comment]
After some more research, Edge rendering engine on desktop seems to have issue handling focus/blur or show/hide keyboard by app/web.
See Edge issue tracker for some sample:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/217022/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5332283/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5438237/

I guess we could close this issue as it seems to be related to Edge :(

**Comment by bseverac** [comment]
Hello i've got the same here, have you find a workaround ?

**Comment by ericdesa** [comment]
I give up with the Windows Cordova engine. I use Electron instead for my windows target.
The keyboard is still an issue because i have to add a padding manually when the keyboard is open to be able to scroll on the full page, and I havent find a way to know when the keyboard is in "detached" mode or when a physical keyboard is plugged.

**Comment by bseverac** [comment]
thx !
