### ISSUE TITLE
RC4 ion-thumbnail img Images width and height set explicitly

### ISSUE THREAD

**Issue by cbetz** [ionic-team/ionic#9675]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
With the upgrade to RC4 I'm seeing the height and width explicitly set for img inside ion-thumbnail. Looks like it was changed here: https://github.com/driftyco/ionic/commit/a1542abbe404df1e5115fb5940d28f1db45a4e31

Appears $item-wp-thumbnail-size is setting the height/width now instead of the max-height/max-width. Just curious why the default changed. 

**Expected behavior:**
In previous versions (up to and including RC3) images were resized to fit in ion-thumbnail.

**Steps to reproduce:**

**Related code:**

```
<ion-list text-wrap>
        <ion-list-header>
            Header
        </ion-list-header>
        <ion-item tappable>
            <ion-thumbnail item-left>
                <img src="">
            </ion-thumbnail>
            <h2>Name</h2>
            <p>More text</p>
        </ion-item>
    </ion-list>
```

**Comment by cbetz** [comment]
I forgot to mention that $item-wp-thumbnail-size is setting the height/width now instead of the max-height/max-width. Is this correct?

**Comment by cbetz** [comment]
What is the best way to override this behavior if this is the new default? I have many, many images that are not square and will not look good stretched.

**Comment by brandyscarney** [comment]
Hello! Sorry for the long overdue response, but if you are still running into this, the following should help depending on your image width:

```
// Shared Styles
// --------------------------------------------------

.item ion-thumbnail ion-img,
.item ion-thumbnail img {
  width: auto !important;
}
```

Before:

<img width="416" alt="screen shot 2017-11-30 at 6 38 28 pm" src="https://user-images.githubusercontent.com/6577830/33460884-359b6124-d5fe-11e7-8226-87a79420126b.png">

After:

<img width="414" alt="screen shot 2017-11-30 at 6 41 49 pm" src="https://user-images.githubusercontent.com/6577830/33460885-35ab02f0-d5fe-11e7-8e89-9a8a15f0f430.png">

I am going to close this since this is something we have resolved for the next version, but if you're still having problems please let me know! Thanks!
