### ISSUE TITLE
Windows ion-toggle doesn't toggle until another click has been made on it or another UI element

### ISSUE THREAD

**Issue by joshstrange** [ionic-team/ionic#9732]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have an ion-toggle in my windows 10 app and when I first click it it does nothing. If I click it a second time it will toggle OR if I click another UI element (like a button) it will toggle. I do not experience this issue on iOS or Android.

**Expected behavior:**
Clicking the toggle results in the toggle changing state

**Steps to reproduce:**
````ionic start myapp --v2````
Add the following to the home.html page:
````
<ion-item>
    <ion-label>Save Password</ion-label>
    <ion-toggle checked="false"></ion-toggle>
</ion-item>
````

Build for windows:
````ionic run windows -- --arch="x64"````

**Related code:**

See above

**Other information:**
I can't find anything else mentioning this issue. I was seeing android UI (see: #6697) and I thought that might have something to do with it but forcing the windows UI still results in this bug.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.1
Xcode version: Not installed
```

**Comment by stevenhalase** [comment]
I also am running into this bug. However, I have noticed that this issue is also affecting building for the 'browser' platform. 

Currently if I run `ionic serve` or `npm run ionic:serve` the toggles work as expected. 

However, after having added the browser platform using `ionic platform add browser` and building for browser using `ionic build browser` the toggles do not work properly. This behavior is also present when building for Windows 10 as well using `ionic build windows`.

After fairly extensive testing, my suspicion is that events are colliding/interfering, specifically when Cordova is involved. 

I testing both using `ionic serve` and `ionic run browser`, on a preexisting project as well as a fresh project. Both exhibited the same bug in the browser platform and did not when being served without Cordova using `ionic serve`.

I did however see that when running from `ionic run browser` if I use Chrome DevTools to go into Responsive or any mobile device, the bug is not present. 

**Screen Captures**
Preexisting project `ionic serve` - Works
![image](http://oi68.tinypic.com/20iw1gj.jpg)


Preexisting project `ionic run browser` - Bugged
![image](http://oi65.tinypic.com/2r62mhf.jpg)

Fresh project `ionic serve` - Works
![image](http://oi68.tinypic.com/2m813jt.jpg)

Fresh project `ionic run browser` - Bugged
![image](https://vgy.me/jqFCQQ.gif)

**To Illustrate what happens in Responsive/Mobile through Chrome DevTools**
![image](https://vgy.me/VtyNWO.gif)

**Code from fresh project (the simplest implementation showing the bug)**
![image](https://vgy.me/XbyzN2.png)

This also happens event with only one toggle:
![image](https://vgy.me/dic4dj.gif)

![image](https://cloud.githubusercontent.com/assets/15740867/24318413/ef7f5a2e-10d2-11e7-9df6-274b63aac4d6.png)


Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.5
Xcode version: Not installed

**Comment by stevenhalase** [comment]
@jgw96 Any status on this?
